Repository etcd-io/etcd, pull requests merged in 2018-02, with the labels that each got.

#9296 mvcc: allow large concurrent reads under light write workload
  internal/mvcc/backend/backend.go
  internal/mvcc/backend/batch_tx.go
Labels: kind/need-release-note-v3.4

#9298 *: replace grpc-gateway endpoint with /v3
  Documentation/dev-guide/api_grpc_gateway.md
  Documentation/dev-guide/apispec/swagger/rpc.swagger.json
  Documentation/dev-guide/apispec/swagger/v3election.swagger.json
  Documentation/dev-guide/apispec/swagger/v3lock.swagger.json
  e2e/ctl_v3_test.go
  e2e/v3_curl_test.go
  embed/serve.go
  etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go
  etcdserver/api/v3election/v3electionpb/v3election.pb.go
  etcdserver/api/v3election/v3electionpb/v3election.proto
  etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go
  etcdserver/api/v3lock/v3lockpb/v3lock.pb.go
  etcdserver/api/v3lock/v3lockpb/v3lock.proto
  etcdserver/etcdserverpb/gw/rpc.pb.gw.go
  etcdserver/etcdserverpb/rpc.pb.go
  etcdserver/etcdserverpb/rpc.proto
Labels: kind/need-release-note-v3.4

#9185 etcdctl/check: create new check command for memory usage
  etcdctl/ctlv3/command/check.go
  etcdctl/ctlv3/command/util.go
Labels: kind/need-release-note-v3.4

#9339 embed: fix revision-based compaction with default value
  embed/config.go
  embed/config_test.go
  embed/etcd.go
Labels: kind/need-backport-v3.3

#9361 Documentation: make "Consul" section more objective
  Documentation/learning/why.md
Labels: Release-Backport/v3.2, Release-Backport/v3.3

#9347 etcdserver: enable "CheckQuorum" when starting with "ForceNewCluster"
  etcdserver/raft.go
Labels: Release-Backport/v3.2, Release-Backport/v3.3, Release-Note/v3.4

#9229 lease: Change lease Mutex to RWMutex
  lease/lessor.go
Labels: Release-Note/v3.4

#9369 auth: a new auth token provider nop
  auth/nop.go
  auth/store.go
Labels: Release-Note/v3.4

#8302 auth: a new option for configuring TTL of jwt tokens
  Documentation/op-guide/configuration.md
  auth/jwt.go
  e2e/cluster_test.go
  e2e/ctl_v3_auth_test.go
Labels: Auth, Feature, Release-Note/v3.4
