Repository etcd-io/etcd, pull requests merged in 2018-10, with the labels that each got.

#10156 etcdserver: add "etcd_server_health_success/failures"
  etcdserver/api/etcdhttp/metrics.go
  integration/metrics_test.go
Labels: Release-Note

#10155 rafthttp: probe all raft transports
  etcdserver/api/rafthttp/metrics.go
  etcdserver/api/rafthttp/probing_status.go
  etcdserver/api/rafthttp/transport.go
  etcdserver/api/rafthttp/transport_test.go
Labels: Release-Note

#10167 raft: provide protection against unbounded Raft log growth
  contrib/raftexample/raft.go
  raft/README.md
  raft/doc.go
  raft/node.go
  raft/node_test.go
  raft/raft.go
  raft/raft_test.go
  raft/rafttest/node.go
  raft/rawnode.go
  raft/rawnode_test.go
Labels: Release-Note

#10199 raft: fix bug in unbounded log growth prevention mechanism
  raft/node_test.go
  raft/raft.go
  raft/raft_paper_test.go
  raft/raft_test.go
  raft/rawnode_test.go
  raft/util.go
Labels: size/M

#10205 OWNERS: experiment
  OWNERS
  raft/OWNERS
Labels: size/M

#10207 *: Fix concurrent clientv3 client creation in 3.4 by using proper UUIDs
  bill-of-materials.json
  clientv3/client.go
  go.mod
  go.sum
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
Labels: Bug, clientv3, size/XL

#10212 raft: fix godoc in tests
  raft/raft_test.go
Labels: lgtm, size/XS

#10209 raft: Fix comment on TestLeaderBcastBeat
  raft/raft_paper_test.go
Labels: lgtm, needs-ok-to-test, size/XS

#10216 *: resolve shellcheck errors.
  build
  test
Labels: approved, lgtm, size/S

#10220 pkg/ioutil: n is equal or greater than cw.writeBytes
  pkg/ioutil/pagewriter_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#10227 Documentation/op-guide: fix error command to start gateway
  Documentation/op-guide/gateway.md
Labels: approved, needs-ok-to-test, size/XS

#10229 pkg/flags: fix "TestSetFlagsFromEnvParsingError"
  pkg/flags/flag_test.go
Labels: size/S

#10230 raft: Explain ReportSnapshot and Propose behavior
  raft/node.go
Labels: approved, lgtm, needs-ok-to-test, size/S
