Repository etcd-io/etcd, pull requests merged in 2018-08, with the labels that each got.

#9979 vendor: upgrade gRPC to v1.14.0
  Gopkg.lock
  scripts/updatedep.sh
  vendor/github.com/coreos/go-semver/example.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/doc.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/main.go
  vendor/github.com/golang/groupcache/byteview.go
  vendor/github.com/golang/groupcache/groupcache.go
  vendor/github.com/golang/groupcache/http.go
  vendor/github.com/golang/groupcache/peers.go
  vendor/github.com/golang/groupcache/sinks.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/wrappers.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/LICENSE
  vendor/github.com/prometheus/client_model/ruby/LICENSE
  vendor/github.com/spf13/cobra/cobra/cmd/testdata/LICENSE.golden
  vendor/golang.org/x/crypto/ssh/buffer.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/channel.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/connection.go
  vendor/golang.org/x/crypto/ssh/doc.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/mac.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/mux.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/session.go
  vendor/golang.org/x/crypto/ssh/streamlocal.go
  vendor/golang.org/x/crypto/ssh/tcpip.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/golang.org/x/text/doc.go
  vendor/golang.org/x/text/gen.go
  vendor/golang.org/x/text/internal/gen.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/match.go
  vendor/golang.org/x/text/internal/tables.go
  vendor/golang.org/x/text/secure/doc.go
  vendor/golang.org/x/text/unicode/doc.go
  vendor/google.golang.org/genproto/regen.go
Labels: Release-Note

#9985 raft: Make flow control more aggressive
  raft/raft.go
  raft/raft_test.go
Labels: Raft

#9977 clientv3: make saved snapshot readable by user only
  clientv3/snapshot/v3_snapshot.go
  clientv3/snapshot/v3_snapshot_test.go
Labels: Release-Note

#9982 raft: Introduce CommittedEntries pagination
  raft/log.go
  raft/node.go
  raft/node_test.go
  raft/raft.go
  raft/raft_test.go
Labels: Raft

#9990 etcdserver: add grpc interceptor to log info on incoming request to etcdserver
  Gopkg.lock
  bill-of-materials.json
  etcdserver/api/v3rpc/grpc.go
  etcdserver/api/v3rpc/interceptor.go
  etcdserver/etcdserverpb/raft_internal_stringer.go
  etcdserver/server.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/wrappers.go
Labels: Release-Note

#9998 etcdserver: add "etcd_server_id" metric
  etcdserver/metrics.go
  etcdserver/server.go
Labels: Release-Note

#9997 *: add v3 snapshot metrics (fsync, network)
  etcdserver/api/rafthttp/http.go
  etcdserver/api/rafthttp/metrics.go
  etcdserver/api/rafthttp/snapshot_sender.go
  etcdserver/api/snap/db.go
  etcdserver/api/snap/metrics.go
Labels: Release-Note

#10025 etcdserver: cherry pick of #9990 to release-3.2
  etcdserver/api/v3rpc/interceptor.go
  etcdserver/etcdserverpb/raft_internal_stringer.go
Labels: Release-Note

#10027 etcdserver: cherry-pick #9861 to release-3.3
  etcdserver/api/v3rpc/grpc.go
  integration/embed_test.go
Labels: Release-Backport/v3.3, Release-Note

#10026 etcdserver: clarify read index wait timeout warnings
  etcdserver/v3_server.go
Labels: Release-Backport/v3.1, Release-Backport/v3.2, Release-Backport/v3.3, Release-Note

#10024 etcdserver/api/rafthttp: clarify "became inactive" warning
  etcdserver/api/rafthttp/peer_status.go
Labels: Release-Backport/v3.1, Release-Backport/v3.2, Release-Backport/v3.3, Release-Note

#10045 *: use Go 1.11 for tests
  .travis.yml
  Makefile
  clientv3/integration/lease_test.go
  clientv3/lease.go
  etcdserver/api/v2http/client.go
  etcdserver/config_test.go
  functional/agent/server.go
  integration/cluster.go
  pkg/testutil/leak.go
  proxy/httpproxy/reverse_test.go
Labels: Release-Note

#10043 Automated cherry pick of #9997
  rafthttp/http.go
  rafthttp/metrics.go
  rafthttp/snapshot_sender.go
  snap/db.go
  snap/metrics.go
Labels: Release-Backport/v3.1
