Repository etcd-io/etcd, pull requests merged in 2018-07, with the labels that each got.

#9916 Documentation/upgrades: update upgrade doc indexes
  Documentation/upgrades/upgrading-etcd.md
Labels: Release-Backport/v3.3

#9934 Eliminate direct use of the gRPC transport package
  functional/tester/stresser_key.go
  integration/v3_grpc_inflight_test.go
Labels: clientv3

#9944 Automated cherry pick of #9761
  etcdserver/metrics.go
  etcdserver/raft.go
  etcdserver/util.go
  mvcc/backend/backend.go
  mvcc/backend/batch_tx.go
  mvcc/backend/metrics.go
  mvcc/kvstore.go
  mvcc/metrics.go
Labels: Release-Note

#9952 clientv3: fix keepalive send interval when response queue is full
  clientv3/integration/lease_test.go
  clientv3/lease.go
Labels: Release-Backport/v3.1, Release-Backport/v3.2, Release-Backport/v3.3

#9957 etcdserver: add "etcd_server_go_version" metric
  etcdserver/metrics.go
Labels: Monitor/Alert

#9924 lease: Persist remainingTTL to prevent indefinite auto-renewal of long lived leases
  Documentation/dev-guide/api_reference_v3.md
  clientv3/snapshot/v3_snapshot.go
  etcdserver/apply.go
  etcdserver/config.go
  etcdserver/etcdserverpb/etcdserver.pb.go
  etcdserver/etcdserverpb/raft_internal.pb.go
  etcdserver/etcdserverpb/raft_internal.proto
  etcdserver/etcdserverpb/rpc.pb.go
  etcdserver/etcdserverpb/rpc.proto
  etcdserver/server.go
  integration/cluster.go
  integration/v3_lease_test.go
  lease/lease_queue.go
  lease/lease_queue_test.go
  lease/leasehttp/http_test.go
  lease/leasepb/lease.pb.go
  lease/leasepb/lease.proto
  lease/lessor.go
  lease/lessor_bench_test.go
  lease/lessor_test.go
  tools/etcd-dump-logs/main.go
Labels: Feature, Release-Note

#9950 docs: automate metrics list documentation
  Makefile
  docs/faq.rst
  docs/index.rst
  docs/metrics-latest
  docs/metrics-v3.1
  docs/metrics-v3.2
  docs/metrics-v3.3
  docs/operate.rst
  tools/etcd-dump-metrics/README
  tools/etcd-dump-metrics/main.go
Labels: Doc, Monitor/Alert

#8689 raft: don't allocate slice and sort on every commit
  raft/raft.go
Labels: Raft
