Repository etcd-io/etcd, pull requests merged in 2018-04, with the labels that each got.

#9418 lease: Add a heap to optimize lease expiration checks
  CHANGELOG-3.4.md
  lease/lease_queue.go
  lease/lessor.go
  lease/lessor_bench_test.go
Labels: Release-Note

#9549 etcdserver: handle proposal error when processing internal raft request
  CHANGELOG-3.4.md
  etcdserver/v3_server.go
Labels: Release-Note

#9557 etcdserver: fix "lease_expired_total" metrics
  etcdserver/server.go
Labels: Release-Backport/v3.2, Release-Backport/v3.3

#9564 functional: add membership reconfiguration tests
  functional.yaml
  functional/agent/handler.go
  functional/build
  functional/rpcpb/rpc.pb.go
  functional/rpcpb/rpc.proto
  functional/tester/cluster.go
  functional/tester/cluster_read_config.go
  functional/tester/cluster_test.go
  functional/tester/failure_case_sigquit_remove.go
  functional/tester/failure_case_sigterm.go
  test
Labels: Testing/functional-tester

#9570 *: fix TLS reload when cert includes only IPs (no domain names in SAN field)
  CHANGELOG-3.2.md
  CHANGELOG-3.3.md
  CHANGELOG-3.4.md
  Documentation/op-guide/security.md
  integration/cluster.go
  integration/fixtures-expired/ca.crt
  integration/fixtures-expired/gencerts.sh
  integration/fixtures-expired/server-ca-csr-ip.json
  integration/fixtures-expired/server-ip.crt
  integration/fixtures-expired/server-ip.key.insecure
  integration/fixtures-expired/server.crt
  integration/fixtures-expired/server.key.insecure
  integration/fixtures/ca.crt
  integration/fixtures/gencerts.sh
  integration/fixtures/revoke.crl
  integration/fixtures/server-ca-csr-ip.json
  integration/fixtures/server-ip.crt
  integration/fixtures/server-ip.key.insecure
  integration/fixtures/server-revoked.crt
  integration/fixtures/server-revoked.key.insecure
  integration/fixtures/server-wildcard.crt
  integration/fixtures/server-wildcard.key.insecure
  integration/fixtures/server.crt
  integration/fixtures/server.key.insecure
  integration/fixtures/server2.crt
  integration/fixtures/server2.key.insecure
  integration/v3_grpc_test.go
  pkg/transport/listener.go
Labels: Release-Backport/v3.2, Release-Backport/v3.3, TLS

#9587 etcdserver: add is_leader prometheus metric that is 1 on the leader.
  etcdserver/metrics.go
  etcdserver/raft.go
Labels: Release-Backport/v3.1, Release-Backport/v3.2, Release-Backport/v3.3

#9582 [WIP] scripts: Add script that performs entire release workflow
  scripts/build-release.sh
  scripts/release
Labels: Release-Backport/v3.1, Release-Backport/v3.2, Release-Backport/v3.3

#9626 etcdserver: Fix v2v3api set to create parent directly if not exists
  etcdserver/api/v2v3/store.go
  etcdserver/v2store/store_test.go
Labels: Release-Note

#9628 etcd-dump-logs: add entry-type flag to list entries of specific types…
  tools/etcd-dump-logs/etcd-dump-log_test.go
  tools/etcd-dump-logs/expectedoutput/listAll.output
  tools/etcd-dump-logs/expectedoutput/listConfigChange.output
  tools/etcd-dump-logs/expectedoutput/listConfigChangeIRRCompaction.output
  tools/etcd-dump-logs/expectedoutput/listConfigChangeIRRLeaseRevoke.output
  tools/etcd-dump-logs/expectedoutput/listIRRCompaction.output
  tools/etcd-dump-logs/expectedoutput/listIRRDeleteRange.output
  tools/etcd-dump-logs/expectedoutput/listIRRLeaseGrant.output
  tools/etcd-dump-logs/expectedoutput/listIRRLeaseRevoke.output
  tools/etcd-dump-logs/expectedoutput/listIRRPut.output
  tools/etcd-dump-logs/expectedoutput/listIRRRange.output
  tools/etcd-dump-logs/expectedoutput/listIRRTxn.output
  tools/etcd-dump-logs/expectedoutput/listInternalRaftRequest.output
  tools/etcd-dump-logs/expectedoutput/listNormal.output
  tools/etcd-dump-logs/expectedoutput/listRequest.output
  tools/etcd-dump-logs/main.go
Labels: Release-Note
