Repository etcd-io/etcd, pull requests merged in 2018-06, with the labels that each got.

#9807 ctlv3: support TLS endpoints for move-leader command
  etcdctl/ctlv3/command/global.go
  etcdctl/ctlv3/command/move_leader_command.go
  tests/e2e/ctl_v3_move_leader_test.go
Labels: Release-Backport/v3.3

#9822 etcdserver: Replace value contents with value_size in request took too long warning
  etcdserver/etcdserverpb/raft_internal_stringer.go
Labels: Release-Backport/v3.2

#9826 etcdserver: Add response byte size and range response count to took too long warning
  etcdserver/apply.go
  etcdserver/apply_v2.go
  etcdserver/util.go
  etcdserver/v3_server.go
Labels: Release-Backport/v3.2

#9834 backend: more metrics for bboltdb transaction
  CHANGELOG-3.4.md
  mvcc/backend/batch_tx.go
  mvcc/backend/metrics.go
Labels: Release-Note

#9887 raft: Really avoid scanning raft log in becomeLeader
  raft/raft.go
Labels: Performance, Raft

#9883 auth: Support all JWT algorithms
  CHANGELOG-3.4.md
  Documentation/op-guide/configuration.md
  auth/jwt.go
  auth/jwt_test.go
  auth/options.go
  auth/store.go
  integration/fixtures/gencerts.sh
  integration/fixtures/server-ca-csr-ecdsa.json
  integration/fixtures/server-ecdsa.crt
  integration/fixtures/server-ecdsa.key.insecure
Labels: Auth, Feature

#9869 *: Add progress notify request watch request
  Documentation/dev-guide/api_reference_v3.md
  Documentation/dev-guide/apispec/swagger/rpc.swagger.json
  Documentation/dev-guide/apispec/swagger/v3election.swagger.json
  Documentation/dev-guide/apispec/swagger/v3lock.swagger.json
  Documentation/dev-guide/interacting_v3.md
  clientv3/integration/watch_test.go
  clientv3/watch.go
  etcdctl/ctlv3/command/watch_command.go
  etcdserver/api/v3rpc/watch.go
  etcdserver/etcdserverpb/etcdserver.pb.go
  etcdserver/etcdserverpb/rpc.pb.go
  etcdserver/etcdserverpb/rpc.proto
Labels: Feature, Release-Note, clientv3
