Repository etcd-io/etcd, pull requests merged in 2018-05, with the labels that each got.

#9688 etcdctl/ctlv3: fix watch with exec commands, interactive mode flag parsing
  .gitignore
  Makefile
  etcdctl/ctlv3/command/watch_command.go
  etcdctl/ctlv3/command/watch_command_test.go
  tests/e2e/ctl_v3_watch_cov_test.go
  tests/e2e/ctl_v3_watch_no_cov_test.go
  tests/e2e/ctl_v3_watch_test.go
Labels: Release-Backport/v3.3

#9694 Cherry-picking PR 7967 to release-3.2
  etcdserver/server.go
Labels: Release-Note

#9693 Cherry-picking PR 7967 to release-3.1
  etcdserver/server.go
Labels: Release-Note

#9778 leases: Add metrics to etcd leases
  lease/lessor.go
  lease/metrics.go
Labels: Release-Note

#9775 mvcc: fix panic by allowing future revision watcher from restore operation
  integration/v3_watch_restore_test.go
  mvcc/watchable_store.go
  mvcc/watchable_store_test.go
  mvcc/watcher_group.go
Labels: Release-Backport/v3.1, Release-Backport/v3.2, Release-Backport/v3.3
