Repository etcd-io/etcd, pull requests merged in 2018-03, with the labels that each got.

#9372 *: mitigate DNS rebinding attacks in insecure etcd server
  CHANGELOG-3.4.md
  Documentation/op-guide/security.md
  embed/config.go
  embed/etcd.go
  embed/serve.go
  etcdmain/config.go
  etcdmain/help.go
  etcdserver/config.go
  etcdserver/server.go
  hack/scripts-dev/docker-dns/certs/run.sh
  hack/scripts-dev/docker-dns/insecure/Procfile
  hack/scripts-dev/docker-dns/insecure/run.sh
  pkg/httputil/httputil.go
  pkg/httputil/httputil_test.go
Labels: Release-Note/v3.4, Security

#9379 *: fix server panic on invalid Election Proclaim/Resign HTTP requests
  e2e/util.go
  e2e/v3_curl_test.go
  etcdserver/api/v3election/election.go
Labels: Release-Backport/v3.2, Release-Backport/v3.3, Release-Note/v3.4

#9382 pkg/flags: fatal on conflicting environment variable
  pkg/flags/flag.go
  pkg/flags/flag_test.go
Labels: Release-Note/v3.4

#9352 *: configure Raft Pre-Vote to reduce disruptive rejoining servers
  embed/config.go
  embed/etcd.go
  etcdmain/config.go
  etcdmain/help.go
  etcdserver/config.go
  etcdserver/raft.go
  etcdserver/server.go
  raft/raft.go
  raft/raft_test.go
Labels: Raft, Release-Note/v3.4

#9399 *: enforce max lease TTL with 9,000,000,000 seconds
  CHANGELOG-3.2.md
  CHANGELOG-3.3.md
  CHANGELOG-3.4.md
  clientv3/integration/lease_test.go
  clientv3/options.go
  etcdserver/api/v3rpc/rpctypes/error.go
  etcdserver/api/v3rpc/util.go
  lease/lessor.go
  lease/lessor_test.go
Labels: Release-Backport/v3.2, Release-Backport/v3.3, Release-Note/v3.4

#9415 etcdserver: adjust election timeout on restart
  etcdserver/raft.go
  etcdserver/server.go
  etcdserver/util_test.go
  rafthttp/transport.go
Labels: Release-Backport/v3.1, Release-Backport/v3.2, Release-Backport/v3.3, Release-Note

#9437 rafthttp: add missing "peer_sent_failures_total" metrics call
  rafthttp/peer.go
  rafthttp/remote.go
Labels: Release-Backport/v3.2, Release-Backport/v3.3

#9433 *: unify type of key and rangeEnd in AuthRoleRevokePermissionRequest
  Documentation/dev-guide/api_reference_v3.md
  Documentation/dev-guide/apispec/swagger/rpc.swagger.json
  auth/store_test.go
  clientv3/auth.go
  etcdserver/etcdserverpb/rpc.pb.go
  etcdserver/etcdserverpb/rpc.proto
Labels: Release-Note

#9466 Change baseimage for ppc64le dockerfile
  Dockerfile-release.ppc64le
Labels: Release-Note

#9476 compactor: clean up
  compactor/compactor.go
  compactor/periodic.go
  compactor/periodic_test.go
  compactor/revision.go
  compactor/revision_test.go
Labels: Release-Backport/v3.3

#9485 compactor: adjust interval for period <1-hour
  compactor/periodic.go
  compactor/periodic_test.go
Labels: Release-Backport/v3.3
