Repository etcd-io/etcd, pull requests merged in 2019-10, with the labels that each got.

#11194 etcdctl: fix member add command
  etcdctl/ctlv3/command/member_command.go
Labels: Release-Backport/v3.3, Release-Backport/v3.4

#11184 clientv3: Set authority used in cert checks to host of endpoint
  .words
  clientv3/balancer/resolver/endpoint/endpoint.go
  clientv3/client.go
  clientv3/credentials/credentials.go
Labels: Release-Backport/v3.4, area/clientv3

#11179 Add tracing to range request in etcd server.
  clientv3/snapshot/v3_snapshot.go
  etcdserver/apply.go
  etcdserver/apply_auth.go
  etcdserver/corrupt.go
  etcdserver/server.go
  etcdserver/v3_server.go
  integration/v3_alarm_test.go
  mvcc/kv.go
  mvcc/kv_test.go
  mvcc/kv_view.go
  mvcc/kvstore.go
  mvcc/kvstore_bench_test.go
  mvcc/kvstore_compaction_test.go
  mvcc/kvstore_test.go
  mvcc/kvstore_txn.go
  mvcc/watchable_store.go
  mvcc/watchable_store_bench_test.go
  mvcc/watchable_store_test.go
  mvcc/watchable_store_txn.go
  pkg/traceutil/trace.go
  pkg/traceutil/trace_test.go
  tools/benchmark/cmd/mvcc-put.go
Labels: Release-Backport/v3.4, area/feature

#11211 Replace endpoint.ParseHostPort with net.SplitHostPort to fix IPv6 client endpoints
  clientv3/balancer/resolver/endpoint/endpoint.go
  clientv3/client.go
  integration/fixtures/ca.crt
  integration/fixtures/gencerts.sh
  integration/fixtures/revoke.crl
  integration/fixtures/server-ca-csr-ipv6.json
  integration/fixtures/server-ecdsa.crt
  integration/fixtures/server-ecdsa.key.insecure
  integration/fixtures/server-ip.crt
  integration/fixtures/server-ip.key.insecure
  integration/fixtures/server-ipv6.crt
  integration/fixtures/server-ipv6.key.insecure
  integration/fixtures/server-revoked.crt
  integration/fixtures/server-revoked.key.insecure
  integration/fixtures/server-wildcard.crt
  integration/fixtures/server-wildcard.key.insecure
  integration/fixtures/server.crt
  integration/fixtures/server.key.insecure
  integration/fixtures/server2.crt
  integration/fixtures/server2.key.insecure
  integration/fixtures/server3.crt
  integration/fixtures/server3.key.insecure
Labels: Release-Backport/v3.4, area/bug

#11233 etcdserver: unset old cluster version in metrics
  etcdserver/api/membership/cluster.go
Labels: Release-Backport/v3.4

#11254 etcdserver: strip patch version in cluster version metrics
  etcdserver/api/membership/cluster.go
  tests/e2e/metrics_test.go
Labels: Release-Note

#11255 Automated cherry pick of #11233 #11254 on release 3.4
  etcdserver/api/membership/cluster.go
  tests/e2e/metrics_test.go
Labels: Release-Note

#11265 etcdserver: strip patch version in metrics
  etcdserver/server.go
Labels: Release-Backport/v3.4

#11262 *: promote the boltdb-freelistType from experimental to official
  Documentation/op-guide/configuration.md
  embed/config.go
  embed/etcd.go
  etcdmain/config.go
  etcdmain/help.go
Labels: Release-Note

#11308 etcdserver: wait purge file loop to finish during shutdown
  etcdserver/server.go
  pkg/fileutil/purge.go
  pkg/fileutil/purge_test.go
Labels: area/bug

#11313 clientv3: fix retry/streamer error message
  clientv3/retry_interceptor.go
Labels: Release-Backport/v3.4
