Repository etcd-io/etcd, pull requests merged in 2019-09, with the labels that each got.

#11108 embed: fix secure server logging message
  embed/serve.go
Labels: Release-Backport/v3.4

#11140 vendor: upgrade to gRPC v1.23.1
  go.mod
  go.sum
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/version.go
Labels: Release-Note

#11157 etcdctl/ctlv3: do not modify db file on "restore"
  e2e/ctl_v3_snapshot_test.go
  etcdctl/ctlv3/command/snapshot_command.go
Labels: Release-Note, area/bug

#11175 *: create project governance
  CHANGELOG-3.5.md
  GOVERNANCE.md
  MAINTAINERS
  MAINTAINERS_RULES.md
  OWNERS
Labels: Release-Note
