Repository etcd-io/etcd, pull requests merged in 2020-02, with the labels that each got.

#11623 Automated cherry pick of #11613 to release-3.3
  mvcc/backend/backend.go
  snap/snapshotter.go
Labels: Release-Backport/v3.3

#11622 Automated cherry pick of #11613 to release-3.4
  etcdserver/api/snap/snapshotter.go
  mvcc/backend/backend.go
Labels: Release-Backport/v3.4

#11046 raft: fix auto-transitioning out of joint config
  raft/node.go
  raft/raft.go
  raft/raft_test.go
  raft/raftpb/confchange.go
  raft/rafttest/interaction_env_handler_deliver_msgs.go
  raft/rawnode.go
  raft/rawnode_test.go
  raft/testdata/confchange_v2_add_double_auto.txt
  raft/testdata/confchange_v2_add_single_auto.txt
Labels: area/raft
