Repository etcd-io/etcd, pull requests merged in 2020-07, with the labels that each got.

#11943 auth, etcdserver: hash password in the API layer
  CHANGELOG-3.5.md
  Documentation/dev-guide/api_reference_v3.md
  Documentation/dev-guide/apispec/swagger/rpc.swagger.json
  Documentation/dev-guide/apispec/swagger/v3election.swagger.json
  Documentation/dev-guide/apispec/swagger/v3lock.swagger.json
  Documentation/upgrades/upgrade_3_5.md
  auth/store.go
  auth/store_test.go
  etcdserver/etcdserverpb/rpc.pb.go
  etcdserver/etcdserverpb/rpc.proto
  etcdserver/v3_server.go
Labels: area/feature

#12129 12126: snapshot: corrupted in Embedded server
  etcdserver/api/v3rpc/maintenance.go
Labels: area/bug

#11802 Documentation/learning/lock/client: add defer Unlock
  Documentation/learning/lock/client/client.go
Labels: stale

#12170 rename the filename pkg/adt/doc.go to be consistent with the package name
  pkg/adt/adt.go
Labels: area/doc

#12179 rafthttp: fix streamHandle outgoingConn peerID
  etcdserver/api/rafthttp/http.go
Labels: area/bug
