Repository etcd-io/etcd, pull requests merged in 2021-05, with the labels that each got.

#12896 server: make applier use ReadTx() in Txn() instead of ConcurrentReadTx()
  server/config/config.go
  server/embed/config.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/help.go
  server/etcdserver/apply.go
  server/mvcc/kv.go
  server/mvcc/kv_test.go
  server/mvcc/kv_view.go
  server/mvcc/kvstore_test.go
  server/mvcc/kvstore_txn.go
Labels: area/performance

#12774 server: add support for log rotation
  CHANGELOG-3.5.md
  bill-of-materials.json
  etcdctl/go.sum
  go.sum
  server/embed/config.go
  server/embed/config_logging.go
  server/embed/config_test.go
  server/etcdmain/config.go
  server/etcdmain/help.go
  server/go.mod
  server/go.sum
  tests/go.sum
Labels: rel/3.5-nice-to-have

#12986 Reset 'seq' flags between transactions and track per 'bucket'
  server/mvcc/backend/backend.go
  server/mvcc/backend/batch_tx.go
  server/mvcc/backend/tx_buffer.go
Labels: area/performance

#12989 github/workflow: run arm64 tests for all branches startin from 3.5
  .github/workflows/self-hosted-linux-arm64-graviton2-tests.yml
Labels: Release-Backport/v3.5

#12587 backend: fix buffer range bug
  server/mvcc/backend/tx_buffer.go
Labels: area/bug, rel/3.5-nice-to-have

#12933 server: set multiple concurrentReadTx instances share one txReadBuffer
  server/mvcc/backend/backend.go
  server/mvcc/backend/tx_buffer.go
Labels: Release-Backport/v3.5, area/performance, rel/3.5-nice-to-have

#13043 backport-3.5: Expose clientv3.CreateDefaultZapLoggerConfig
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/pkg/logutil/zap_grpc.go
  client/pkg/logutil/zap_grpc_test.go
  client/v2/go.sum
  client/v3/client.go
  client/v3/logger.go
  etcdctl/go.sum
  etcdutl/go.sum
  go.sum
  raft/go.sum
  server/etcdmain/grpc_proxy.go
  server/go.sum
  tests/go.sum
Labels: Release-Backport/v3.5
