Repository etcd-io/etcd, pull requests merged in 2022-12, with the labels that each got.

#14884 [3.5] Backport: non mutating requests pass through quotaKVServer when NOSPACE
  server/etcdserver/quota.go
  tests/integration/v3_alarm_test.go
Labels: stage/merge-when-tests-green

#14898 changelog: added non mutating requests pass through quotaKVServer when NOSPACE in 3.7
  CHANGELOG/CHANGELOG-3.5.md
Labels: stage/merge-when-tests-green

#14972 dependabot: change schedule interval to weekly
  .github/dependabot.yml
Labels: dependencies

#14973 deps: bump some dependencies suggested by dependabot
  api/go.mod
  api/go.sum
  bill-of-materials.json
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: dependencies

#15006 Add trivy nightly scan for `release-3.5`
  .github/workflows/trivy-nightly-scan.yaml
Labels: area/security, stage/merge-when-tests-green

#15007 Add trivy nightly scan for `release-3.4`
  .github/workflows/trivy-nightly-scan.yaml
Labels: area/security, stage/merge-when-tests-green

#14999 e2e: deflake TestCtlV3AuthGracefulDisable
  tests/framework/e2e/cluster_proxy.go
Labels: stage/merge-when-tests-green

#15016 [3.5] Security: use distroless base image to address critical Vulnerabilities
  Dockerfile-release.amd64
  Dockerfile-release.arm64
  Dockerfile-release.ppc64le
  Dockerfile-release.s390x
Labels: area/security, priority/important

#15017 [3.4] Security: use distroless base image to address critical Vulnerabilities
  Dockerfile-release
  Dockerfile-release.arm64
  Dockerfile-release.ppc64le
Labels: area/security, priority/important

#15018 [3.5] Security: address HIGH Vulnerabilities
  .github/workflows/e2e.yaml
  .github/workflows/functional.yaml
  .github/workflows/grpcproxy.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  .travis.yml
  Makefile
  api/go.mod
  bill-of-materials.json
  build.sh
  client/pkg/go.mod
  client/v2/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  raft/go.mod
  scripts/test_lib.sh
  server/go.mod
  server/go.sum
  test.sh
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
Labels: area/security, priority/important

#15019 [3.4] Security: address HIGH Vulnerabilities
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  clientv3/integration/black_hole_test.go
  clientv3/integration/network_partition_test.go
  clientv3/integration/watch_fragment_test.go
  embed/config_logging_journal_unix.go
  embed/config_logging_journal_windows.go
  etcdctl/ctlv2/ctl_cov.go
  etcdctl/ctlv2/ctl_nocov.go
  etcdctl/ctlv3/ctl_cov.go
  etcdctl/ctlv3/ctl_nocov.go
  etcdserver/api/v2store/store_v2_test.go
  etcdserver/api/v2store/store_v2v3_test.go
  go.mod
  go.sum
  integration/cluster_direct.go
  integration/cluster_proxy.go
  integration/embed_test.go
  mvcc/backend/config_default.go
  mvcc/backend/config_windows.go
  pkg/fileutil/dir_unix.go
  pkg/fileutil/dir_windows.go
  pkg/fileutil/lock_flock.go
  pkg/fileutil/lock_linux.go
  pkg/fileutil/lock_linux_test.go
  pkg/fileutil/lock_solaris.go
  pkg/fileutil/lock_unix.go
  pkg/fileutil/lock_windows.go
  pkg/fileutil/preallocate_darwin.go
  pkg/fileutil/preallocate_unix.go
  pkg/fileutil/preallocate_unsupported.go
  pkg/fileutil/sync.go
  pkg/fileutil/sync_darwin.go
  pkg/fileutil/sync_linux.go
  pkg/logutil/zap_journal.go
  pkg/logutil/zap_journal_test.go
  pkg/netutil/routes.go
  pkg/netutil/routes_linux.go
  pkg/netutil/routes_linux_test.go
  pkg/osutil/interrupt_unix.go
  pkg/osutil/interrupt_windows.go
  pkg/osutil/signal.go
  pkg/osutil/signal_linux.go
  pkg/runtime/fds_other.go
  test
  tests/e2e/cluster_direct_test.go
  tests/e2e/cluster_proxy_test.go
  tests/e2e/ctl_v3_watch_cov_test.go
  tests/e2e/ctl_v3_watch_no_cov_test.go
  tests/e2e/etcd_spawn_cov.go
  tests/e2e/etcd_spawn_nocov.go
  tests/e2e/v2_test.go
  tests/e2e/v2v3_test.go
  tests/e2e/v3_cipher_suite_test.go
  tools/etcd-dump-metrics/install_darwin.go
  tools/etcd-dump-metrics/install_linux.go
  tools/etcd-dump-metrics/install_windows.go
Labels: area/security, priority/important

#15031 clientv3: add protection code to prevent SnapshotWithVersion from panicking
  client/v3/maintenance.go
  client/v3/snapshot/v3_snapshot.go
Labels: area/clientv3, backport/v3.4, backport/v3.5

#15040 Update nsswitch.conf file
  nsswitch.conf
Labels: backport/v3.4, backport/v3.5
