Repository etcd-io/etcd, pull requests merged in 2022-04, with the labels that each got.

#13868 tests/common/lease: Wait for correct lease list response
  tests/common/lease_test.go
Labels: stage/merge-when-tests-green

#13880 etcd-dump-logs will panic if there is no WAL entry after the snapshot
  tools/etcd-dump-logs/main.go
Labels: stage/merge-when-tests-green

#13854 Fix the data inconsistency issue by moving the SetConsistentIndex into the transaction lock
  etcdutl/etcdutl/backup_command.go
  etcdutl/etcdutl/migrate_command.go
  server/auth/range_perm_cache.go
  server/auth/store.go
  server/auth/store_mock_test.go
  server/etcdserver/adapters.go
  server/etcdserver/bootstrap.go
  server/etcdserver/cindex/cindex.go
  server/etcdserver/server.go
  server/etcdserver/server_test.go
  server/lease/lessor.go
  server/storage/backend.go
  server/storage/backend/backend.go
  server/storage/backend/batch_tx.go
  server/storage/backend/hooks_test.go
  server/storage/backend/verify.go
  server/storage/backend/verify_test.go
  server/storage/mvcc/kvstore.go
  server/storage/mvcc/kvstore_compaction.go
  server/storage/mvcc/kvstore_test.go
  server/storage/mvcc/kvstore_txn.go
  server/storage/mvcc/store.go
  server/storage/schema/alarm.go
  server/storage/schema/auth.go
  server/storage/schema/auth_roles.go
  server/storage/schema/auth_users.go
  server/storage/schema/cindex.go
  server/storage/schema/membership.go
  server/storage/schema/migration.go
  server/storage/schema/schema.go
  server/storage/schema/schema_test.go
  server/verify/verify.go
Labels: important

#13898 tools/mod: Update tools
  tools/mod/go.mod
  tools/mod/go.sum
  tools/mod/tools.go
Labels: stage/merge-when-tests-green

#13910 *: update golang.org/x/crypto
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
Labels: stage/merge-when-tests-green

#13930 Set backend to cindex before recovering the lessor in applySnapshot
  server/etcdserver/server.go
Labels: backport/v3.5

#13933 [3.5]Set backend to cindex before recovering the lessor in applySnapshot
  server/etcdserver/server.go
Labels: stage/merge-when-tests-green

#13923 cv3/mirror: Fetch the most recent revision from the prefix
  client/v3/mirror/syncer.go
  tests/integration/clientv3/mirror_auth_test.go
Labels: stage/merge-when-tests-green

#13938 [backport] PR 13923 to release-3.5
  client/v3/mirror/syncer.go
  tests/integration/clientv3/mirror_auth_test.go
Labels: stage/merge-when-tests-green

#13929 contrib/raftexample: Save snapshot and WAL before hard state
  contrib/raftexample/raft.go
Labels: stage/merge-when-tests-green

#13888 go.mod: upgrade opentelemetry deps
  api/go.mod
  api/go.sum
  bill-of-materials.json
  client/pkg/testutil/leak.go
  client/v2/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  raft/go.mod
  raft/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
Labels: stage/merge-when-tests-green

#13950 Revert #13714
  client/pkg/srv/srv.go
  client/pkg/srv/srv_test.go
Labels: backport/v3.5, stage/merge-when-tests-green

#13942 Update consitent_index when applying fails
  server/etcdserver/server.go
  tests/integration/v3_auth_test.go
Labels: backport/v3.5

#13981 scripts: Add tests for release scripts
  .github/workflows/release.yaml
  scripts/release.sh
Labels: stage/merge-when-tests-green

#13966 Fixed potential goroutine leak due to p.Ready() receive in pkg/proxy and dependents.
  pkg/proxy/server_test.go
  tests/functional/cmd/etcd-proxy/main.go
Labels: stage/merge-when-tests-green
