Repository etcd-io/etcd, pull requests merged in 2022-10, with the labels that each got.

#14549 update changelogs of 3.4 and 3.5 for handling auth invalid token and old revision errors in watch
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: stage/merge-when-tests-green

#14562 *: avoid closing a watch with ID 0 incorrectly
  clientv3/watch.go
  etcdserver/api/v3rpc/watch.go
  integration/v3_auth_test.go
  integration/v3_watch_test.go
  mvcc/watcher.go
  proxy/grpcproxy/watch.go
Labels: stage/merge-when-tests-green

#13861 [Release-3.5] Makefile: additional logic fix / Update Ubuntu base
  Makefile
  tests/Dockerfile
Labels: backport/v3.4, stage/tracked

#14581 [3.4] client/v3: Add backoff before retry when watch stream returns unavailable
  clientv3/watch.go
Labels: stage/merge-when-tests-green

#14591 Tests: Check Watch response error not nil to avoid runtime panic.
  tests/integration/clientv3/watch_test.go
Labels: backport/v3.4, backport/v3.5, stage/merge-when-tests-green

#14607 [e2e] Fix bug in EtcdctlV3.HashKV() e2e implementation.
  tests/framework/e2e/etcdctl.go
Labels: stage/merge-when-tests-green

#14600 lessor: simplify expireExists to make it more clear
  server/lease/lease_queue_test.go
  server/lease/lessor.go
Labels: stage/merge-when-tests-green

#14608 [e2e] Fix AuthEnable/Disable e2e test implementations
  tests/framework/e2e/etcdctl.go
Labels: stage/merge-when-tests-green

#14398 Validate etcd linearizability
  .github/workflows/linearizability.yaml
  Makefile
  bill-of-materials.json
  pkg/expect/expect.go
  scripts/test.sh
  tests/framework/e2e.go
  tests/framework/e2e/cluster_proxy.go
  tests/framework/e2e/etcd_process.go
  tests/framework/interface.go
  tests/go.mod
  tests/go.sum
  tests/linearizability/client.go
  tests/linearizability/failpoints.go
  tests/linearizability/linearizability_test.go
  tests/linearizability/main_test.go
  tests/linearizability/model.go
  tests/linearizability/model_test.go
  tests/linearizability/traffic.go
Labels: priority/important, stage/merge-when-tests-green

#14613 fix: add a warning message on startup if the server name is default
  server/embed/config.go
Labels: stage/merge-when-tests-green

#14635 fix: close conn
  client/v3/maintenance.go
Labels: backport/v3.4, backport/v3.5

#14637 [e2e] don't pass --endpoints flag in test HashKV implementation
  tests/framework/e2e/etcdctl.go
Labels: stage/merge-when-tests-green

#14574 etcdserver: call refreshRangePermCache on Recover() in AuthStore.
  server/auth/range_perm_cache.go
  server/auth/store.go
  tests/e2e/ctl_v3_auth_cluster_test.go
  tests/framework/e2e/cluster.go
  tests/framework/e2e/etcdctl.go
Labels: backport/v3.4, backport/v3.5

#14639 *: bump to go1.19.2 from 1.19.1
  .github/workflows/build.yaml
  .github/workflows/contrib.yaml
  .github/workflows/coverage.yaml
  .github/workflows/e2e.yaml
  .github/workflows/functional.yaml
  .github/workflows/fuzzing.yaml
  .github/workflows/grpcproxy.yaml
  .github/workflows/linearizability.yaml
  .github/workflows/release.yaml
  .github/workflows/static-analysis.yaml
  .github/workflows/tests.yaml
  tests/functional/Dockerfile
  tests/manual/Makefile
Labels: stage/merge-when-tests-green

#14649 [3.4] server: add a unit test case for authStore.Reocver() with empty rangePermCache
  auth/store.go
  auth/store_test.go
Labels: stage/merge-when-tests-green

#14648 [3.5] server: refresh auth info when etcd recovers from a snapshot
  server/auth/store.go
  server/auth/store_test.go
Labels: stage/merge-when-tests-green

#14621 test: terminate functional test on failure and code cleanup
  tests/functional/tester/cluster_run.go
Labels: area/functional-testing

#14662 [3.5] fix: close maintenance conn
  client/v3/maintenance.go
Labels: stage/merge-when-tests-green
