Repository etcd-io/etcd, pull requests merged in 2022-07, with the labels that each got.

#14179 [backport 3.4] Update golang.org/x/crypto to latest
  go.mod
  go.sum
Labels: area/security

#14169 Support configuring `MaxConcurrentStreams` for http2
  pkg/flags/uint32.go
  pkg/flags/uint32_test.go
  server/config/config.go
  server/embed/config.go
  server/embed/etcd.go
  server/embed/serve.go
  server/etcdmain/config.go
  server/etcdmain/grpc_proxy.go
  server/etcdmain/help.go
  server/etcdserver/api/v3rpc/grpc.go
  tests/e2e/ctl_v3_test.go
  tests/e2e/v3_curl_maxstream_test.go
  tests/framework/e2e/cluster.go
Labels: backport/v3.5

#14203 clientv3: Fix parsing of ETCD_CLIENT_DEBUG
  client/v3/logger.go
Labels: backport/v3.5

#14236 [release-3.4] clientv3: filter learners members during autosync
  clientv3/client.go
  clientv3/client_test.go
Labels: stage/merge-when-tests-green

#14240 [3.4] etcdserver: add more detailed traces on linearized reading
  etcdserver/v3_server.go
  pkg/traceutil/trace.go
Labels: stage/merge-when-tests-green

#14235 delete unreachable code
  raft/raft_test.go
Labels: stage/merge-when-tests-green

#14246 [3.4] etcdserver,pkg: remove temp files in snap dir when etcdserver starting
  etcdserver/server.go
  pkg/fileutil/fileutil.go
  pkg/fileutil/fileutil_test.go
Labels: stage/merge-when-tests-green

#14231 update changelog-3.4 to protection for rangePermCache with a RW lock
  CHANGELOG/CHANGELOG-3.4.md
Labels: stage/merge-when-tests-green

#14279 [3.4] clientv3/mvcc: fixed DATA RACE
  go.mod
  mvcc/kvstore.go
Labels: stage/merge-when-tests-green

#14278 tests: Migrate member list tests to common framework
  tests/common/member_test.go
  tests/e2e/ctl_v3_member_test.go
  tests/framework/integration.go
  tests/framework/interface.go
Labels: stage/merge-when-tests-green

#14280 fix: code cleanup
  server/auth/simple_token.go
  server/auth/store_test.go
  server/embed/serve.go
Labels: stage/merge-when-tests-green
