Repository etcd-io/etcd, pull requests merged in 2023-05, with the labels that each got.

#15813 keep going with other test suite runs when failure with one
  scripts/test.sh
Labels: stage/merge-when-tests-green

#15821 Updated go to latest patch release 1.19.9
  .github/workflows/go-version.yaml
Labels: backport/v3.4, backport/v3.5

#15842 log time when open backend db took too long
  server/storage/backend.go
Labels: stage/merge-when-tests-green

#15860 [release-3.5] Move go version to dedicated .go-version file
  .github/workflows/go-version.yaml
  .go-version
  scripts/release
Labels: backport/v3.5

#15861 [release-3.4] Move go version to dedicated .go-version file
  .github/workflows/go-version.yaml
  .go-version
  scripts/release.sh
Labels: backport/v3.4

#15835 grpcproxy: fix memberlist results not update when proxy node down
  server/proxy/grpcproxy/cluster.go
  tests/integration/proxy/grpcproxy/cluster_test.go
Labels: backport/v3.4, backport/v3.5

#15938 Add example format for initial-cluster in configuration file
  etcd.conf.yml.sample
Labels: stage/merge-when-tests-green

#15950 [2023-05-25] Bump dependencies identified by dependabot
  api/go.mod
  api/go.sum
  client/internal/v2/go.mod
  client/internal/v2/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.sum
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: stage/merge-when-tests-green
