Repository etcd-io/etcd, pull requests merged in 2023-03, with the labels that each got.

#15398 rafthttp: replace inline code with existing function
  server/etcdserver/api/rafthttp/pipeline.go
  server/etcdserver/api/rafthttp/transport.go
Labels: stage/merge-when-tests-green

#15405 CHANGELOG: Add entries for 3.4 and 3.5 go version 1.19.
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: stage/merge-when-tests-green

#15201 pkg/schedule: correct comparison for FIFO schedule test
  pkg/schedule/schedule_test.go
Labels: stage/merge-when-tests-green

#15427 Updated go to latest 1.19.7 release
  .github/workflows/build.yaml
  .github/workflows/contrib.yaml
  .github/workflows/coverage.yaml
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e.yaml
  .github/workflows/fuzzing.yaml
  .github/workflows/govuln.yaml
  .github/workflows/grpcproxy.yaml
  .github/workflows/release.yaml
  .github/workflows/robustness-template.yaml
  .github/workflows/static-analysis.yaml
  .github/workflows/tests-arm64.yaml
  .github/workflows/tests.yaml
  tests/manual/Makefile
Labels: backport/v3.4, backport/v3.5

#15431 Watch random scheduler
  pkg/stringutil/rand.go
  server/embed/serve.go
  tests/e2e/watch_delay_test.go
Labels: backport/v3.4, backport/v3.5

#15447 FIX #13389
  server/embed/serve.go
Labels: backport/v3.4, backport/v3.5

#15473 Refactor: Use proper variable names for urls
  server/etcdmain/config_test.go
Labels: stage/merge-when-tests-green

#15479 Test connection multiplexing.
  bill-of-materials.json
  tests/e2e/cluster_downgrade_test.go
  tests/e2e/cmux_test.go
  tests/e2e/metrics_test.go
  tests/e2e/utils.go
  tests/e2e/v3_cipher_suite_test.go
  tests/e2e/v3_curl_maxstream_test.go
  tests/e2e/v3_curl_test.go
  tests/e2e/watch_delay_test.go
  tests/framework/e2e/curl.go
  tests/go.mod
Labels: backport/v3.4, backport/v3.5

#15502 deflake member_test: enable pre-vote by default and add retry
  tests/common/member_test.go
  tests/framework/integration/cluster.go
Labels: stage/merge-when-tests-green

#15509 server/embed: fix data race when start insecure grpc
  server/embed/serve.go
  tests/e2e/cmux_test.go
Labels: backport/v3.4, backport/v3.5

#15546 CHANGELOG: add 'server/embed: fix data race when starting both secure & insecure gRPC servers on the same address' into 3.4/3.5
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: stage/merge-when-tests-green

#15446 Allow user to separate http and grpc server
  server/embed/config.go
  server/embed/etcd.go
  server/embed/serve.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
  tests/e2e/cmux_test.go
  tests/e2e/utils.go
  tests/e2e/watch_delay_test.go
  tests/framework/e2e/cluster.go
  tests/framework/e2e/cluster_proxy.go
  tests/framework/e2e/etcd_process.go
Labels: release/v3.5, release/v3.4

#15270 Fixes: #15266 All docker images of Architecture show amd64
  scripts/build-docker.sh
  scripts/test_images.sh
Labels: backport/v3.4, backport/v3.5
