Repository etcd-io/etcd, pull requests merged in 2023-12, with the labels that each got.

#17066 server: disable redirects in peer communication
  server/etcdserver/cluster_util.go
  server/etcdserver/corrupt.go
  server/lease/leasehttp/http.go
Labels: ok-to-test

#17070 Backport disable redirects in peer communication to release-3.5
  server/etcdserver/cluster_util.go
  server/etcdserver/corrupt.go
  server/lease/leasehttp/http.go
Labels: ok-to-test

#17072 Bump dependencies manually
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: ok-to-test

#17078 server: ignore raft messages if member id mismatch
  server/etcdserver/server.go
  server/etcdserver/server_test.go
Labels: backport/v3.4, backport/v3.5, needs-ok-to-test

#17080 Update release-3.4 and 3.5 Changelog for go bump to 1.20.12
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test

#17047 Adding automated install of Protoc if not found on the system
  scripts/genproto.sh
Labels: ok-to-test

#17089 Adjusted RAM Requirements for arm64 Workflows
  .github/workflows/e2e-arm64.yaml
  .github/workflows/robustness-nightly.yaml
  .github/workflows/robustness.yaml
  .github/workflows/tests.yaml
Labels: ok-to-test

#17079 Add member replace e2e test
  tests/e2e/corrupt_test.go
  tests/e2e/ctl_v3_member_no_proxy_test.go
  tests/e2e/utils.go
Labels: needs-ok-to-test

#17108 contrib: add missing lock and mixin readme descriptions
  contrib/README.md
Labels: ok-to-test

#17112 [3.4] Backport disable redirects in peer communication
  etcdserver/cluster_util.go
  etcdserver/corrupt.go
  lease/leasehttp/http.go
Labels: ok-to-test

#17117 etcdclient: Fix memory leak caused by for + time.After
  client/v3/lease.go
Labels: needs-ok-to-test

#17115 changelog: update 3.4 changelog to include ssrf fix
  CHANGELOG/CHANGELOG-3.4.md
Labels: ok-to-test

#17107 testutils: return early instead of first breaking in LogObserver.Expe…
  tests/framework/testutils/log_observer.go
Labels: ok-to-test

#16822 Ignore old leader's leases revoking request
  server/etcdserver/server.go
  server/etcdserver/v3_server.go
  server/lease/lessor.go
  server/lease/lessor_test.go
  tests/e2e/v3_lease_no_proxy_test.go
  tests/integration/v3_lease_test.go
Labels: backport/v3.4, backport/v3.5

#16888 tests: add comments for clientv3test.TestWatchResumeInitRev
  tests/integration/clientv3/watch_test.go
Labels: ok-to-test

#17131 Remove workflow telemetry github action
  .github/workflows/e2e-arm64.yaml
  .github/workflows/robustness-template.yaml
  .github/workflows/tests-template.yaml
Labels: area/testing, type/cleanup

#17149 Correct typo from 'Kuberntes' to 'Kubernetes'
  tests/robustness/traffic/kubernetes.go
Labels: ok-to-test

#17122 Add digest for base image and configure dependabot
  .github/dependabot.yml
  Dockerfile
Labels: ok-to-test

#17159 Manually bump dependencies
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: needs-ok-to-test

#17172 Manually bump dependencies
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: stage/merge-when-tests-green, needs-ok-to-test

#17106 Replace the deprecated `x509.ParseCRL` with `x509.ParseRevocationList`
  client/pkg/transport/listener.go
  client/pkg/transport/listener_test.go
  client/pkg/transport/listener_tls.go
Labels: ok-to-test
