Repository etcd-io/etcd, pull requests merged in 2023-11, with the labels that each got.

#16859 Add robustness failpoint for IO stall in raft loop
  tests/framework/e2e/etcd_process.go
  tests/robustness/failpoint/failpoint.go
  tests/robustness/failpoint/gofail.go
Labels: stage/merge-when-tests-green

#16882 etcdctl,etcdutl,server,tests: update golang.org/x/time to v0.4.0
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
Labels: stage/merge-when-tests-green

#16884 etcd-io tests: trial arm64 on every pr with a small robustness workflow
  .github/workflows/robustness.yaml
Labels: stage/merge-when-tests-green

#16883 scripts: macOS support for scripts/genproto.sh
  scripts/genproto.sh
Labels: stage/merge-when-tests-green

#16946 [3.5] CVE-2023-47108: Backport go.opentelemetry.io/otel@v1.20.0 and go.open…
  api/go.mod
  api/go.sum
  bill-of-materials.json
  client/pkg/go.mod
  client/pkg/go.sum
  client/v2/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
Labels: stage/merge-when-tests-green, needs-ok-to-test

#16952 Manually bump dependencies raised by dependabot
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: needs-ok-to-test

#16953 changelog: Update fix for CVE-2023-47108
  CHANGELOG/CHANGELOG-3.5.md
Labels: needs-ok-to-test

#16994 Add tests for setting cluster version using v2 request
  server/etcdserver/server_test.go
Labels: stage/merge-when-tests-green

#17005 fix missing json flag when using VERBOSE=1
  scripts/test_lib.sh
Labels: stage/merge-when-tests-green, ok-to-test

#17007 Remove v2 applier
  server/etcdserver/apply_v2.go
  server/etcdserver/server.go
  server/etcdserver/server_test.go
Labels: stage/merge-when-tests-green

#16950 etcd-e2d-test:rename e2e-arm64 file and runs it on every pull request…
  .github/workflows/e2e-arm64-nightly.yaml
  .github/workflows/e2e-arm64.yaml
Labels: ok-to-test

#17018 add initialization for epMu in contetx client
  client/v3/client.go
Labels: backport/v3.5, ok-to-test

#17027 changelog: Update changelog for 3.5.11 to include url redirect fix
  CHANGELOG/CHANGELOG-3.5.md
Labels: needs-ok-to-test

#17040 Fix message in case of unsupported platform
  server/etcdmain/etcd.go
Labels: ok-to-test
