Repository etcd-io/etcd, pull requests merged in 2023-07, with the labels that each got.

#15924 Add cluster id check for hash kv handler
  api/v3rpc/rpctypes/error.go
  server/etcdserver/api/rafthttp/http.go
  server/etcdserver/api/rafthttp/stream.go
  server/etcdserver/api/rafthttp/util.go
  server/etcdserver/corrupt.go
  server/etcdserver/corrupt_test.go
  tests/e2e/corrupt_test.go
  tests/framework/e2e/cluster.go
  tests/integration/hashkv_test.go
Labels: stage/merge-when-tests-green

#16156 clientv3: remove v3.WithFirstKey() in Barrier.Wait()
  client/v3/experimental/recipes/barrier.go
  tests/integration/clientv3/experimental/recipes/v3_barrier_test.go
Labels: backport/v3.5, stage/merge-when-tests-green

#16120 etcdutl: fix db double closed
  etcdutl/snapshot/v3_snapshot.go
Labels: backport/v3.5

#16194 Update CHANGELOG for #16029 #16165 #16193
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
  CHANGELOG/CHANGELOG-3.6.md
Labels: stage/merge-when-tests-green

#16200 clientv3: create keepAliveCtxCloser goroutine only if ctx can be canc…
  client/v3/lease.go
Labels: backport/v3.4, backport/v3.5

#16272 pkg/flags: fix UniqueURLs'Set to remove duplicates in UniqueURLs'uss
  pkg/flags/unique_urls.go
  pkg/flags/unique_urls_test.go
Labels: backport/v3.4, backport/v3.5

#16248 Replace unnecessary Lock()/Unlock()s with RLock()/RUnlock()s
  server/storage/backend/read_tx.go
  server/storage/mvcc/kvstore.go
  server/storage/schema/alarm.go
  server/storage/schema/membership.go
  server/storage/schema/schema.go
  server/storage/schema/version.go
Labels: backport/v3.4, backport/v3.5
