Repository etcd-io/etcd, pull requests merged in 2023-06, with the labels that each got.

#16003 Promote etcd frequently asked questions in our bug report template and readme
  .github/ISSUE_TEMPLATE/bug-report.yml
  README.md
Labels: area/documentation, area/community

#15985 Check ScheduledCompactKeyName and FinishedCompactKeyName before writing hash
  server/etcdserver/corrupt.go
  server/storage/mvcc/kvstore.go
  server/storage/mvcc/kvstore_test.go
  tests/e2e/corrupt_test.go
  tests/framework/e2e/cluster.go
Labels: backport/v3.5

#16027 Update the go version to 1.19.10 patch release
  .go-version
Labels: backport/v3.4, backport/v3.5

#16005 Early exit auth check on lease puts
  server/etcdserver/apply/apply_auth.go
  server/etcdserver/apply/apply_auth_test.go
  server/lease/lease.go
  server/lease/lessor.go
Labels: area/performance, backport/v3.4, backport/v3.5, stage/merge-when-tests-green

#16086 etcdserver: add tests for apply_auth.go
  server/etcdserver/apply/apply_auth_test.go
Labels: stage/merge-when-tests-green

#16127 add runtime reconfiguration tests
  tests/e2e/ctl_v3_auth_cluster_test.go
  tests/e2e/etcd_grpcproxy_test.go
  tests/e2e/etcd_mix_versions_test.go
  tests/e2e/runtime_reconfiguration_test.go
  tests/framework/e2e/cluster.go
  tests/framework/e2e/etcdctl.go
Labels: stage/merge-when-tests-green
