Repository etcd-io/etcd, pull requests merged in 2023-01, with the labels that each got.

#15048 tests: Implement network delay and blackholing in linearizability tests
  tests/e2e/ctl_v3_snapshot_test.go
  tests/e2e/etcd_grpcproxy_test.go
  tests/framework/e2e/cluster.go
  tests/framework/e2e/cluster_proxy.go
  tests/framework/e2e/curl.go
  tests/framework/e2e/etcd_process.go
  tests/linearizability/failpoints.go
  tests/linearizability/linearizability_test.go
Labels: stage/merge-when-tests-green

#15059 tests: Rewrite etcd requests to use operations
  tests/linearizability/history.go
  tests/linearizability/model.go
  tests/linearizability/model_test.go
  tests/linearizability/traffic.go
Labels: stage/merge-when-tests-green

#15068 etcdserver: process the case of the last WAL record being partially synced to disk [backport 3.5]
  server/etcdserver/bootstrap.go
  server/storage/wal/decoder.go
  server/storage/wal/wal.go
  server/storage/wal/wal_test.go
  tools/etcd-dump-logs/raw.go
Labels: backport/v3.5

#15094 CHANGELOG: add dep update item to 3.4
  CHANGELOG/CHANGELOG-3.4.md
Labels: stage/merge-when-tests-green

#15095 etcdserver: return `membership.ErrIDNotFound` when the memberID not found
  server/etcdserver/server.go
Labels: backport/v3.4, backport/v3.5

#15135 CHANGELOG: add item about improvement for count-only range
  CHANGELOG/CHANGELOG-3.4.md
Labels: stage/merge-when-tests-green

#15133 tests: Persist operation history
  tests/linearizability/linearizability_test.go
Labels: stage/merge-when-tests-green

#15192 etcdserver: correct the old name of notifyc in comments
  server/etcdserver/raft.go
Labels: stage/merge-when-tests-green

#15153 netutil: consistently format ipv6 addresses
  pkg/netutil/netutil.go
  pkg/netutil/netutil_test.go
Labels: backport/v3.4, backport/v3.5
