Repository etcd-io/etcd, pull requests merged in 2024-01, with the labels that each got.

#17189 [3.4] Add missing `experimental-enable-lease-checkpoint-persist` flag in etcd help
  etcdmain/help.go
Labels: backport/v3.4, ok-to-test

#17190 [3.5] Add missing `experimental-enable-lease-checkpoint-persist` flag in etcd help
  server/etcdmain/help.go
Labels: backport/v3.5, ok-to-test

#17177 Backport testutils.ExecuteUntil to 3.5 branch
  tests/framework/testutils/execute.go
Labels: ok-to-test

#17202 [3.4]Add a unit tests and missing flags in etcd help.
  etcdmain/config_test.go
  etcdmain/help.go
Labels: needs-ok-to-test

#17201 [3.5]Add a unit tests and missing flags in etcd help.
  server/etcdmain/config_test.go
  server/etcdmain/help.go
Labels: needs-ok-to-test

#17103 Update arm64 infra guide standard `arm64` runner definition
  Documentation/infra-guide/arm64-infra.md
Labels: ok-to-test

#17200 Automate installation of yamllint
  Makefile
  scripts/genproto.sh
Labels: ok-to-test

#17199 Don't flock snapshot files
  client/pkg/fileutil/purge.go
  client/pkg/fileutil/purge_test.go
  server/etcdserver/server.go
Labels: backport/v3.4, backport/v3.5

#17220 Bump dependencies manually
  Documentation/dev-guide/apispec/swagger/rpc.swagger.json
  api/etcdserverpb/gw/rpc.pb.gw.go
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go
  server/etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: ok-to-test

#17225 docs: update rotation worksheet
  Documentation/contributor-guide/dependency_management.md
Labels: needs-ok-to-test

#17219 Fix Struct Config has methods on both value and pointer receivers. Such usage is not recommended by the Go Documentation.
  server/embed/config.go
  server/embed/config_logging.go
Labels: ok-to-test

#17123 [3.5] member replace e2e test
  tests/e2e/corrupt_test.go
  tests/e2e/ctl_v3_member_no_proxy_test.go
  tests/e2e/etcdctl.go
  tests/e2e/utils.go
Labels: needs-ok-to-test

#17173 [3.4] member replace e2e test
  tests/e2e/ctl_v3_member_no_proxy_test.go
  tests/e2e/etcdctl.go
  tests/e2e/utils.go
Labels: stage/merge-when-tests-green, needs-ok-to-test

#17228 Fix tx buffer inconsistency if there are duplicate keys in one tx.
  server/storage/backend/batch_tx_test.go
  server/storage/backend/tx_buffer.go
Labels: backport/v3.4, backport/v3.5

#17229 Ensure bin/python directory is cleaned after install
  Makefile
Labels: ok-to-test

#17238 [3.4] Fix delete inconsistencies in read buffer
  clientv3/integration/user_test.go
  go.mod
  go.sum
  mvcc/backend/batch_tx.go
  mvcc/backend/batch_tx_test.go
Labels: stage/merge-when-tests-green

#17242 [3.4] Backport adding digest for etcd base image
  Dockerfile-release
  Dockerfile-release.arm64
  Dockerfile-release.ppc64le
Labels: stage/merge-when-tests-green

#17204 mvcc: Printing etcd backend database related metrics inside scheduleCompaction function
  server/storage/mvcc/kvstore_compaction.go
Labels: needs-ok-to-test

#17249 Replace `CreateBucket` with `CreateBucketIfNotExists`
  server/storage/backend/batch_tx.go
Labels: stage/merge-when-tests-green

#17275 [3.5] dependency: upgrade go to 1.20.13
  .go-version
Labels: ok-to-test

#17273 Added container tools to devcontainer for debugging prow jobs
  .devcontainer/devcontainer.json
Labels: ok-to-test

#17286 Fix golangci revive error-strings issues
  client/internal/v2/client_test.go
  client/internal/v2/keys_test.go
  client/internal/v2/members_test.go
  tools/.golangci.yaml
Labels: ok-to-test

#17291 [3.5] mvcc: Printing etcd backend database related metrics inside scheduleCompaction function
  server/mvcc/kvstore_compaction.go
Labels: needs-ok-to-test

#17276 [3.4] dependency: update go to 1.20.13
  .go-version
  Makefile
  functional/scripts/docker-local-agent.sh
  functional/scripts/docker-local-tester.sh
Labels: stage/merge-when-tests-green, ok-to-test

#17307 Add backoff & retries to client config
  client/v3/client.go
  client/v3/client_test.go
  client/v3/config.go
Labels: ok-to-test

#17309 changelog: add 3.4 and 3.5 note about go 1.20.13
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: stage/merge-when-tests-green, ok-to-test

#17288 Added a error log when learner is not sync with etcd leader.
  server/etcdserver/server.go
Labels: stage/merge-when-tests-green, ok-to-test
