Repository etcd-io/etcd, pull requests merged in 2024-02, with the labels that each got.

#17358 Manually bump dependencies
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: stage/merge-when-tests-green, needs-ok-to-test

#17363 [3.5] backport backoff/retry config
  client/v3/client.go
  client/v3/client_test.go
  client/v3/config.go
Labels: needs-ok-to-test

#17362 [3.5] Update to go 1.21
  .go-version
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/v2/go.mod
  client/v2/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  raft/go.mod
  server/embed/config_tracing.go
  server/go.mod
  server/go.sum
  server/mvcc/kvstore_compaction.go
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
Labels: ok-to-test

#17368 [3.4] Update to go1.21
  .go-version
  Makefile
  functional/scripts/docker-local-agent.sh
  functional/scripts/docker-local-tester.sh
  go.mod
  tools/mod/go.mod
Labels: ok-to-test

#17369 [3.4] add backoff to client config
  clientv3/client.go
  clientv3/client_test.go
  clientv3/config.go
Labels: ok-to-test

#17370 Add backoff/retry config to changelog
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: stage/merge-when-tests-green, ok-to-test

#15812 etcd: ignore SetKeepAlivePeriod errors on OpenBSD
  client/pkg/transport/keepalive_listener.go
  client/pkg/transport/keepalive_listener_openbsd.go
  client/pkg/transport/keepalive_listener_unix.go
Labels: stage/tracked

#17387 [3.5] Backport ignore SetKeepAlivePeriod errors on OpenBSD
  client/pkg/transport/keepalive_listener.go
  client/pkg/transport/keepalive_listener_openbsd.go
  client/pkg/transport/keepalive_listener_unix.go
Labels: ok-to-test

#17392 Manually bump dependencies
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: stage/merge-when-tests-green, ok-to-test

#17388 add OpenBSD support to changelog 3.5
  CHANGELOG/CHANGELOG-3.5.md
Labels: stage/merge-when-tests-green, ok-to-test

#17380 Add go1.21 update to changelog
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test

#17398 [3.4] tests/e2e: backport WaitLeader
  tests/e2e/cluster_test.go
  tests/e2e/etcd_process.go
  tests/e2e/etcdctl.go
Labels: ok-to-test

#17418 Make CGO_ENABLED configurable
  scripts/build_lib.sh
Labels: stage/merge-when-tests-green, ok-to-test

#17422 [3.4] Make CGO_ENABLED configurable
  build
Labels: ok-to-test

#17421 [3.5] Make CGO_ENABLED configurable
  build.sh
Labels: stage/merge-when-tests-green, ok-to-test

#17277 etcdutl: Fix snapshot restore memory alloc issue
  etcdutl/etcdutl/snapshot_command.go
  etcdutl/snapshot/v3_snapshot.go
  server/storage/backend/backend.go
Labels: ok-to-test

#17423 feat: add `TestNoErrorLogsDuringNormalOperations` e2e test to validate error logs during etcd bootstrap
  tests/e2e/logging_test.go
Labels: needs-ok-to-test

#17427 [3.5] Implement etcd process go fail client timeout
  tests/framework/e2e/cluster.go
  tests/framework/e2e/etcd_process.go
Labels: stage/merge-when-tests-green, ok-to-test

#17433 server: fix comment to match function name
  server/etcdserver/api/etcdhttp/health.go
Labels: ok-to-test

#17434 *: fix failing shellchecks
  build.sh
  scripts/install-marker.sh
Labels: ok-to-test

#17432 [3.4] backport EtcdProcess GoFailClientTimeout
  tests/e2e/cluster_test.go
  tests/e2e/etcd_process.go
Labels: ok-to-test

#17439 [3.5] tools/mod: go mod tidy
  tools/mod/go.mod
  tools/mod/go.sum
Labels: ok-to-test

#17441 server/verify: use retErr to shadow local err
  server/verify/verify.go
Labels: stage/merge-when-tests-green

#17445 *: update logrus to v1.9.3
  go.mod
  go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
Labels: ok-to-test

#17435 *: add test-smoke to the pipeline and update test-smoke
  .github/workflows/tests-template.yaml
  .github/workflows/tests.yaml
  Makefile
Labels: ok-to-test

#17425 [3.5] backport ignore old leaders leases revoking requests
  server/etcdserver/server.go
  server/etcdserver/v3_server.go
  server/lease/lessor.go
  server/lease/lessor_test.go
  tests/e2e/v3_lease_no_proxy_test.go
  tests/framework/e2e/cluster.go
  tests/integration/v3_lease_test.go
Labels: ok-to-test

#17366 Added client keepalive arguments to the grpc-proxy
  server/etcdmain/grpc_proxy.go
Labels: ok-to-test

#17447 [3.5] Added client keepalive arguments to the grpc-proxy
  server/etcdmain/grpc_proxy.go
Labels: ok-to-test

#17446 Fix typo in etcdctl/README.md
  etcdctl/README.md
Labels: ok-to-test

#17465 [3.4] backport ignore old leader leases revoking requests
  etcdserver/server.go
  etcdserver/v3_server.go
  integration/v3_lease_test.go
  lease/lessor.go
  lease/lessor_test.go
  tests/e2e/cluster_test.go
  tests/e2e/etcdctl.go
  tests/e2e/v3_lease_no_proxy_test.go
Labels: ok-to-test

#17481 Increased timeout to fix TestHashKVWhenCompacting test
  server/storage/mvcc/kvstore_test.go
Labels: stage/merge-when-tests-green, ok-to-test

#17482 [3.5] dependency: bump github.com/sirupsen/logrus to v1.9.3
  go.mod
  go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: ok-to-test

#17488 update CHANGELOG-3.5.md for #17447
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test

#17469 Add Cyberfusion to adopters
  ADOPTERS.md
Labels: ok-to-test
