Repository etcd-io/etcd, pull requests merged in 2024-07, with the labels that each got.

#18245 Suppress noisy basic auth token deletion log
  server/auth/simple_token.go
Labels: ok-to-test, size/XS

#18233 etcdctl: add support for filtering by {min,max} x {create,mod} x {revision}
  etcdctl/README.md
  etcdctl/ctlv3/command/get_command.go
  tests/e2e/ctl_v3_kv_test.go
Labels: area/testing, area/etcdctl, ok-to-test, size/L

#18270 Bump Go version to 1.22.5: GO-2024-2963 fix.
  .go-version
  api/go.mod
  client/internal/v2/go.mod
  client/pkg/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
  tools/rw-heatmaps/go.mod
  tools/testgrid-analysis/go.mod
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, ok-to-test, size/S

#18271 [3.5] Bump Go version to 1.21.12: GO-2024-2963 fix
  .go-version
  api/go.mod
  client/pkg/go.mod
  client/v2/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  raft/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
Labels: ok-to-test, size/S

#18272 [3.4]: Bump Go version to 1.21.12: GO-2024-2963 fix.
  .go-version
  functional/scripts/docker-local-agent.sh
  functional/scripts/docker-local-tester.sh
  go.mod
  tools/mod/go.mod
Labels: ok-to-test, size/S

#18266 [2024-07-03] Manual Dependency Bump
  bill-of-materials.json
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
Labels: area/testing, area/clientv3, area/etcdctl, area/etcdutl, ok-to-test, size/L

#18273 Follow up manual Dependency Bump
  tools/mod/go.mod
  tools/mod/go.sum
Labels: area/tooling, stage/merge-when-tests-green, ok-to-test, size/S

#18280 make: Include tools/mod when checking dependency versions
  scripts/test.sh
  tools/mod/go.mod
  tools/mod/go.sum
Labels: area/tooling, size/S

#18250 Remove gsutil acl command for bucket permissions from release.sh
  scripts/release.sh
Labels: area/tooling, backport/v3.4, backport/v3.5, size/XS

#18281 changed the scorecard badge link to the standard format
  README.md
Labels: ok-to-test, size/XS

#18278 Update CHANGELOG-3.5 with backported commit
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test, size/XS

#18282 CHANGELOG: Update to reflect go version 1.21.12 bump
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test, size/XS

#18277 robustness: remove head rev match in validateGotAtLeastOneProgressNotify
  tests/robustness/watch.go
Labels: area/testing, area/robustness-testing, size/XS

#18287 client/pkg/testutil: update interestingGoroutines
  client/pkg/testutil/leak.go
Labels: stage/merge-when-tests-green, size/XS, approved

#18284 [3.5] make: Include tools/mod when checking dependency versions
  test.sh
  tools/mod/go.mod
  tools/mod/go.sum
Labels: ok-to-test, size/L

#18308 client/v3/watch.go: use `fmt` go pkg for metadata map printing
  client/v3/watch.go
  client/v3/watch_test.go
Labels: area/clientv3, github_actions, ok-to-test, size/M, approved

#18310 [2024-07-08] Manual Dependency Bump
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#18312 [3.5] client/v3/watch.go: use fmt go pkg for gRPC metadata map printing
  client/v3/watch.go
  client/v3/watch_test.go
Labels: area/performance, area/documentation, area/testing, area/tooling, area/etcdctl, area/contrib, github_actions, ok-to-test, area/observability, size/M

#18311 [3.4] client/v3/watch.go: use fmt go pkg for gRPC metadata map printing
  clientv3/watch.go
  clientv3/watch_test.go
Labels: area/performance, area/documentation, area/testing, area/tooling, area/etcdctl, area/contrib, github_actions, ok-to-test, area/observability, size/M

#18314 github: remove amd64 test actions
  .github/workflows/tests.yaml
Labels: github_actions, size/XS, approved, lgtm

#18313 Differentiate the warning message for rejected client and peer connections
  server/embed/config_logging.go
  tests/e2e/zap_logging_test.go
Labels: area/testing, backport/v3.5, size/L, approved

#18319 [3.5] Differentiate the warning message for rejected client and peer connections
  server/embed/config_logging.go
  tests/e2e/zap_logging_test.go
Labels: size/L

#18320 CHANGELOG Differentiate the warning message for rejected client and peer connections for release-3.5
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#18317 CHANGELOG/CHANGELOG-3.5.md: update changelog for gRPC metadata printing
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test, size/XS, approved

#18316 CHANGELOG/CHANGELOG-3.4.md: update changelog for gRPC metadata printing
  CHANGELOG/CHANGELOG-3.4.md
Labels: ok-to-test, size/XS, approved

#17564 fileutil: improve control flow readability of purgeFile function
  client/pkg/fileutil/purge.go
Labels: ok-to-test, size/M

#18318 marker(markdown linter): use released binary when running markdown lint
  scripts/test.sh
Labels: size/S, approved, lgtm

#18289 [3.5] Backport fix(server/embed) enforce non-empty client TLS if scheme is https/unixs
  server/embed/etcd.go
  server/embed/etcd_test.go
  server/etcdmain/help.go
  tests/e2e/etcd_config_test.go
  tests/e2e/utils.go
Labels: size/L, lgtm

#18342 [2024-07-15] Manual Dependency Bump
  api/go.mod
  api/go.sum
  bill-of-materials.json
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#18321 mvcc/*_test.go: should not use duplicate revision.Main for one key
  server/storage/mvcc/key_index_test.go
Labels: size/M, approved

#18345 [3.4] Remove gsutil acl command for bucket permissions
  scripts/release.sh
Labels: size/XS

#18279 Add "server-feature-gates" flag.
  pkg/featuregate/feature_gate.go
  pkg/featuregate/feature_gate_test.go
  server/embed/config.go
  server/embed/etcd.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
  server/features/etcd_features.go
Labels: size/L, approved

#16333 Introduce Kubernetes interface to etcd client
  client/v3/auth.go
  client/v3/client.go
  client/v3/cluster.go
  client/v3/kubernetes/client.go
  client/v3/kubernetes/interface.go
  client/v3/kv.go
  client/v3/lease.go
  client/v3/maintenance.go
  client/v3/txn.go
  client/v3/watch.go
Labels: area/documentation, area/testing, area/clientv3, area/tooling, area/etcdctl, stage/merge-when-tests-green, area/etcdutl, area/observability, size/L, approved

#18283 etcdserver: change the snapshot + compact into sync operation
  server/etcdserver/server.go
Labels: ok-to-test, size/M, approved

#18358 Introduce Kubernetes KV interface to etcd client
  client/v3/auth.go
  client/v3/client.go
  client/v3/cluster.go
  client/v3/kubernetes/client.go
  client/v3/kubernetes/interface.go
  client/v3/kv.go
  client/v3/lease.go
  client/v3/maintenance.go
  client/v3/txn.go
  client/v3/watch.go
Labels: size/L

#18366 dependency: Bumps golang.org/x/image from 0.11.0 to 0.18.0
  tools/rw-heatmaps/go.mod
  tools/rw-heatmaps/go.sum
Labels: area/performance, area/tooling, stage/merge-when-tests-green, size/S, approved

#18367 github/workflows: pin robutness tests dependencies
  .github/workflows/robustness-template.yaml
Labels: github_actions, size/XS, approved

#18365 Add config file field for feature-gates flag.
  server/embed/config.go
  server/embed/config_test.go
Labels: size/M, approved

#18368 github/workflows: set read-only default permissions to approve workflow
  .github/workflows/gh-workflow-approve.yaml
Labels: github_actions, size/XS, approved

#18371 tests: remove Dockerfile
  scripts/install-marker.sh
  tests/Dockerfile
Labels: area/testing, size/M, approved

#18373 Fix wait time docs, tests to indicate trigger deadline geq to wait deadline.
  pkg/wait/wait_time.go
  pkg/wait/wait_time_test.go
Labels: ok-to-test, size/S, approved

#18369 tests/e2e: add test cases related to HashKV
  tests/e2e/hashkv_test.go
Labels: area/testing, size/L, approved

#18384 [2024-07-29] Manual Dependency Bump
  api/etcdserverpb/gw/rpc.pb.gw.go
  api/go.mod
  api/go.sum
  client/internal/v2/go.mod
  client/internal/v2/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go
  server/etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#18252 Reduce client concurrency for high traffic robustness tests
  tests/robustness/traffic/traffic.go
Labels: area/testing, area/robustness-testing, ok-to-test, size/XS, approved
