Repository etcd-io/etcd, pull requests merged in 2024-08, with the labels that each got.

#18387 tests/e2e: check compactOnRev > tombstoneRevs[0]
  tests/e2e/hashkv_test.go
Labels: area/testing, stage/merge-when-tests-green, size/XS, approved

#18383 Update release.md to reflect notes taken during 3.5.15 release
  Documentation/contributor-guide/release.md
Labels: area/documentation, size/XS, approved

#18392 Remove flake caused failpoint in watch disrupting progress notifies
  tests/robustness/main_test.go
Labels: area/testing, area/robustness-testing, size/XS, approved

#18396 Upgrade gofail to v0.2.0
  go.mod
  go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: size/S

#18395 Upgrade gofail to v0.2.0
  client/pkg/go.mod
  client/pkg/go.sum
  client/v2/go.sum
  client/v3/go.sum
  etcdctl/go.sum
  etcdutl/go.sum
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: size/M

#18398 [3.5] Cleanup github.com/etcd-io/gofail
  bill-of-materials.json
  tests/functional/cmd/etcd-tester/main.go
  tests/go.mod
  tests/go.sum
Labels: size/S

#18397 Ensure proper gofail package version in robustness tests
  tests/robustness/makefile.mk
Labels: area/testing, area/robustness-testing, size/XS, approved

#18394 Backport migration of OWNERS file.
  OWNERS
Labels: size/S

#18400 Complete backport of migration to OWNERS file.
  CONTRIBUTING.md
  GOVERNANCE.md
  MAINTAINERS
Labels: size/M, approved

#18183 Add examples to `etcdctl snapshot` command's help
  etcdctl/ctlv3/command/snapshot_command.go
  etcdctl/util/normalizer.go
  pkg/cobrautl/help.go
Labels: area/etcdctl, needs-ok-to-test, size/L, approved

#18359 migrate experimental-stop-grpc-service-on-defrag flag to feature gate.
  pkg/flags/flag.go
  server/config/config.go
  server/embed/config.go
  server/embed/config_test.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
  server/etcdserver/api/v3rpc/health.go
  server/features/etcd_features.go
  tests/e2e/failover_test.go
  tests/framework/e2e/cluster.go
  tests/framework/integration/cluster.go
Labels: area/testing, size/L, approved

#18417 Remove arm64 robustness github actions workflows
  .github/workflows/robustness-nightly.yaml
  .github/workflows/robustness-template.yaml
Labels: github_actions, size/L, approved

#18418 [2024-08-08] Bump dependency updates identified by dependabot
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/rw-heatmaps/go.mod
  tools/rw-heatmaps/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, stage/merge-when-tests-green, area/etcdutl, size/L, approved

#18420 go version bump from 1.22.5 to 1.22.6
  .go-version
  api/go.mod
  client/internal/v2/go.mod
  client/pkg/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
  tools/rw-heatmaps/go.mod
  tools/testgrid-analysis/go.mod
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/S, approved

#18421 [release-3.5] go version bump from 1.21.12 to 1.21.13
  .go-version
  api/go.mod
  client/pkg/go.mod
  client/v2/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  raft/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
Labels: size/S, approved

#18422 [release-3.4] go version bump from 1.21.12 to 1.21.13
  .go-version
  functional/scripts/docker-local-agent.sh
  functional/scripts/docker-local-tester.sh
  go.mod
  tools/mod/go.mod
Labels: size/S

#18423 Update release-3.4 and release-3.5 CHANGELOG with go version bump
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: stage/merge-when-tests-green, size/XS, approved

#18427 [2024-08-09] Bump dependency updates identified by dependabot
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/M, approved

#18399 Keep release process documentation up to date
  Documentation/contributor-guide/release.md
Labels: area/documentation, size/S, approved, lgtm

#18430 [3.5] Backport github/workflows: set read-only default permissions to approve workflow
  .github/workflows/gh-workflow-approve.yaml
Labels: size/XS, approved

#18431 Add `genproto` error troubleshoot step for manual bumps
  Documentation/contributor-guide/dependency_management.md
Labels: area/documentation, stage/merge-when-tests-green, size/S, approved

#18428 Skip leadership check if the etcd instance is active processing heartbeats
  server/etcdserver/raft.go
  server/etcdserver/server.go
  server/etcdserver/server_test.go
Labels: area/performance, backport/v3.4, backport/v3.5, size/M, approved

#18439 [3.5] Skip leadership check if the etcd instance is active processing heartbeats
  server/etcdserver/raft.go
  server/etcdserver/server.go
  server/etcdserver/server_test.go
Labels: size/M, approved

#18440 [3.4] Skip leadership check if the etcd instance is active processing heartbeats
  etcdserver/raft.go
  etcdserver/server.go
  etcdserver/server_test.go
Labels: size/M

#18441 Update changelog for the performance regression caused by ensureLeadership in leaseRenew
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#18442 Reduce number of concurrent clients to 8 and compactions to avoid flakes
  tests/robustness/traffic/etcd.go
  tests/robustness/traffic/kubernetes.go
  tests/robustness/traffic/traffic.go
Labels: area/testing, stage/merge-when-tests-green, area/robustness-testing, size/S, approved

#18448 Complete backport of OWNERS file.
  CONTRIBUTING.md
  Documentation/op-guide/supported-platform.md
  MAINTAINERS
  MAINTAINERS_RULES.md
  OWNERS
  README.md
Labels: size/M

#18274 *: keep tombstone if revision == compactAtRev
  server/storage/mvcc/hash.go
  server/storage/mvcc/index_test.go
  server/storage/mvcc/key_index.go
  server/storage/mvcc/key_index_test.go
  tests/e2e/watch_test.go
Labels: area/testing, area/robustness-testing, size/XL, approved

#18449 deleted infra-guide
  Documentation/infra-guide/arm64-infra.md
Labels: area/documentation, type/cleanup, ok-to-test, size/S, approved

#18450 test: extend leaseRevoke and leaseRenew test to support 5 members cluster
  tests/e2e/v3_lease_no_proxy_test.go
Labels: area/testing, size/S, approved

#18451 [3.5] test: extend leaseRevoke and leaseRenew test to support 5 members cluster
  tests/e2e/v3_lease_no_proxy_test.go
Labels: size/S, approved

#18452 [3.4] test: extend leaseRevoke and leaseRenew test to support 5 members cluster
  tests/e2e/v3_lease_no_proxy_test.go
Labels: size/S, approved

#18446 [release-3.5] Bump go toolchain to 1.22.6
  .go-version
  api/go.mod
  client/pkg/go.mod
  client/v2/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  raft/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
Labels: size/M, approved

#18445 [release-3.4] Bump go toolchain to 1.22.6
  .go-version
  functional/scripts/docker-local-agent.sh
  functional/scripts/docker-local-tester.sh
  go.mod
  pkg/debugutil/pprof.go
  tools/mod/go.mod
Labels: size/S, approved

#18458 [3.5] client/pkg/testutil: update interestingGoroutines
  client/pkg/testutil/leak.go
Labels: size/XS, approved

#18457 [3.5] tests/e2e: add e2e test to reproduce issue 18089
  tests/e2e/watch_test.go
Labels: size/M, approved

#18460 CHANGELOG: Add entry for etcdutl hashkv command.
  CHANGELOG/CHANGELOG-3.6.md
Labels: ok-to-test, size/XS, approved

#18454 github/workflows: remove e2e jobs
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e.yaml
Labels: github_actions, size/M, approved

#18461 [3.5] mvcc/*_test.go: should not use duplicate revision.Main for one key
  server/mvcc/key_index_test.go
Labels: size/M, approved

#18456 [3.4] mvcc/*_test.go: should not use duplicate revision.Main for one key
  mvcc/key_index_test.go
Labels: size/M, approved

#18455 [3.4] tests/e2e: add e2e test to reproduce issue 18089
  tests/e2e/watch_test.go
Labels: size/M, approved

#18476 [3.5] tests/e2e: add test cases related to HashKV
  tests/e2e/hashkv_test.go
Labels: size/L, approved

#18474 [3.5] *: keep tombstone if revision == compactAtRev
  server/mvcc/hash.go
  server/mvcc/index_test.go
  server/mvcc/key_index.go
  server/mvcc/key_index_test.go
  tests/e2e/watch_test.go
Labels: size/XL, approved

#18475 [3.4] *: keep tombstone if revision == compactAtRev
  mvcc/index_test.go
  mvcc/key_index.go
  mvcc/key_index_test.go
  mvcc/kvstore.go
  tests/e2e/watch_test.go
Labels: size/XL, approved

#18453 Revert "Disable robustness test detection of #18089 to allow detecting other issues
  tests/robustness/model/replay.go
  tests/robustness/validate/validate_test.go
  tests/robustness/validate/watch.go
Labels: area/testing, area/robustness-testing, size/L, approved

#18482 CHANGELOG: update changes for issue 18089
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: stage/merge-when-tests-green, size/XS, approved

#18478 KEP-4578: migrate experimental-initial-corrupt-check flag to feature gate.
  server/embed/config_test.go
  server/embed/etcd.go
  server/etcdmain/help.go
  server/features/etcd_features.go
Labels: ok-to-test, size/M, approved

#18490 [2024-08-24] Bump dependency updates identified by dependabot
  api/go.mod
  api/go.sum
  bill-of-materials.json
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#18489 [3.5] Bump bbolt to 1.3.11
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
Labels: ok-to-test, size/M, approved

#18488 [3.4] Bump bbolt to 1.3.11
  go.mod
  go.sum
Labels: ok-to-test, size/XS, approved

#18495 etcdserver: rename defaultCompactionSleepInterval var
  server/storage/mvcc/kvstore.go
  server/storage/mvcc/kvstore_test.go
Labels: ok-to-test, size/S, approved

#18512 CHANGELOG: Add entries for bbolt dependency bump
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test, size/XS, approved

#18360 Fix passing default grpc call options in Kubernetes client
  client/v3/kubernetes/client.go
Labels: area/clientv3, size/M, approved

#18517 [release-3.5] Fix passing default grpc call options in Kubernetes client
  client/v3/kubernetes/client.go
Labels: size/M, approved

#18515 [2024-08-29] Bump dependency updates identified by dependabot
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tests/integration/clientv3/lease/lease_test.go
  tests/integration/metrics_test.go
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved
