Repository etcd-io/etcd, pull requests merged in 2024-03, with the labels that each got.

#17518 etcdserver: skip when detect a removed peer
  server/etcdserver/raft.go
Labels: stage/merge-when-tests-green, ok-to-test

#17541 [3.4] Update go version to 1.21.8 for build.
  Makefile
  functional/scripts/docker-local-agent.sh
  functional/scripts/docker-local-tester.sh
Labels: ok-to-test

#17393 Migrate to go1.22
  .devcontainer/devcontainer.json
  .go-version
  api/go.mod
  client/internal/v2/go.mod
  client/pkg/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
Labels: ok-to-test

#17543 [2024-03-04] Bump dependencies identified by dependabot
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: stage/merge-when-tests-green, ok-to-test

#17553 [3.5] dependency: bump google protobuf to 1.33.0
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  raft/go.mod
  raft/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
Labels: ok-to-test

#17554 [3.4] dependency: bump google protobuf to 1.33.0
  go.mod
  go.sum
Labels: ok-to-test

#17550 [3.5] Add govuln GitHub workflow
  .github/workflows/govuln.yaml
Labels: ok-to-test

#17559 [3.4][3.5] Changelog: Add CVE-2024-24786 remediation
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: stage/merge-when-tests-green, ok-to-test

#17561 tests: temporary disable coverage redisign Go experiment
  scripts/codecov_upload.sh
Labels: ok-to-test

#17428 Reimplement tools/rw-heatmaps in go
  tools/rw-heatmaps/README.md
  tools/rw-heatmaps/cmd/root.go
  tools/rw-heatmaps/go.mod
  tools/rw-heatmaps/go.sum
  tools/rw-heatmaps/main.go
  tools/rw-heatmaps/pkg/chart/heatmap_grid.go
  tools/rw-heatmaps/pkg/chart/heatmaps.go
  tools/rw-heatmaps/pkg/dataset/dataset.go
  tools/rw-heatmaps/plot_data.py
  tools/rw-heatmaps/requirements.txt
Labels: ok-to-test

#17557 Fix progress notification for watch that doesn't get any events
  server/etcdserver/api/v3rpc/watch.go
  tests/integration/v3_watch_test.go
Labels: backport/v3.4, backport/v3.5

#17580 [3.4] dependency: bump github.com/sirupsen/logrus to v1.9.3
  go.mod
  go.sum
Labels: ok-to-test

#17582 client: address golangci var-naming issues
  client/pkg/logutil/log_format.go
  client/pkg/logutil/log_format_test.go
  client/pkg/tlsutil/cipher_suites_test.go
  client/pkg/verify/verify.go
  client/v3/client.go
  client/v3/internal/endpoint/endpoint.go
  client/v3/internal/endpoint/endpoint_test.go
  client/v3/mock/mockserver/mockserver.go
  client/v3/retry_interceptor.go
  client/v3/watch.go
  tests/integration/clientv3/concurrency/example_election_test.go
  tests/integration/clientv3/concurrency/example_mutex_test.go
  tests/integration/clientv3/concurrency/example_stm_test.go
Labels: ok-to-test

#17555 Fix watch event loss
  server/etcdserver/api/v3rpc/watch.go
  server/storage/mvcc/watchable_store.go
  server/storage/mvcc/watchable_store_test.go
  tests/integration/v3_watch_test.go
  tests/robustness/makefile.mk
Labels: backport/v3.4, backport/v3.5, priority/critical-urgent

#17597 Update community meeting docs to cover lead rotation
  README.md
Labels: stage/merge-when-tests-green

#17613 Let dapendabot to auto-update docker for release 3.4&3.5.
  .github/dependabot.yml
Labels: ok-to-test

#17620 [2023-03-18] Weekly dependency update
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: stage/merge-when-tests-green

#17588 flaky: fix jwt test with increasing ttl
  tests/framework/e2e/cluster.go
Labels: ok-to-test

#17584 pkg: address golangci var-naming issues
  pkg/expect/expect.go
  pkg/grpctesting/recorder.go
  pkg/grpctesting/stub_server.go
  tests/framework/integration/cluster.go
  tests/integration/clientv3/naming/resolver_test.go
Labels: ok-to-test

#17640 fix some typos
  etcdctl/ctlv3/command/check.go
  scripts/test.sh
  scripts/test_images.sh
  scripts/test_lib.sh
  server/storage/backend/hooks_test.go
  server/storage/schema/auth_roles_test.go
  server/storage/schema/auth_users_test.go
  server/storage/schema/confstate.go
  server/storage/wal/wal.go
  tests/common/lease_test.go
  tests/integration/lazy_cluster.go
  tests/robustness/validate/validate_test.go
  tools/etcd-dump-logs/README.md
Labels: stage/merge-when-tests-green, ok-to-test

#17634 all: call Close() after reading http.Response.Body
  contrib/lock/client/client.go
  server/etcdserver/api/etcdhttp/peer_test.go
Labels: ok-to-test

#17652 all: make regexp.Regexp variables global when not using configuration…
  client/pkg/testutil/leak.go
  etcdctl/ctlv3/command/util.go
Labels: ok-to-test

#17618 feat: add wal write system call metrics observation (main)
  server/storage/wal/encoder.go
  server/storage/wal/metrics.go
Labels: ok-to-test
