Repository etcd-io/etcd, pull requests merged in 2024-04, with the labels that each got.

#17676 client/pkg/testutil: add shouldSkip func for interestingGoroutines
  client/pkg/testutil/leak.go
Labels: ok-to-test

#17678 changelog: change livez/readyz HTTP endpoints to v3.5.11
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test

#17690 nit: Fix trailing whitespace in etcdmain/help.go
  server/etcdmain/help.go
Labels: ok-to-test

#17675 client/pkg/testutil: eliminate copyToInterface function
  client/pkg/testutil/assert.go
Labels: ok-to-test

#17694 Replace run.skip-files with issues.exclude-files in golangci config
  tools/.golangci.yaml
Labels: ok-to-test

#17700 Makefile: perfect .PHONY
  Makefile
Labels: ok-to-test

#17698 changelog: add requests retry when receiving ErrGPRCNotSupportedForLearner
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: stage/merge-when-tests-green, ok-to-test

#17701 server/storage: change deprecated bolt error to new error package
  server/storage/backend/batch_tx.go
Labels: ok-to-test

#17699 Backport initialization of mu in NewCtxClient to release-3.5
  client/v3/client.go
Labels: ok-to-test

#17641 [3.5] backport for fix retry requests when receiving ErrGPRCNotSupportedForLearner
  client/v3/retry_interceptor.go
Labels: ok-to-test

#17692 [3.4] backport for fix retry requests when receiving ErrGPRCNotSupportedForLearner
  clientv3/retry_interceptor.go
Labels: ok-to-test

#17679 Add trivy scan action for current branch HEAD
  .github/workflows/release.yaml
Labels: ok-to-test

#17708 Bump go-version to 1.21.9 for release-3.5 due to CVE-2023-45288
  .go-version
  go.mod
  go.sum
Labels: ok-to-test

#17709 Bump go-version to 1.21.9 for release-3.4 due to CVE-2023-45288
  .go-version
  Makefile
  functional/scripts/docker-local-agent.sh
  functional/scripts/docker-local-tester.sh
  go.mod
  go.sum
Labels: ok-to-test

#17714 Backport initialization of epMu in NewCtxClient to release-3.4
  clientv3/client.go
Labels: ok-to-test

#17706 Update CHANGELOG 3.4 and 3.5 - initialization for epMu/mu in client context
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: stage/merge-when-tests-green, ok-to-test

#17710 tools/benchmark/cmd: don't panic with nil values in hashKV function
  tools/benchmark/cmd/put.go
Labels: ok-to-test

#17716 [3.5]Add trivy scan for current branch HEAD
  .github/workflows/release.yaml
  .github/workflows/trivy-nightly-scan.yaml
Labels: ok-to-test

#16764 Limit a timeout in testing robustness validation
  tests/robustness/main_test.go
  tests/robustness/validate/operations.go
  tests/robustness/validate/validate.go
  tests/robustness/validate/validate_test.go
Labels: stage/merge-when-tests-green

#17715 [3.4]Add trivy scan for current branch HEAD
  .github/workflows/release.yaml
  .github/workflows/trivy-nightly-scan.yaml
Labels: ok-to-test

#17619 [3.5] Add approvals gh workflows.
  .github/workflows/gh-workflow-approve.yaml
Labels: ok-to-test

#17616 [3.5] feat: add wal write system call metrics observation
  server/wal/encoder.go
  server/wal/metrics.go
Labels: ok-to-test

#17728 CHANGELOG:add wal write system call metrics observation
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test

#17758 Improve documentation
  CONTRIBUTING.md
  Documentation/contributor-guide/branch_management.md
  Documentation/contributor-guide/community-membership.md
  Documentation/contributor-guide/dependency_management.md
  Documentation/contributor-guide/features.md
  Documentation/contributor-guide/local_cluster.md
  Documentation/contributor-guide/logging.md
  Documentation/contributor-guide/modules.md
  Documentation/contributor-guide/release.md
  Documentation/contributor-guide/reporting_bugs.md
  Documentation/contributor-guide/roadmap.md
  Documentation/contributor-guide/triage_issues.md
  Documentation/contributor-guide/triage_prs.md
Labels: ok-to-test

#17751 [2024-04-08] Bump dependency updates identified by dependabot
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: ok-to-test

#17767 [2024-04-10] Bump dependency updates identified by dependabot
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: ok-to-test

#17729 fix: close profile in the mvccPutFunc func
  tools/benchmark/cmd/mvcc-put.go
Labels: ok-to-test

#17762 etcdserver: updated pre-vote flag description
  server/embed/config.go
  server/etcdmain/help.go
Labels: ok-to-test

#17809 tests: fix some typos in comments
  tests/common/kv_test.go
  tests/integration/clientv3/ordering_kv_test.go
  tests/integration/v3_watch_test.go
Labels: ok-to-test

#17787 server/etcdmain: eliminate deprecated tlsConfig.BuildNameToCertificate()
  server/etcdmain/grpc_proxy.go
Labels: ok-to-test

#17813 [backport-3.5] server: ignore raft messages if member id mismatch
  server/etcdserver/server.go
  server/etcdserver/server_test.go
Labels: ok-to-test

#17814 [backport-3.4] server: ignore raft messages if member id mismatch
  etcdserver/server.go
  etcdserver/server_test.go
Labels: ok-to-test

#17819 Update CHANGELOG 3.4 and 3.5 - ignore raft messages if member id mismatch
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test

#17816 server/auth: simplify code for isValidPermissionRange
  server/auth/range_perm_cache.go
Labels: ok-to-test

#17792 Update the compaction log when bootstrap and update compact's signature
  server/storage/mvcc/kvstore.go
Labels: backport/v3.4, backport/v3.5

#17791 Add verification that the revision shouldn't decrease on bootstrap
  server/storage/mvcc/kvstore.go
Labels: backport/v3.4, backport/v3.5

#17836 Manually bump dependencies
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: ok-to-test

#17815 [RFC] fix revision loss issue caused by compaction - 17780
  server/storage/mvcc/kvstore.go
  tests/e2e/reproduce_17780_test.go
Labels: release/v3.5, release/v3.4, priority/critical-urgent

#17826 Update CHANGELOG - 3.4, 3.5 - fix PRISMA-2023-0056
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test

#17862 server/storage/mvcc: should update currentRev in revMu
  server/storage/mvcc/kvstore.go
Labels: backport/v3.4, backport/v3.5, ok-to-test

#17834 server/proxy/tcpproxy: use net.JoinHostPort rather than formatAddr
  server/proxy/tcpproxy/userspace.go
  server/proxy/tcpproxy/userspace_test.go
Labels: type/cleanup, ok-to-test

#17878 all: don't convert byte slice to string when using verb %s
  client/pkg/transport/timeout_transport_test.go
  etcdctl/ctlv3/command/printer_simple.go
  etcdutl/snapshot/v3_snapshot.go
  server/etcdserver/api/etcdhttp/peer_test.go
  server/etcdserver/cluster_util.go
  server/etcdserver/corrupt.go
  server/etcdserver/corrupt_test.go
  server/lease/leasehttp/http.go
  server/storage/backend/backend.go
  server/storage/backend/batch_tx_test.go
  tests/integration/clientv3/naming/resolver_test.go
  tests/integration/snapshot/member_test.go
  tests/integration/snapshot/v3_snapshot_test.go
  tests/integration/v3_failover_test.go
Labels: ok-to-test

#17842 gofail: show error messages returned by gofail HTTP endpoints
  tests/framework/e2e/etcd_process.go
Labels: ok-to-test

#17893 github workflow: drop measure test flakiness
  .github/workflows/measure-test-flakiness.yaml
  .github/workflows/measure-testgrid-flakiness.yaml
  Makefile
  scripts/measure-test-flakiness.sh
Labels: ok-to-test

#17770 Test: add tools/rw-heatmaps & tools/testgrid-analysis to module_dirs
  scripts/test_lib.sh
  tools/testgrid-analysis/cmd/data.go
  tools/testgrid-analysis/cmd/github.go
Labels: stage/merge-when-tests-green, ok-to-test

#17913 github/workflows: skip robustness tests in forks
  .github/workflows/robustness-template.yaml
Labels: stage/merge-when-tests-green

#17793 Fix remove member failed.
  server/etcdserver/server.go
  tests/common/member_test.go
Labels: needs-ok-to-test
