Repository etcd-io/etcd, pull requests merged in 2024-12, with the labels that each got.

#18979 Fix gofump error due to merge race
  server/etcdserver/server.go
Labels: stage/merge-when-tests-green, size/XS, approved

#18821 fix: use require instead of t.Fatal(err) in tests/e2e package
  tests/e2e/ctl_v3_auth_test.go
  tests/e2e/ctl_v3_defrag_test.go
  tests/e2e/ctl_v3_elect_test.go
  tests/e2e/ctl_v3_grpc_test.go
  tests/e2e/ctl_v3_kv_test.go
  tests/e2e/ctl_v3_lock_test.go
  tests/e2e/ctl_v3_make_mirror_test.go
  tests/e2e/ctl_v3_member_test.go
  tests/e2e/ctl_v3_move_leader_test.go
  tests/e2e/ctl_v3_snapshot_test.go
  tests/e2e/ctl_v3_test.go
  tests/e2e/discovery_test.go
  tests/e2e/discovery_v3_test.go
  tests/e2e/etcd_config_test.go
  tests/e2e/etcd_grpcproxy_test.go
  tests/e2e/etcd_release_upgrade_test.go
  tests/e2e/gateway_test.go
  tests/e2e/http_health_check_test.go
  tests/e2e/logging_test.go
  tests/e2e/metrics_test.go
  tests/e2e/utl_migrate_test.go
  tests/e2e/v2store_deprecation_test.go
  tests/e2e/v3_curl_auth_test.go
  tests/e2e/v3_curl_cluster_test.go
  tests/e2e/v3_curl_election_test.go
  tests/e2e/v3_curl_lease_test.go
  tests/e2e/v3_curl_lock_test.go
  tests/e2e/v3_curl_maintenance_test.go
  tests/e2e/v3_curl_maxstream_test.go
  tests/e2e/v3_curl_watch_test.go
  tests/e2e/v3_lease_no_proxy_test.go
  tests/e2e/zap_logging_test.go
Labels: area/testing, ok-to-test, size/XL, approved

#18977 Handle non-linearized MemberList in v3.4 for robustness tests
  tests/robustness/failpoint/cluster.go
Labels: area/testing, stage/merge-when-tests-green, area/robustness-testing, size/S, approved

#17563 Reuse events used for syncing watchers
  server/storage/mvcc/watchable_store.go
  server/storage/mvcc/watchable_store_test.go
  server/storage/mvcc/watcher_test.go
Labels: size/L, approved

#18981 Extract rangeEvents function
  server/storage/mvcc/watchable_store.go
  server/storage/mvcc/watchable_store_test.go
Labels: size/L, approved

#18991 Reuse grpcOverheadBytes calculation by creating a function for that
  server/config/config.go
  server/etcdserver/api/v3rpc/grpc.go
  server/etcdserver/api/v3rpc/watch.go
  server/etcdserver/api/v3rpc/watch_test.go
Labels: size/S, approved

#18998 Mark --snapshot-count as deprecated in v3.6 and will be decommissioned in 3.7
  server/embed/config.go
  server/etcdmain/config.go
  server/etcdmain/help.go
  tests/e2e/etcd_config_test.go
Labels: area/testing, size/M, approved

#18999 [3.5] Print warning message for deprecated v2 flags if set
  server/etcdmain/config.go
  server/etcdmain/help.go
  tests/e2e/etcd_config_test.go
Labels: size/L, approved

#18966 fix: use testify instead of t.Fatal or t.Error in api package
  api/etcdserverpb/raft_internal_stringer_test.go
  api/v3rpc/rpctypes/error_test.go
Labels: ok-to-test, size/S, approved

#19002 [2024-12-02] Manual Dependency Bump
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
Labels: area/testing, area/etcdutl, size/S, approved

#19003 Bump go toolchain to 1.23.4
  .go-version
  api/go.mod
  client/internal/v2/go.mod
  client/pkg/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
  tools/rw-heatmaps/go.mod
  tools/testgrid-analysis/go.mod
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, ok-to-test, size/S, approved

#19004 [3.5] Bump go toolchain to 1.22.10
  .go-version
  api/go.mod
  client/pkg/go.mod
  client/v2/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  raft/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
Labels: ok-to-test, size/S, approved

#19005 [3.4] Bump Go to 1.22.10
  .go-version
  go.mod
  tools/mod/go.mod
Labels: ok-to-test, size/XS

#19008 Update 3.5 changelog to cover the warning message for the deprecated v2 flags if set
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#18973 fix: enable gosimple linter
  etcdctl/ctlv3/command/defrag_command.go
  etcdctl/main.go
  server/etcdserver/api/v3discovery/discovery.go
  server/etcdserver/cluster_util.go
  server/etcdserver/corrupt.go
  server/storage/mvcc/hash.go
  server/storage/wal/version.go
  tests/e2e/v2store_deprecation_test.go
  tests/e2e/v3_curl_maintenance_test.go
  tests/integration/clientv3/concurrency/example_stm_test.go
  tests/integration/revision_test.go
  tests/robustness/model/describe.go
  tests/robustness/model/replay.go
  tests/robustness/traffic/limiter.go
  tools/.golangci.yaml
Labels: area/testing, area/tooling, area/etcdctl, area/robustness-testing, needs-ok-to-test, size/M, approved

#19013 fix: golangci-lint yamllint
  tools/.golangci.yaml
Labels: area/tooling, ok-to-test, size/XS, approved

#18992 chore: group tools/mod updates and update only direct dependencies
  .github/dependabot.yml
Labels: ok-to-test, size/XS, approved

#19011 release: Allow "v" prefix when specifying release version
  scripts/release.sh
Labels: size/XS, approved

#19016 docs: Add note on releasing a pre-release
  Documentation/contributor-guide/release.md
Labels: area/documentation, size/XS, approved

#19006 Deprecate `--v2-deprecation` and schedule to remove it in 3.8
  server/config/v2_deprecation.go
  server/embed/config.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/help.go
  tests/e2e/etcd_config_test.go
Labels: area/testing, size/L, approved

#19028 Update Changelog of 3.5 and 3.4
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: area/documentation, ok-to-test, size/XS, approved

#19031 Format the 3.5 changelog
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#18968 fix: use testify instead of t.Fatal or t.Error in contrib package
  contrib/raftexample/kvstore_test.go
  contrib/raftexample/raft_test.go
  contrib/raftexample/raftexample_test.go
Labels: area/contrib, ok-to-test, size/S, approved

#19036 Mark --max-snapshots as deprecated in 3.6 and will be decommissioned …
  server/embed/config.go
  server/etcdmain/config.go
  server/etcdmain/help.go
  tests/e2e/etcd_config_test.go
Labels: area/testing, size/S, approved

#19034 Documentation: consistent way to manage go version
  Documentation/contributor-guide/dependency_management.md
Labels: area/documentation, ok-to-test, size/XS, approved

#19042 scripts: simplify mod tidy pass
  scripts/test.sh
Labels: size/S, approved

#19047 Add a TODO comment for UnsafeDetectSchemaVersion on how to simplify t…
  server/storage/schema/schema.go
Labels: size/XS, approved

#19046 Set a 80% threshold for the codecov status.patch
  codecov.yml
Labels: size/XS, approved

#19041 Do not wait for ready notify if the server is stopping
  server/embed/serve.go
Labels: size/XS, approved

#19048 [2024-12-09] Manual Dependency Bump
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/rw-heatmaps/go.mod
  tools/rw-heatmaps/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/XL, approved

#19057 Remove duplicated <-s.ReadyNotify()
  server/embed/serve.go
Labels: size/XS, approved

#19045 scripts: fix shellws pass
  scripts/test.sh
Labels: size/S, approved

#19065 [2024-12-13] Manual Dependency Bump
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19060 fix(e2e): ignore error log about failed storage update
  tests/e2e/logging_test.go
  tests/e2e/zap_logging_test.go
Labels: area/testing, size/M, approved

#18969 fix: use testify instead of t.Fatal or t.Error in etcdctl packages
  etcdctl/ctlv3/command/watch_command_test.go
  etcdctl/go.mod
  etcdctl/go.sum
Labels: area/etcdctl, ok-to-test, size/M, approved

#19068 Wait for cluster version to non-default value to remove errors when cluster is bootstrapping.
  server/etcdserver/version/monitor.go
Labels: size/XS, approved

#19067 Add more debug info when running into ErrSliceOutOfRange when reading WAL
  server/storage/wal/wal.go
Labels: size/XS, approved

#19069 Update the allowedErrors in TestNoErrorLogsDuringNormalOperations
  tests/e2e/logging_test.go
Labels: area/testing, size/S, approved

#19053 migrate experimental-compact-hash-check-enabled to feature gate.
  pkg/featuregate/feature_gate.go
  server/config/config.go
  server/embed/config.go
  server/embed/config_test.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
  server/etcdserver/server.go
  server/features/etcd_features.go
  tests/e2e/corrupt_test.go
  tests/framework/e2e/cluster.go
Labels: area/testing, size/L, approved

#19079 scripts: remove duplicate bom fix in fix make target
  scripts/fix.sh
Labels: size/XS, approved

#18970 fix: use testify instead of t.Fatal or t.Error in pkg package (part 1)
  pkg/adt/interval_tree_test.go
  pkg/crc/crc_test.go
  pkg/expect/expect_test.go
  pkg/flags/flag_test.go
  pkg/flags/strings_test.go
  pkg/flags/uint32_test.go
  pkg/flags/unique_strings_test.go
  pkg/flags/urls_test.go
  pkg/ioutil/pagewriter_test.go
  pkg/ioutil/readcloser_test.go
  pkg/report/report_test.go
  pkg/report/timeseries_test.go
  pkg/schedule/schedule_test.go
  pkg/stringutil/rand_test.go
  pkg/traceutil/trace_test.go
Labels: ok-to-test, size/L, approved

#19082 [tools/etcd-dump-logs] Fix the usage of --start-index in etcd-dump-logs
  tools/etcd-dump-logs/main.go
Labels: area/tooling, size/S, approved

#19085 scripts: remove receiver name check
  Makefile
  scripts/test.sh
Labels: size/S, approved

#19077 backend: Remove logger nil checks
  server/storage/backend/backend.go
Labels: ok-to-test, size/M, approved

#19081 Add more info in the error message in downgrade detection
  server/storage/schema/schema.go
  server/storage/schema/schema_test.go
Labels: size/XS, approved

#19080 [2024-12-16] Manual Dependency Bump
  api/go.mod
  api/go.sum
  bill-of-materials.json
  client/internal/v2/go.mod
  client/internal/v2/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  scripts/etcd_version_annotations.txt
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#18967 fix: use testify instead of t.Fatal or t.Error in client package (part 1)
  client/internal/v2/client_test.go
  client/internal/v2/keys_bench_test.go
  client/internal/v2/members_test.go
  client/pkg/fileutil/dir_windows.go
  client/pkg/fileutil/fileutil_test.go
  client/pkg/fileutil/read_dir_test.go
  client/pkg/srv/srv_test.go
  client/pkg/tlsutil/cipher_suites_test.go
  client/pkg/transport/keepalive_listener_test.go
  client/pkg/transport/listener_test.go
  client/pkg/transport/timeout_transport_test.go
  client/pkg/types/set_test.go
  client/pkg/types/urlsmap_test.go
  client/v3/client_test.go
  client/v3/compact_op_test.go
  client/v3/ctx_test.go
Labels: area/clientv3, ok-to-test, size/L, approved

#19078 migrate `--experimental-txn-mode-write-with-shared-buffer` flag to feature gate.
  server/embed/config.go
  server/embed/config_test.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/help.go
  server/etcdserver/server.go
  server/etcdserver/server_test.go
  server/etcdserver/txn/txn.go
  server/etcdserver/v3_server.go
  server/features/etcd_features.go
Labels: ok-to-test, size/L, approved

#19111 docs(contributing): fix links and build tool list
  CONTRIBUTING.md
Labels: ok-to-test, size/S, approved, lgtm

#19108 [2024-12-23] Manual Dependency Bump
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19038 Add MemberDowngrade failpoint
  tests/framework/e2e/curl.go
  tests/robustness/failpoint/cluster.go
  tests/robustness/failpoint/failpoint.go
  tests/robustness/report/wal.go
Labels: area/testing, area/robustness-testing, size/L, approved
