Repository etcd-io/etcd, pull requests merged in 2025-06, with the labels that each got.

#20073 Update changelog-3.6 to cover to fixes for 3.6.1
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#20091 Fix antithesis makefile target
  .github/workflows/antithesis-test.yml
Labels: github_actions, size/XS, approved

#20053 Sync keys in keystore on list request response
  tests/robustness/traffic/etcd.go
  tests/robustness/traffic/key_store.go
Labels: area/testing, area/robustness-testing, size/M, approved, do-not-merge/hold

#20085 chore(test): address Go usetesting for `v3_auth_test`
  tests/integration/v3_auth_test.go
Labels: area/testing, size/M, approved

#20086 chore(test): address Go usetesting for `v3_grpc_test`
  tests/integration/v3_grpc_test.go
Labels: area/testing, size/L, approved

#20087 chore(test): address Go usetesting for `v3_lease_test`
  tests/integration/v3_lease_test.go
Labels: area/testing, size/M, approved

#20088 chore(test): address Go usetesting for `clientV3`
  tests/integration/clientv3/cluster_test.go
  tests/integration/clientv3/kv_test.go
  tests/integration/clientv3/maintenance_test.go
  tests/integration/clientv3/metrics_test.go
  tests/integration/clientv3/mirror_auth_test.go
  tests/integration/clientv3/mirror_test.go
  tests/integration/clientv3/namespace_test.go
  tests/integration/clientv3/naming/endpoints_test.go
  tests/integration/clientv3/naming/resolver_test.go
  tests/integration/clientv3/ordering_kv_test.go
  tests/integration/clientv3/ordering_util_test.go
  tests/integration/clientv3/snapshot/v3_snapshot_test.go
  tests/integration/clientv3/txn_test.go
  tests/integration/clientv3/user_test.go
  tests/integration/clientv3/util.go
  tests/integration/clientv3/watch_fragment_test.go
Labels: area/testing, size/L, approved

#20050 Add List requests to Antithesis traffic
  tests/robustness/traffic/etcd.go
Labels: area/testing, area/robustness-testing, size/XS, approved

#20094 tests/integration: address usetesting issues
  tests/integration/cluster_test.go
  tests/integration/corrupt_test.go
  tests/integration/embed/embed_test.go
  tests/integration/grpc_test.go
  tests/integration/hashkv_test.go
  tests/integration/member_test.go
  tests/integration/metrics_test.go
  tests/integration/proxy/grpcproxy/cluster_test.go
  tests/integration/proxy/grpcproxy/kv_test.go
  tests/integration/revision_test.go
  tests/integration/snapshot/member_test.go
  tests/integration/snapshot/v3_snapshot_test.go
  tests/integration/tracing_test.go
  tests/integration/utl_wal_version_test.go
  tests/integration/v3_alarm_test.go
  tests/integration/v3_election_test.go
  tests/integration/v3_failover_test.go
  tests/integration/v3_grpc_inflight_test.go
  tests/integration/v3_kv_test.go
  tests/integration/v3_leadership_test.go
  tests/integration/v3_stm_test.go
  tests/integration/v3_watch_restore_test.go
  tests/integration/v3_watch_test.go
  tests/integration/v3election_grpc_test.go
  tests/integration/v3lock_grpc_test.go
Labels: area/testing, size/L, approved

#20095 chore(clientV3): address Go usetesting for clientV3
  client/v3/client_test.go
Labels: area/clientv3, size/XS, approved

#20089 chore(test): Re-enable usetesting linter
  tools/.golangci.yaml
Labels: area/tooling, size/XS, approved

#20063 [release-3.4] Add grpcproxy Makefile targets
  Makefile
  test
Labels: size/S, approved

#20099 [release-3.5] Remove static analysis workflow
  .github/workflows/static-analysis.yaml
Labels: size/M, approved, lgtm

#20096 CHANGELOG: add backport fix notes for #19577
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
  CHANGELOG/CHANGELOG-3.6.md
Labels: ok-to-test, size/XS, approved

#20100 Update `--discovery` related test cases to use v3discovery flags
  server/etcdmain/config_test.go
Labels: size/M, approved

#20111 Verify that the discovery endpoint isn't empty
  server/embed/config.go
  server/embed/config_test.go
Labels: approved, backport/v3.6

#20113 [release-3.6] Add validation to ensure that there is NO empty discovery endpoint
  server/embed/config.go
  server/embed/config_test.go
Labels: size/M, approved

#20109 Remove v2discovery
  etcdutl/go.mod
  etcdutl/go.sum
  server/config/config.go
  server/config/config_test.go
  server/embed/config.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/etcd.go
  server/etcdserver/api/v2discovery/discovery.go
  server/etcdserver/api/v2discovery/discovery_test.go
  server/etcdserver/bootstrap.go
  server/go.mod
  server/go.sum
  tests/framework/e2e/cluster.go
  tests/framework/e2e/cluster_test.go
  tests/framework/integration/cluster.go
  tests/go.mod
  tests/go.sum
  tests/integration/embed/embed_test.go
Labels: area/testing, area/etcdutl, size/XXL, approved

#20108 [2025-06-02] Manual Dependency Bump
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#20114 Update changelog to cover v2discovery and client/v2 removals
  CHANGELOG/CHANGELOG-3.6.md
  CHANGELOG/CHANGELOG-3.7.md
Labels: size/XS, approved

#20120 Update 'endpoint health' command to avoid calling `flags.SetPflagsFromEnv` multiple times
  etcdctl/ctlv3/command/ep_command.go
Labels: area/etcdctl, size/S, approved, backport/v3.6

#20128 [release-3.6] Bump Go to 1.23.9
  .go-version
  api/go.mod
  client/pkg/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
  tools/rw-heatmaps/go.mod
  tools/testgrid-analysis/go.mod
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/S, approved

#20124 Introduce Result struct to represent ternary result: success, failure unknown
  tests/antithesis/test-template/robustness/finally/main.go
  tests/robustness/validate/operations.go
  tests/robustness/validate/operations_test.go
  tests/robustness/validate/result.go
  tests/robustness/validate/validate.go
  tests/robustness/validate/validate_test.go
  tests/robustness/validate/watch.go
Labels: area/testing, area/robustness-testing, size/L, approved

#20134 CHANGELOG(3.6): Add Go 1.23.10 note
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#20135 CHANGELOG(3.6): Set v3.6.1 release date
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#20131 Ignore leases from failed requests greatly reducing linearization search space
  tests/robustness/model/deterministic.go
Labels: area/testing, area/robustness-testing, size/XS, approved

#20136 [release-3.4] Backport removing obsolete http 1.0 version for cmux tests
  tests/e2e/cmux_test.go
Labels: size/XS, approved

#20140 Add defragment support
  tests/antithesis/test-template/robustness/traffic/main.go
Labels: area/testing, size/M, approved

#20155 Update 3.6.2 changelog to cover bumping bbolt to 1.4.1
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#20156 [2025-06-09] Manual Dependency Bump
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/rw-heatmaps/go.mod
  tools/rw-heatmaps/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#20149 Add Kubernetes Traffic Type
  tests/antithesis/test-template/robustness/finally/main.go
  tests/antithesis/test-template/robustness/traffic/main.go
Labels: area/testing, size/M, approved

#20033 Update the Decision-making process and transparency
  GOVERNANCE.md
Labels: size/XS, approved

#20116 [release-3.4] .github/workflows: Remove tests.yaml
  .github/workflows/tests.yaml
Labels: size/M, approved, do-not-merge/hold

#20164 [release-3.5] Bump Go to 1.23.10
  .go-version
  api/go.mod
  client/pkg/go.mod
  client/v2/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  raft/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
Labels: ok-to-test, size/S, approved

#20166 [release-3.4] Bump Go to 1.23.10
  .go-version
  go.mod
  go.sum
  tools/mod/go.mod
Labels: ok-to-test, size/M, approved

#20174 CHANGELOG(3.4,3.5): Add Go 1.23.10 note
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test, size/XS, approved

#20172 [release-3.5] Add makefile target for run-govuluncheck
  Makefile
  test.sh
Labels: size/S, approved

#20177 etcdctl: refactor json printing to support custom writers
  etcdctl/ctlv3/command/printer_json.go
Labels: area/etcdctl, ok-to-test, size/S, approved

#20176 [Antithesis] Configuration for 1 node cluster
  tests/antithesis/Dockerfile.config
  tests/antithesis/Makefile
  tests/antithesis/docker-compose-1-node.yml
  tests/antithesis/docker-compose-3-node.yml
  tests/antithesis/test-template/Dockerfile
  tests/antithesis/test-template/entrypoint/main.go
  tests/antithesis/test-template/robustness/common/config.go
  tests/antithesis/test-template/robustness/common/path.go
  tests/antithesis/test-template/robustness/finally/main.go
  tests/antithesis/test-template/robustness/traffic/main.go
Labels: area/testing, size/L, approved

#20193 Treat future revision as client error
  tests/robustness/model/deterministic.go
  tests/robustness/model/history.go
Labels: area/testing, area/robustness-testing, size/S, approved

#19976 Add dry run instruction for release
  Documentation/contributor-guide/release.md
Labels: area/documentation, size/XS, approved

#20185 refactor: use slices.Contains to simplify code
  tools/proto-annotations/cmd/etcd_version.go
Labels: area/tooling, ok-to-test, size/XS, approved

#20175 Refactor recording client management
  tests/antithesis/test-template/robustness/traffic/main.go
  tests/robustness/client/client.go
  tests/robustness/client/watch.go
  tests/robustness/main_test.go
  tests/robustness/traffic/traffic.go
Labels: area/testing, area/robustness-testing, size/L, approved

#20151 Add support to generate JSON report to the benchmark tool
  etcdctl/ctlv3/command/check.go
  pkg/report/perfdash.go
  pkg/report/report.go
  pkg/report/report_test.go
  pkg/report/weighted.go
  tools/benchmark/cmd/lease.go
  tools/benchmark/cmd/mvcc-put.go
  tools/benchmark/cmd/put.go
  tools/benchmark/cmd/range.go
  tools/benchmark/cmd/root.go
  tools/benchmark/cmd/stm.go
  tools/benchmark/cmd/txn_mixed.go
  tools/benchmark/cmd/txn_put.go
  tools/benchmark/cmd/util.go
  tools/benchmark/cmd/watch.go
  tools/benchmark/cmd/watch_get.go
  tools/benchmark/cmd/watch_latency.go
Labels: area/performance, area/tooling, area/etcdctl, ok-to-test, size/L, approved

#20173 Refactor and add connect all client
  tests/antithesis/test-template/robustness/traffic/main.go
  tests/robustness/scenarios/scenarios.go
  tests/robustness/traffic/traffic.go
Labels: area/testing, area/robustness-testing, size/M, approved

#20216 Add single node cluster config to Antithesis tests in Github Actions
  .github/workflows/antithesis-test.yml
Labels: github_actions, size/XS, approved

#20215 Use security@etcd.io to receive any CVE report
  .github/ISSUE_TEMPLATE/bug-report.yml
  security/README.md
  security/email-templates.md
  security/security-release-process.md
Labels: area/security, size/S, approved

#20198 [release-3.5] Remove integration_extra from integration tests
  test.sh
Labels: size/XS, approved

#20219 [Antithesis] Fix building the client image
  .github/workflows/antithesis-test.yml
Labels: github_actions, size/S, approved

#20194 Add non-linearizable requests to visualization
  tests/robustness/validate/patch_history_test.go
  tests/robustness/validate/result.go
  tests/robustness/validate/validate.go
Labels: area/testing, area/robustness-testing, size/M, approved

#20229 Skip sending progress notification for watch with starting revision in the future
  server/etcdserver/api/v3rpc/watch.go
  server/storage/mvcc/watchable_store.go
  server/storage/mvcc/watcher_test.go
Labels: size/L, approved

#20195 Split model Step function
  tests/robustness/model/deterministic.go
Labels: area/testing, area/robustness-testing, size/L, approved

#20225 Add verification to verify the watch response have a bigger revision than minRev
  server/storage/mvcc/watchable_store.go
Labels: size/S, approved

#20236 .github/workflows: Remove grpcproxy.yaml from Github workflows
  .github/workflows/grpcproxy.yaml
Labels: size/M, approved

#20241 [release-3.6] Skip sending progress notification for watch with starting revision in the future
  server/etcdserver/api/v3rpc/watch.go
  server/storage/mvcc/watchable_store.go
  server/storage/mvcc/watcher_test.go
Labels: size/L, approved

#20240 Disable progress notify validation until we can guarantee response
  tests/robustness/client/watch.go
  tests/robustness/main_test.go
Labels: area/testing, area/robustness-testing, size/S, approved

#20246 [release-3.6] Disable progress notify validation until we can guarantee response
  tests/robustness/client/watch.go
  tests/robustness/main_test.go
Labels: area/testing, area/robustness-testing, size/S, approved
