Repository etcd-io/etcd, pull requests merged in 2025-03, with the labels that each got.

#19504 tests: deflakey TestLeaseGrantKeepAliveOnce
  tests/common/lease_test.go
Labels: area/testing, ok-to-test, size/S, approved

#19358 github workflows: remove release tests
  .github/workflows/release.yaml
Labels: stage/merge-when-tests-green, github_actions, size/M, approved

#19521 Fix the issue of etcdserver crashing on receiving REST watch stream requests
  api/etcdserverpb/gw/rpc.pb.gw.go
  api/go.mod
  api/go.sum
  client/internal/v2/go.mod
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/e2e/v3_curl_watch_test.go
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved, backport/v3.6

#19522 [3.6] Fix the issue of etcdserver crashing on receiving REST watch stream requests
  api/etcdserverpb/gw/rpc.pb.gw.go
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/e2e/v3_curl_watch_test.go
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19520 Add verify release assets GitHub workflow
  .github/workflows/verify-released-assets.yaml
Labels: github_actions, size/M, approved

#19532 Update CHANGELOGs with recent merged pull requests
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/S, approved

#19533 [3.4] Bump go toolchain to v1.23.7
  .go-version
  go.mod
  tools/mod/go.mod
Labels: size/XS

#19528 [3.5] Bump go toolchain to 1.23.7
  .go-version
  api/go.mod
  client/pkg/go.mod
  client/v2/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  raft/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
Labels: size/S, approved

#19527 [release-3.6] Bump go toolchain to 1.23.7
  .go-version
  api/go.mod
  client/internal/v2/go.mod
  client/pkg/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
  tools/rw-heatmaps/go.mod
  tools/testgrid-analysis/go.mod
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/S, approved

#19531 [release-3.6] dependency: bump golang.org/x/net from v0.34.0 to v0.36.0
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/M

#19530 [3.5] dependency: bump golang.org/x/net from v0.34.0 to v0.36.0
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/v2/go.mod
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  raft/go.mod
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: size/M

#19529 [3.4] dependency: bump golang.org/x/net from v0.34.0 to v0.36.0
  go.mod
  go.sum
Labels: size/XS

#19523 [2025-02-03] Manual Dependency Bump
  api/go.mod
  api/go.sum
  client/internal/v2/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19543 Update changelog with v3.5.19 v3.6.0-rc.2 release dates
  CHANGELOG/CHANGELOG-3.5.md
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/S, approved

#19440 Bump go toolchain to 1.24.1
  .go-version
  api/go.mod
  client/internal/v2/go.mod
  client/pkg/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  server/embed/config_test.go
  server/go.mod
  tests/go.mod
  tools/.golangci.yaml
  tools/mod/go.mod
  tools/rw-heatmaps/go.mod
  tools/testgrid-analysis/go.mod
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, stage/merge-when-tests-green, area/etcdutl, size/M, approved

#19547 [release-3.6] github workflows: remove release tests
  .github/workflows/release.yaml
Labels: stage/merge-when-tests-green, github_actions, size/M, approved

#19546 scripts/release: Use `go mod` instead of `go list`
  scripts/release_mod.sh
Labels: size/S, approved

#19552 Use clientPutCount instead of persistedPutCount as not all client requests are persisted
  tests/robustness/validate/patch_history.go
Labels: area/testing, area/robustness-testing, size/XS, approved

#19525 [release-3.5] back port gofail comments
  server/etcdserver/api/membership/cluster.go
  server/etcdserver/api/v3rpc/watch.go
  server/etcdserver/raft.go
  server/etcdserver/server.go
  server/mvcc/backend/backend.go
  server/mvcc/backend/batch_tx.go
  server/mvcc/kvstore.go
  server/mvcc/kvstore_compaction.go
Labels: ok-to-test, size/S, approved

#19555 server: remove ExperimentalMaxLearners
  server/embed/config.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
Labels: size/M, approved, backport/v3.6

#19554 fix: grpcproxy can get stuck in and endless loop causing high cpu usage
  server/proxy/grpcproxy/cluster.go
Labels: ok-to-test, size/XS, approved

#19573 [release-3.5/test] Update server unit test cases to set a backend
  server/etcdserver/server_test.go
Labels: size/S, approved

#19563 [release-3.5] Fix the learner promotion changes not being persisted into v3store (bbolt)
  server/etcdserver/api/membership/cluster.go
  server/etcdserver/api/membership/cluster_test.go
  server/etcdserver/api/membership/store.go
  server/etcdserver/server.go
  server/etcdserver/server_test.go
  server/verify/verify.go
  tests/e2e/ctl_v2_test.go
Labels: release/v3.5, size/M, approved

#19425 Tooling for markdown linting
  Makefile
  scripts/markdown_diff_lint.sh
  tools/.markdownlint.jsonc
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, github_actions, area/etcdutl, ok-to-test, size/L, approved

#19575 pkg: address Go 1.24 usetesting issues
  pkg/expect/expect_test.go
  pkg/netutil/netutil_test.go
  pkg/proxy/server_test.go
  pkg/traceutil/trace_test.go
Labels: size/S, approved

#19576 client/pkg: address Go 1.24 usetesting issues
  client/pkg/testutil/before.go
Labels: size/XS, approved

#19445 [3.5]: use RLock in Demoted method for read-only access to expiry
  server/lease/lessor.go
Labels: release/v3.5, ok-to-test, size/XS, approved

#19572 Nominate @fuweid as a new approver
  OWNERS
Labels: size/XS, approved

#19589 client: address Go 1.24 usetesting issues
  client/internal/v2/client_test.go
  client/internal/v2/keys_test.go
  client/internal/v2/members_test.go
  client/v3/client_test.go
  client/v3/credentials/credentials_test.go
  client/v3/ctx_test.go
  client/v3/ordering/kv_test.go
  client/v3/txn_test.go
  client/v3/watch_test.go
Labels: area/clientv3, size/L, approved

#19590 server: address Go 1.24 usetesting issues
  server/auth/jwt_test.go
  server/auth/simple_token_test.go
  server/auth/store_test.go
  server/embed/auth_test.go
  server/etcdserver/api/rafthttp/stream_test.go
  server/etcdserver/api/v3rpc/validationfuzz_test.go
  server/etcdserver/server_test.go
  server/etcdserver/txn/txn_test.go
  server/etcdserver/version/version_test.go
  server/lease/leasehttp/http_test.go
  server/storage/backend/hooks_test.go
  server/storage/mvcc/hash_test.go
  server/storage/mvcc/kv_test.go
  server/storage/mvcc/kvstore_bench_test.go
  server/storage/mvcc/kvstore_compaction_test.go
  server/storage/mvcc/kvstore_test.go
Labels: size/L, approved

#19602 [release-3.5] Fix the issue that learner promotion command doesn't support json output
  etcdctl/ctlv3/command/printer.go
  tests/e2e/ctl_v3_member_test.go
  tests/e2e/etcd_mix_versions_test.go
  tests/framework/e2e/cluster.go
  tests/framework/e2e/etcdctl.go
Labels: size/M, approved

#19603 Update 3.5 changelog to cover the member promotion command not suppor…
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#19591 etcdutl: address Go 1.24 usetesting issues
  etcdutl/snapshot/v3_snapshot_test.go
Labels: area/etcdutl, size/S, approved

#19592 tests/common: address Go 1.24 usetesting issues
  tests/common/alarm_test.go
  tests/common/auth_test.go
  tests/common/compact_test.go
  tests/common/defrag_test.go
  tests/common/endpoint_test.go
  tests/common/kv_test.go
  tests/common/lease_test.go
  tests/common/maintenance_auth_test.go
  tests/common/member_test.go
  tests/common/role_test.go
  tests/common/status_test.go
  tests/common/txn_test.go
  tests/common/user_test.go
  tests/common/wait_leader_test.go
  tests/common/watch_test.go
Labels: area/testing, size/L, approved

#19593 tests/e2e: address Go 1.24 usetesting issues
  tests/e2e/cluster_downgrade_test.go
  tests/e2e/cmux_test.go
  tests/e2e/corrupt_test.go
  tests/e2e/ctl_v3_auth_cluster_test.go
  tests/e2e/ctl_v3_auth_no_proxy_test.go
  tests/e2e/ctl_v3_grpc_test.go
  tests/e2e/ctl_v3_member_no_proxy_test.go
  tests/e2e/ctl_v3_member_test.go
  tests/e2e/ctl_v3_move_leader_test.go
  tests/e2e/ctl_v3_snapshot_test.go
  tests/e2e/ctl_v3_test.go
  tests/e2e/defrag_no_space_test.go
  tests/e2e/discovery_test.go
  tests/e2e/discovery_v3_test.go
  tests/e2e/etcd_config_test.go
  tests/e2e/etcd_grpcproxy_test.go
  tests/e2e/etcd_mix_versions_test.go
  tests/e2e/etcd_release_upgrade_test.go
  tests/e2e/failover_test.go
  tests/e2e/gateway_test.go
  tests/e2e/graceful_shutdown_test.go
  tests/e2e/hashkv_test.go
  tests/e2e/http_health_check_test.go
  tests/e2e/leader_snapshot_no_proxy_test.go
  tests/e2e/logging_test.go
  tests/e2e/metrics_test.go
  tests/e2e/promote_experimental_flag_test.go
  tests/e2e/reproduce_17780_test.go
  tests/e2e/runtime_reconfiguration_test.go
  tests/e2e/utl_migrate_test.go
  tests/e2e/v2store_deprecation_test.go
  tests/e2e/v3_curl_maxstream_test.go
  tests/e2e/v3_curl_watch_test.go
  tests/e2e/v3_lease_no_proxy_test.go
  tests/e2e/watch_test.go
  tests/e2e/zap_logging_test.go
Labels: area/testing, size/L, approved

#19595 tests/framework: address Go 1.24 usetesting issues
  tests/framework/e2e/cluster.go
  tests/framework/e2e/downgrade.go
  tests/framework/e2e/etcd_process.go
  tests/framework/integration/cluster.go
  tests/framework/testutils/execute.go
  tests/framework/testutils/log_observer_test.go
Labels: area/testing, size/S, approved

#19582 Bump devcontainer version to 1.24
  .devcontainer/devcontainer.json
Labels: size/XS, approved

#19609 Update the robustness test README
  tests/robustness/README.md
Labels: area/testing, area/robustness-testing, size/M, approved

#19610 Fix wrong error message in `loadKeyValueOperations`
  tests/robustness/report/client.go
Labels: area/testing, area/robustness-testing, size/S, approved

#19594 test/robustness: rename makefile.mk to Makefile
  Makefile
  tests/robustness/Makefile
Labels: area/testing, area/robustness-testing, size/M, approved

#19585 [2025-02-10] Manual Dependency Bump
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/rw-heatmaps/go.mod
  tools/rw-heatmaps/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/XL, approved

#19632 [2025-03-17] Manual Dependency Bump
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19625 doc: update feature development guide.
  Documentation/contributor-guide/features.md
Labels: area/documentation, size/M, approved

#19637 minor refactor DowngradeUpgradeMembersByID to not block on waiting fo…
  tests/framework/e2e/downgrade.go
Labels: area/testing, size/S, approved, backport/v3.6

#19638 [release-3.6] minor refactor DowngradeUpgradeMembersByID to not block on waiting fo…
  tests/framework/e2e/downgrade.go
Labels: area/testing, size/S, approved

#19640 Returns the string representation of the `ClusterVersion`
  tests/framework/e2e/config.go
Labels: area/testing, size/XS, approved, backport/v3.6

#19641 [release-3.6] Returns the string representation of the `ClusterVersion`
  tests/framework/e2e/config.go
Labels: area/testing, size/XS, approved

#19631 Split `scripts/test_lib.sh`
  scripts/markdown_diff_lint.sh
  scripts/test_lib.sh
  scripts/test_utils.sh
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, ok-to-test, size/L, approved

#19639 CHANGELOG-3.5: Set v3.5.20 release date
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/S, approved

#19636 [release-3.6] Auto sync members in v3store is IsLearner differs between v2 and v3 store
  server/etcdserver/api/membership/cluster.go
  server/etcdserver/api/membership/cluster_test.go
  server/etcdserver/api/membership/membership_test.go
  server/etcdserver/api/membership/store.go
  server/etcdserver/bootstrap.go
  server/storage/backend/verify.go
  server/storage/schema/membership.go
  tests/e2e/ctl_v3_member_test.go
  tests/go.mod
Labels: area/testing, size/L, approved

#19650 Update 3.6 changelog for the fix to auto sync member in v3store
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#19634 e2e: add upgrade test for clusters set up by promoted members
  tests/e2e/etcd_release_upgrade_test.go
Labels: area/testing, size/L, approved, backport/v3.6

#19647 [release-3.6] dependency: bump github.com/golang-jwt/jwt/v5 from 5.2.1 to 5.2.2
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
Labels: area/testing, area/etcdutl, size/S, approved

#19646 [release-3.5] dependency: bump github.com/golang-jwt/jwt/v4 from 4.5.1 to 4.5.2
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
Labels: size/M, approved

#19616 chore: use testify instead of testing in tests/integration
  tests/integration/clientv3/concurrency/election_test.go
  tests/integration/clientv3/connectivity/black_hole_test.go
  tests/integration/clientv3/connectivity/dial_test.go
  tests/integration/clientv3/connectivity/network_partition_test.go
  tests/integration/clientv3/experimental/recipes/v3_barrier_test.go
  tests/integration/clientv3/experimental/recipes/v3_double_barrier_test.go
  tests/integration/clientv3/experimental/recipes/v3_lock_test.go
  tests/integration/clientv3/experimental/recipes/v3_queue_test.go
  tests/integration/clientv3/lease/lease_test.go
  tests/integration/clientv3/lease/leasing_test.go
  tests/integration/clientv3/naming/endpoints_test.go
  tests/integration/clientv3/naming/resolver_test.go
  tests/integration/clientv3/ordering_util_test.go
  tests/integration/clientv3/snapshot/v3_snapshot_test.go
  tests/integration/clientv3/user_test.go
  tests/integration/clientv3/watch_fragment_test.go
  tests/integration/clientv3/watch_test.go
  tests/integration/cluster_test.go
  tests/integration/member_test.go
  tests/integration/metrics_test.go
  tests/integration/network_partition_test.go
  tests/integration/proxy/grpcproxy/cluster_test.go
  tests/integration/proxy/grpcproxy/kv_test.go
  tests/integration/proxy/grpcproxy/register_test.go
  tests/integration/revision_test.go
  tests/integration/snapshot/member_test.go
  tests/integration/snapshot/v3_snapshot_test.go
  tests/integration/v2store/store_test.go
  tests/integration/v3_alarm_test.go
  tests/integration/v3_auth_test.go
  tests/integration/v3_election_test.go
  tests/integration/v3_failover_test.go
  tests/integration/v3_grpc_test.go
Labels: area/testing, size/XXL, approved

#19662 [3.6] e2e: add upgrade test for clusters set up by promoted members
  tests/e2e/etcd_release_upgrade_test.go
Labels: area/testing, size/M, approved

#19599 development: fix 'make verify' errors in OSX
  scripts/test.sh
Labels: area/documentation, ok-to-test, size/S, approved

#19651 Patch the return time with MaxInt64 in robustness test
  tests/robustness/model/history.go
  tests/robustness/validate/patch_history.go
  tests/robustness/validate/patch_history_test.go
Labels: area/testing, area/robustness-testing, size/M, approved

#19668 [Robustness test] Improve append history checks
  tests/robustness/model/history.go
  tests/robustness/model/history_test.go
Labels: area/testing, area/robustness-testing, size/L, approved

#19673 [release-3.6] Move client/internal/v2 into server/internal/clientv2
  bill-of-materials.json
  client/internal/v2/LICENSE
  client/internal/v2/go.mod
  client/internal/v2/go.sum
  codecov.yml
  dummy.go
  etcdutl/go.mod
  go.mod
  scripts/release_mod.sh
  scripts/test_lib.sh
  server/etcdserver/api/v2discovery/discovery.go
  server/etcdserver/api/v2discovery/discovery_test.go
  server/go.mod
  server/internal/clientv2/README.md
  server/internal/clientv2/auth_role.go
  server/internal/clientv2/auth_user.go
  server/internal/clientv2/cancelreq.go
  server/internal/clientv2/client.go
  server/internal/clientv2/client_test.go
  server/internal/clientv2/cluster_error.go
  server/internal/clientv2/curl.go
  server/internal/clientv2/discover.go
  server/internal/clientv2/doc.go
  server/internal/clientv2/fake_transport_test.go
  server/internal/clientv2/keys.go
  server/internal/clientv2/keys_bench_test.go
  server/internal/clientv2/keys_test.go
  server/internal/clientv2/main_test.go
  server/internal/clientv2/members.go
  server/internal/clientv2/members_test.go
  server/internal/clientv2/util.go
  tests/go.mod
  tests/go.sum
Labels: area/testing, area/etcdutl, size/L, approved

#19672 Update 3.6 changelog to cover the revert client/v2 change
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#19676 codecov: set commit sha for merges
  scripts/codecov_upload.sh
Labels: size/XS, approved

#19679 Pass a non-infinite returnTime in history patching tests
  tests/robustness/validate/patch_history_test.go
Labels: area/testing, area/robustness-testing, size/M, approved

#19669 [Robustness test] Preserve return time for failed requests
  tests/robustness/model/history.go
  tests/robustness/validate/operations.go
  tests/robustness/validate/patch_history.go
  tests/robustness/validate/patch_history_test.go
  tests/robustness/validate/validate.go
Labels: area/testing, area/robustness-testing, size/M, approved

#19677 [2025-03-24] Manual Dependency Bump
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19683 [release-3.6] bump golang.org/x/net to v0.37.0 to address CVE-2025-22870
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/rw-heatmaps/go.mod
  tools/rw-heatmaps/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19687 [release-3.6] dependency: bump golang.org/x/net from v0.37.0 to v0.38.0
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, stage/merge-when-tests-green, area/etcdutl, size/M, approved

#19686 [release-3.5] dependency: bump golang.org/x/net from v0.36.0 to v0.38.0
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: size/L, approved

#19690 remove CHANGELOG directory
  CHANGELOG/CHANGELOG-2.3.md
  CHANGELOG/CHANGELOG-3.0.md
  CHANGELOG/CHANGELOG-3.1.md
  CHANGELOG/CHANGELOG-3.2.md
  CHANGELOG/CHANGELOG-3.3.md
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
  CHANGELOG/CHANGELOG-3.6.md
  CHANGELOG/CHANGELOG-4.0.md
  CHANGELOG/README.md
Labels: ok-to-test, size/XXL, approved

#19688 CHANGELOG: Add missing entries in v3.6.0-rc.3 and v3.5.21
  CHANGELOG/CHANGELOG-3.5.md
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/S, approved

#19155 chore: enable unnecessary-stmt rule from revive
  client/pkg/types/urls.go
  server/etcdmain/etcd.go
  server/storage/wal/repair.go
  tools/.golangci.yaml
Labels: area/tooling, size/S, approved

#19680 [Robustness Test] Add HashKV check to robustness test
  tests/robustness/client/kvhash.go
  tests/robustness/main_test.go
Labels: area/testing, area/robustness-testing, size/M, approved
