Repository etcd-io/etcd, pull requests merged in 2025-04, with the labels that each got.

#19694 Switch to validating v3 when v2 and v3 are synchronized
  server/etcdserver/api/membership/cluster.go
  server/etcdserver/api/membership/cluster_test.go
  server/etcdserver/server.go
  tests/e2e/metrics_test.go
Labels: area/testing, size/S, approved, backport/v3.6

#19708 Update 3.6 changelog to cover the membership validation update
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#19709 [2025-04-04] Manual Dependency Bump
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/M, approved

#19666 markdown lint job: set ETCD_ROOT_DIR to root directory of git repository
  scripts/markdown_diff_lint.sh
  tools/.markdownlint.jsonc
Labels: area/testing, area/tooling, github_actions, ok-to-test, size/S, approved

#19725 [release-3.5] Bump Go to 1.23.8
  .go-version
  api/go.mod
  client/pkg/go.mod
  client/v2/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  raft/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
Labels: size/S, approved

#19726 [release-3.4] Bump Go to 1.23.8
  .go-version
  auth/jwt.go
  auth/jwt_test.go
  auth/options.go
  bill-of-materials.json
  go.mod
  go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: size/M, approved

#19724 [release-3.6] Bump Go to 1.23.8
  .go-version
  api/go.mod
  client/pkg/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
  tools/rw-heatmaps/go.mod
  tools/testgrid-analysis/go.mod
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/S, approved

#19723 [main] Bump Go to 1.24.2
  .go-version
  api/go.mod
  client/internal/v2/go.mod
  client/pkg/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
  tools/rw-heatmaps/go.mod
  tools/testgrid-analysis/go.mod
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/S, approved

#19729 [2025-04-08] Bump dependency updates identified by dependabot
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/rw-heatmaps/go.mod
  tools/rw-heatmaps/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19730 [release-3.6] add verification to check whether membership data is in sync between …
  server/etcdserver/api/membership/cluster.go
  server/etcdserver/server.go
Labels: size/M, approved

#19728 Update release note for bumping Go to 1.23.8/1.24.2
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
  CHANGELOG/CHANGELOG-3.6.md
  CHANGELOG/CHANGELOG-3.7.md
Labels: size/S, approved

#19733 [Robustness] Improve HashKV check comments
  tests/robustness/client/kvhash.go
  tests/robustness/main_test.go
Labels: area/testing, area/robustness-testing, size/XS, approved

#19681 Merge operation categorization into one function
  tests/robustness/validate/patch_history_test.go
  tests/robustness/validate/validate.go
Labels: area/testing, area/robustness-testing, size/M, approved

#19735 Remove required headings rule in markdown checker
  tools/.markdownlint.jsonc
Labels: area/tooling, ok-to-test, size/XS, approved

#19738 K8s bump etcd version guide
  Documentation/contributor-guide/bump_etcd_version_k8s.md
Labels: area/documentation, ok-to-test, size/XS, approved

#19739 Antithesis Integration: Move Antithesis demo to etcd repo
  tests/antithesis/Dockerfile.config
  tests/antithesis/README.md
  tests/antithesis/docker-compose.yaml
  tests/antithesis/test-template/Dockerfile.client
  tests/antithesis/test-template/entrypoint/entrypoint.py
Labels: area/testing, ok-to-test, size/L, approved

#19749 CHANGELOG: update items with release date
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#19755 CHAGELOG-3.6: Remove `etcdutl snapshot save` removal note
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#19763 [Robustness Test] Fix Dockerfile.config
  tests/antithesis/Dockerfile.config
Labels: area/testing, size/XS, approved

#19764 [Rubustness Test] Rename suffix yaml to yml
  tests/antithesis/Dockerfile.config
  tests/antithesis/docker-compose.yml
Labels: area/testing, github_actions, size/XS, approved

#19765 Create Go client for robustness test foundation with etcd health checks
  tests/antithesis/test-template/Dockerfile.client
  tests/antithesis/test-template/go-delete-keys/go.mod
  tests/antithesis/test-template/go-delete-keys/go.sum
  tests/antithesis/test-template/go-delete-keys/serial_driver_delete_keys.go
Labels: area/testing, ok-to-test, size/L, approved

#19767 Add Antithesis package imports
  tests/antithesis/test-template/go-delete-keys/go.mod
  tests/antithesis/test-template/go-delete-keys/go.sum
  tests/antithesis/test-template/go-delete-keys/serial_driver_delete_keys.go
Labels: area/testing, size/M, approved

#19762 emit compaction pause duration metric in every compaction batch
  server/storage/mvcc/kvstore_compaction.go
Labels: ok-to-test, size/XS, approved

#19757 chore: fix testifylint new issues
  server/etcdserver/api/v2store/store_ttl_test.go
  tests/e2e/v2store_deprecation_test.go
  tools/etcd-dump-logs/etcd-dump-log_test.go
Labels: area/testing, area/tooling, size/XS, approved

#19030 Add rw benchmark line chart
  tools/rw-heatmaps/cmd/root.go
  tools/rw-heatmaps/pkg/chart/line_chart.go
Labels: area/performance, area/tooling, size/L, approved

#19779 Catch ErrSliceOutOfRange error
  tests/robustness/report/wal.go
Labels: area/testing, area/robustness-testing, needs-ok-to-test, size/XS, approved

#19271 chore: enable thelper linter
  server/etcdserver/api/membership/cluster_test.go
  server/etcdserver/server_test.go
  server/lease/lessor_bench_test.go
  server/storage/backend/batch_tx_test.go
  server/storage/backend/hooks_test.go
  server/storage/backend/testing/betesting.go
  server/storage/wal/testing/waltesting.go
  tests/e2e/utils.go
  tests/e2e/v2store_deprecation_test.go
  tests/framework/e2e/cluster.go
  tests/framework/e2e/cluster_direct.go
  tests/framework/e2e/e2e.go
  tests/framework/e2e/etcd_process.go
  tests/framework/e2e/testing.go
  tests/framework/e2e/util.go
  tests/framework/integration/cluster.go
  tests/framework/integration/integration.go
  tests/framework/integration/testing.go
  tests/framework/unit/unit.go
  tests/integration/v3_leadership_test.go
  tools/.golangci.yaml
Labels: area/testing, area/tooling, size/L, approved

#19790 [Robustness test] Merge Antithesis Github workflows
  .github/workflows/antithesis-test.yml
Labels: github_actions, size/S, approved

#19794 Change <hr> occurrences to `---` in Markdown files
  CHANGELOG/CHANGELOG-2.3.md
  CHANGELOG/CHANGELOG-3.0.md
  CHANGELOG/CHANGELOG-3.1.md
  CHANGELOG/CHANGELOG-3.2.md
  CHANGELOG/CHANGELOG-3.3.md
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
  CHANGELOG/CHANGELOG-3.6.md
  CHANGELOG/CHANGELOG-3.7.md
  CHANGELOG/CHANGELOG-4.0.md
  tools/.markdownlint.jsonc
Labels: area/tooling, ok-to-test, size/L, approved

#19781 Antithesis Integration: Convert entrypoint from python to Go
  tests/antithesis/docker-compose.yml
  tests/antithesis/test-template/Dockerfile.client
  tests/antithesis/test-template/entrypoint/entrypoint.go
  tests/antithesis/test-template/entrypoint/entrypoint.py
  tests/antithesis/test-template/entrypoint/go.mod
  tests/antithesis/test-template/entrypoint/go.sum
Labels: area/testing, area/robustness-testing, ok-to-test, size/L, approved

#19608 Add e2e test to reproduce issue #19406
  server/storage/mvcc/kvstore_compaction.go
  tests/e2e/metrics_test.go
  tests/e2e/reproduce_19406_test.go
  tests/framework/e2e/metrics.go
Labels: area/testing, ok-to-test, size/L, approved

#19807 Extract ensureTrace function
  server/etcdserver/txn/txn.go
Labels: size/M, approved

#19810 [release-3.4] Add run-govulncheck Makefile target
  Makefile
  test
Labels: ok-to-test, size/S, approved

#19792 [2025-04-24] Manual Dependency Bump
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  client/v3/internal/resolver/resolver.go
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, github_actions, area/robustness-testing, area/etcdutl, ok-to-test, size/M, approved

#19803 pkg/featuregate: Return MutableFeatureGate interface in New function
  pkg/featuregate/feature_gate.go
  pkg/featuregate/feature_gate_test.go
Labels: size/XS, approved

#19814 docs: update v3.6.0 roadmap
  Documentation/contributor-guide/roadmap.md
Labels: area/documentation, ok-to-test, size/XS, approved, lgtm

#19820 [Antithesis] Fix lint and rename Dockerfile
  tests/antithesis/README.md
  tests/antithesis/test-template/Dockerfile
  tests/antithesis/test-template/entrypoint/entrypoint.go
  tests/antithesis/test-template/go-delete-keys/serial_driver_delete_keys.go
Labels: area/testing, ok-to-test, size/M, approved

#19801 adt: add tests for IntervalTree.Find()
  pkg/adt/interval_tree_test.go
Labels: ok-to-test, size/M, approved

#19748 fix(server/etcdserver/api/v3compactor): fix flaky TestPeriodicHourly and others with Retry Mechanism
  server/etcdserver/api/v3compactor/periodic_test.go
Labels: ok-to-test, size/M, approved

#19797 Consolidate to tests's go.mod
  .github/workflows/antithesis-test.yml
  bill-of-materials.json
  tests/antithesis/Makefile
  tests/antithesis/test-template/Dockerfile
  tests/antithesis/test-template/entrypoint/entrypoint.go
  tests/antithesis/test-template/entrypoint/go.mod
  tests/antithesis/test-template/entrypoint/go.sum
  tests/antithesis/test-template/go-delete-keys/go.mod
  tests/antithesis/test-template/go-delete-keys/go.sum
  tests/antithesis/test-template/go-delete-keys/serial_driver_delete_keys.go
  tests/go.mod
  tests/go.sum
Labels: area/testing, area/tooling, github_actions, ok-to-test, size/L, approved

#19824 Fix antithesis docker file removing distroless layer.
  tests/antithesis/Makefile
  tests/antithesis/README.md
  tests/antithesis/test-template/Dockerfile
Labels: area/testing, size/S, approved

#19811 Refactor checking put request
  server/etcdserver/txn/txn.go
Labels: size/L, approved

#19813 Simplify apply by handling membership apply through the same applyV3 stack
  server/etcdserver/apply/apply.go
  server/etcdserver/apply/apply_auth.go
  server/etcdserver/apply/apply_auth_test.go
  server/etcdserver/apply/uber_applier.go
  server/etcdserver/apply/uber_applier_test.go
  server/etcdserver/server.go
  server/etcdserver/server_test.go
Labels: size/L, approved

#19826 Split other methods in txn into separate files
  server/etcdserver/txn/delete.go
  server/etcdserver/txn/put.go
  server/etcdserver/txn/range.go
  server/etcdserver/txn/txn.go
Labels: size/XL, approved

#19834 Antithesis: Use RecordingClient from robustness tests
  tests/antithesis/test-template/go-delete-keys/serial_driver_delete_keys.go
Labels: area/testing, ok-to-test, size/S, approved

#19837 Update changelog to include fix for compaction pause duration metric
  CHANGELOG/CHANGELOG-3.5.md
  CHANGELOG/CHANGELOG-3.6.md
Labels: ok-to-test, size/XS, approved

#19825 chore(client/v3/naming): deprecate Metadata field in Endpoint struct
  client/v3/naming/endpoints/endpoints.go
Labels: area/clientv3, ok-to-test, size/XS, approved

#19836 make: upload partial coverage reports
  Makefile
Labels: size/XS, approved

#19815 Add test-release-tests Makefile target
  Makefile
  scripts/test.sh
Labels: ok-to-test, size/S, approved
