Repository etcd-io/etcd, pull requests merged in 2025-02, with the labels that each got.

#19319 *: introduce (*Op) Limit() interface for robustness
  client/v3/op.go
  tests/robustness/client/client.go
Labels: area/testing, area/clientv3, area/robustness-testing, size/XS, approved

#19317 Remove some HealthInterval to reduce the time to run DowngradeUpgradeMembers
  tests/framework/e2e/downgrade.go
  tests/robustness/failpoint/cluster.go
Labels: area/testing, area/robustness-testing, size/XS, approved

#19282 migrate experimental-memory-mlock flag to memory-mlock
  server/config/config.go
  server/embed/config.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
  server/storage/backend.go
Labels: ok-to-test, size/L, approved, lgtm

#19325 fix test.sh to download correct binary for mac os
  scripts/test.sh
Labels: ok-to-test, size/XS, approved

#19326 fileutil: removes redundant continue statement in RemoveMatchFile
  client/pkg/fileutil/fileutil.go
Labels: ok-to-test, size/XS, approved

#19330 [3.5] Add more info into log for learner member operations
  server/etcdserver/api/membership/cluster.go
Labels: size/XS, approved

#19329 Add learner id into log when being promoted
  server/etcdserver/api/membership/cluster.go
Labels: size/XS, approved

#19331 CHANGELOG(3.5): Add entry for #19280
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#19252 Add downgrade cancellation e2e tests
  tests/e2e/cluster_downgrade_test.go
  tests/framework/e2e/downgrade.go
Labels: area/testing, area/etcdctl, area/robustness-testing, size/L, approved

#19254 Align NewConfig with AddFlags defaults
  server/embed/config.go
  server/embed/config_test.go
Labels: size/M, approved

#19337 [3.4] Update golang toolchain to 1.22.12
  .go-version
  go.mod
  tools/mod/go.mod
Labels: ok-to-test, size/XS, approved

#19332 chore: use testify instead of testing in tests/integration
  tests/integration/clientv3/cluster_test.go
  tests/integration/clientv3/concurrency/mutex_test.go
  tests/integration/clientv3/concurrency/session_test.go
  tests/integration/clientv3/connectivity/black_hole_test.go
  tests/integration/clientv3/connectivity/dial_test.go
  tests/integration/clientv3/connectivity/network_partition_test.go
  tests/integration/clientv3/connectivity/server_shutdown_test.go
  tests/integration/clientv3/experimental/recipes/v3_double_barrier_test.go
  tests/integration/clientv3/experimental/recipes/v3_lock_test.go
  tests/integration/clientv3/kv_test.go
  tests/integration/clientv3/lease/lease_test.go
  tests/integration/clientv3/lease/leasing_test.go
  tests/integration/clientv3/maintenance_test.go
  tests/integration/clientv3/metrics_test.go
  tests/integration/clientv3/mirror_auth_test.go
  tests/integration/clientv3/mirror_test.go
  tests/integration/clientv3/namespace_test.go
  tests/integration/clientv3/ordering_kv_test.go
  tests/integration/clientv3/ordering_util_test.go
  tests/integration/clientv3/txn_test.go
  tests/integration/clientv3/user_test.go
  tests/integration/clientv3/watch_test.go
  tests/integration/metrics_test.go
  tests/integration/v3_alarm_test.go
  tests/integration/v3_auth_test.go
  tests/integration/v3_election_test.go
  tests/integration/v3_grpc_test.go
  tests/integration/v3_lease_test.go
  tests/integration/v3_watch_test.go
  tests/integration/v3election_grpc_test.go
  tests/integration/v3lock_grpc_test.go
Labels: area/testing, size/XXL, approved

#19336 [3.5] Update golang toolchain to 1.22.12
  .go-version
  api/go.mod
  client/pkg/go.mod
  client/v2/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  raft/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
Labels: ok-to-test, size/S

#19335 Update golang toolchain to 1.23.6
  .go-version
  api/go.mod
  client/internal/v2/go.mod
  client/pkg/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
  tools/rw-heatmaps/go.mod
  tools/testgrid-analysis/go.mod
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, ok-to-test, size/S, approved

#19346 [2025-02-05] Bump dependency updates identified by dependabot
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/rw-heatmaps/go.mod
  tools/rw-heatmaps/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/performance, area/testing, area/tooling, area/etcdctl, area/etcdutl, size/M, approved

#19349 Bump bbolt to v1.4.0 and raft to v3.6.0
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: area/testing, area/tooling, area/etcdutl, size/M, approved

#19338 changelog: update GO entry to reflect 1.22.12 update
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test, size/XS, approved

#19348 increase timeout for MemberDowngradeUpgrade test
  tests/robustness/failpoint/cluster.go
  tests/robustness/failpoint/failpoint.go
Labels: area/testing, area/robustness-testing, ok-to-test, size/S, approved

#19328 migrate experimental-downgrade-checktime to downgrade-checktime
  server/embed/config.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
Labels: ok-to-test, size/M, approved

#19353 test: update robustness doc and new case to reproduce 19179
  tests/robustness/README.md
  tests/robustness/makefile.mk
  tests/robustness/scenarios/scenarios.go
  tests/robustness/traffic/kubernetes.go
  tests/robustness/traffic/traffic.go
Labels: area/testing, area/robustness-testing, size/L, approved, lgtm

#19351 migrate experimental-compaction-sleep-interval flag to compaction-sleep interval
  server/embed/config.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
Labels: ok-to-test, size/M, approved

#19052 server: fix unexported-return lint issue
  server/auth/store.go
  server/auth/store_test.go
  server/etcdserver/adapters.go
  server/storage/mvcc/kvstore.go
  server/storage/mvcc/watchable_store.go
  server/storage/mvcc/watchable_store_test.go
  server/storage/schema/auth.go
Labels: ok-to-test, size/M, approved

#19356 migrate experimental-enable-lease-checkpoint and experimental-enable-lease-checkpoint-persist flag to feature gate.
  server/config/config.go
  server/embed/config.go
  server/embed/config_test.go
  server/embed/etcd.go
  server/etcdmain/help.go
  server/etcdserver/server.go
  server/features/etcd_features.go
  tests/framework/integration/cluster.go
Labels: area/testing, size/L, approved

#19344 etcdutl: use map to count unique user keys in snapshot status
  etcdutl/snapshot/v3_snapshot.go
  etcdutl/snapshot/v3_snapshot_test.go
  server/storage/mvcc/revision.go
  tests/e2e/ctl_v3_auth_test.go
  tests/e2e/ctl_v3_snapshot_test.go
Labels: area/testing, area/etcdutl, ok-to-test, size/L, approved

#19359 Add more debug info into waitTillSnapshot
  tests/robustness/failpoint/network.go
Labels: area/testing, area/robustness-testing, size/XS, approved

#19361 Update 3.6 changelog to cover the etcdutl status command change
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#19362 migrate experimental-peer-skip-client-san-verification flag to peer-skip-client-san-verification
  server/embed/config.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
Labels: size/L, approved

#19367 Fix a log formatting bug in the e2e downgrade tests
  tests/e2e/cluster_downgrade_test.go
  tests/framework/e2e/downgrade.go
Labels: area/testing, size/XS, approved

#19369 [3.4]Fix(ci): upgrade artifact actions to v4
  .github/workflows/release.yaml
Labels: ok-to-test, size/XS, approved

#19350 Migrate WALVersion to fix unexported-return of walVersion
  etcdutl/etcdutl/migrate_command.go
  server/storage/schema/schema.go
  server/storage/wal/version.go
Labels: area/etcdutl, ok-to-test, size/S, approved

#19385 Migrate experimental distributed tracing flags to non-experimental flags
  server/config/config.go
  server/embed/config.go
  server/embed/config_tracing.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
  server/etcdserver/api/v3rpc/grpc.go
  tests/integration/tracing_test.go
Labels: area/testing, size/XL, approved

#19352 migrate experimental-snapshot-catchup-entries flag to snapshot-catchup-entries
  server/embed/config.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
  tests/framework/e2e/cluster.go
  tests/framework/e2e/cluster_test.go
  tests/framework/e2e/etcd_process.go
Labels: area/testing, ok-to-test, size/L

#19388 Minor refacotr on the e2e test framework
  tests/framework/e2e/cluster.go
  tests/framework/e2e/cluster_test.go
  tests/framework/e2e/etcd_process.go
Labels: area/testing, size/M, approved

#19386 CHANGELOG-3.4: Add entry from #19197
  CHANGELOG/CHANGELOG-3.4.md
Labels: size/XS, approved

#19370 Remove passing of anonymous visualize function
  bill-of-materials.json
  tests/go.mod
  tests/go.sum
  tests/robustness/main_test.go
  tests/robustness/validate/operations.go
  tests/robustness/validate/validate.go
  tests/robustness/validate/validate_test.go
Labels: area/testing, area/robustness-testing, ok-to-test, size/M, approved

#19398 [test] Correct the expected version in downgrade test case
  tests/framework/e2e/downgrade.go
Labels: area/testing, size/S, approved

#19403 server: Remove deprecated NewZapCoreLoggerBuilder
  server/embed/config_logging.go
Labels: size/XS, approved

#19407 CHANGELOG-3.6: Add note from #19404
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#19410 Fix a performance regression due to uncertain compaction sleep interval
  server/storage/mvcc/kvstore_compaction.go
Labels: size/XS, approved

#19412 Add the fix of the performance regression due to uncertain compaction…
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#19405 [release-3.5] Fix a performance regression due to uncertain compaction sleep interval
  server/mvcc/kvstore_compaction.go
Labels: ok-to-test, size/XS, approved

#19413 Migrate --experimental-set-member-localaddr to using feature flag
  CHANGELOG/CHANGELOG-3.6.md
  server/embed/config.go
  server/embed/config_test.go
  server/embed/etcd.go
  server/etcdmain/help.go
  server/features/etcd_features.go
  tests/e2e/etcd_config_test.go
Labels: area/testing, size/M, approved

#19418 Fix release script prerelease GitHub template release
  scripts/release.sh
Labels: size/XS, approved

#19422 github/workflows: remove fuzzing workflow.
  .github/workflows/fuzzing.yaml
Labels: github_actions, size/S, approved

#19421 github/workflows: remove contrib workflow
  .github/workflows/contrib.yaml
Labels: github_actions, size/S, approved

#19432 perf: use RLock in Demoted method for read-only access to expiry
  server/lease/lease.go
Labels: ok-to-test, size/XS, approved

#19342 Move interface `AlarmBackend` from `server/etcdserver/api/v3alarm` to `server/storage/schema` to fix the `unexported-return` lint error
  server/etcdserver/api/v3alarm/alarms.go
  server/storage/schema/alarm.go
Labels: ok-to-test, size/S, approved, backport/v3.6

#19430 [3.5] Update golang toolchain to 1.23.6
  .go-version
  api/go.mod
  client/pkg/go.mod
  client/v2/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  raft/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
Labels: area/performance, area/documentation, area/testing, area/clientv3, area/tooling, area/etcdctl, github_actions, area/etcdutl, ok-to-test, area/observability, size/M, approved

#19429 [3.4] Update golang toolchain to 1.23.6
  .go-version
  go.mod
  tools/mod/go.mod
Labels: stage/merge-when-tests-green, ok-to-test, size/S, approved

#19431 Update CHANGELOG for version bump to go 1.23.6
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test, size/XS, approved

#19450 Simplify release permissions process
  Documentation/contributor-guide/release.md
Labels: area/documentation, size/S, approved

#19341 Rename `storageRecorder` to `StorageRecorder` to fix `unexported-return` lint error
  server/mock/mockstorage/storage_recorder.go
Labels: ok-to-test, size/S, approved

#19340 Rename `applierMembership` to `ApplierMembership` to fix the `unexported-return` lint error
  server/etcdserver/apply/apply.go
Labels: ok-to-test, size/S, approved

#19451 *: support DowngradeInfo field in maintenence.Status API
  Documentation/dev-guide/apispec/swagger/rpc.swagger.json
  api/etcdserverpb/rpc.pb.go
  api/etcdserverpb/rpc.proto
  etcdctl/ctlv3/command/printer.go
  etcdctl/ctlv3/command/printer_fields.go
  scripts/etcd_version_annotations.txt
  server/etcdserver/api/v3rpc/maintenance.go
  tests/e2e/cluster_downgrade_test.go
  tests/framework/e2e/downgrade.go
  tests/robustness/failpoint/cluster.go
Labels: area/documentation, area/testing, area/etcdctl, area/robustness-testing, size/XXL, approved

#19461 deflake: TestDowngradeCancellationAfterDowngrading1InClusterOf3
  tests/e2e/cluster_downgrade_test.go
  tests/framework/e2e/cluster.go
  tests/framework/e2e/downgrade.go
  tests/robustness/failpoint/cluster.go
Labels: area/testing, stage/merge-when-tests-green, area/robustness-testing, size/M, approved

#19446 etcdserver: Update description for count field in the RangeResponse message
  Documentation/dev-guide/apispec/swagger/rpc.swagger.json
  api/etcdserverpb/rpc.pb.go
  api/etcdserverpb/rpc.proto
Labels: area/documentation, ok-to-test, size/S, approved

#19471 [3.6] Backport DowngradeInfo proto change
  Documentation/dev-guide/apispec/swagger/rpc.swagger.json
  api/etcdserverpb/rpc.pb.go
  api/etcdserverpb/rpc.proto
  etcdctl/ctlv3/command/printer.go
  etcdctl/ctlv3/command/printer_fields.go
  scripts/etcd_version_annotations.txt
  server/etcdserver/api/v3rpc/maintenance.go
  tests/e2e/cluster_downgrade_test.go
  tests/framework/e2e/cluster.go
  tests/framework/e2e/downgrade.go
  tests/robustness/failpoint/cluster.go
Labels: area/documentation, area/testing, area/etcdctl, area/robustness-testing, size/XXL, approved

#19472 Add release team leads and additional release team members
  Documentation/contributor-guide/release.md
Labels: area/documentation, size/XS, approved

#19474 CHANGELOG: update 3.6 changelog with DowngradeInfo
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/S, approved

#19475 Address issues reported by golangci-lint after bumping the version to v1.64.5
  tests/integration/clientv3/examples/example_cluster_test.go
  tests/integration/clientv3/examples/example_kv_test.go
  tests/integration/clientv3/examples/example_lease_test.go
  tests/integration/clientv3/examples/example_maintenance_test.go
  tests/integration/clientv3/examples/example_metrics_test.go
  tests/integration/clientv3/examples/example_test.go
  tests/integration/clientv3/examples/example_watch_test.go
Labels: area/testing, size/L, approved

#19478 [3.5] dependency: Bump golang.org/x/crypto from v0.32.0 to v0.35.0
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: size/L, approved

#19477 [3.4] dependency: Bump golang.org/x/crypto from v0.32.0 to v0.35.0
  go.mod
  go.sum
Labels: size/S, approved

#19476 tests: deflakey TestLeaseGrantTimeToLiveExpired
  tests/common/lease_test.go
Labels: area/testing, size/S, approved

#19481 [3.6] Fix TestLeaseGrantTimeToLiveExpired flaky due to leader change
  tests/common/lease_test.go
Labels: area/testing, size/S, approved

#19466 [2025-02-22] Bump dependency updates identified by dependabot
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/rw-heatmaps/go.mod
  tools/rw-heatmaps/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19473 Fix flaky `TestLeaseKeepAliveOneSecond`
  tests/integration/clientv3/lease/lease_test.go
Labels: area/testing, size/XS, approved

#19484 Add release date for `v3.4.36` and `v3.6.0-rc.1`
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.6.md
Labels: stage/merge-when-tests-green, size/S, approved

#19486 Address Go 1.24 govet errors
  client/v3/retry_interceptor.go
  tests/integration/v3_lease_test.go
Labels: area/testing, area/clientv3, size/XS, approved

#19452 Add prometheus metric for server feature gate
  pkg/featuregate/feature_gate.go
  server/etcdserver/metrics.go
  server/etcdserver/server.go
  server/etcdserver/server_test.go
Labels: area/testing, area/etcdctl, stage/merge-when-tests-green, area/etcdutl, ok-to-test, size/M, approved, backport/v3.6

#19470 refactor: use a more straightforward return value
  client/v3/kv.go
  server/auth/jwt.go
Labels: area/clientv3, ok-to-test, size/XS, approved

#19496 github/workflows: delete grpcproxy workflow
  .github/workflows/grpcproxy.yaml
Labels: github_actions, size/M, approved

#19502 Add change log 3.7
  CHANGELOG/CHANGELOG-3.7.md
Labels: stage/merge-when-tests-green, ok-to-test, size/S, approved
