Repository etcd-io/etcd, pull requests merged in 2025-07, with the labels that each got.

#20266 chore(client): remove existFileOrDir funce
  tools/etcd-dump-db/main.go
  tools/etcd-dump-db/utils.go
Labels: area/tooling, size/S, approved

#20141 Move docker-compose.yml and Dockerfile.config to config directory
  tests/antithesis/Makefile
  tests/antithesis/config/Dockerfile
  tests/antithesis/config/docker-compose-1-node.yml
  tests/antithesis/config/docker-compose-3-node.yml
Labels: area/testing, size/S, approved

#20261 [2025-06-30] Manual Dependency Bump
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19988 Add review policy
  Documentation/contributor-guide/triage_prs.md
Labels: area/documentation, size/M, approved

#20285 cache: remove AfterRev entry predicate
  cache/demux.go
  cache/predicate.go
  cache/ringbuffer.go
  cache/ringbuffer_test.go
Labels: ok-to-test, size/M, approved

#20287 CHANGELOG(3.6): Add bbolt 1.4.2 entry
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#20291 [release-3.4] Avoid lowering revision of watchers in the future after restore
  mvcc/watchable_store.go
  mvcc/watchable_store_test.go
Labels: size/L, approved

#20181 Add Kubernetes API coverage test consuming traces
  tests/go.mod
  tests/robustness/coverage/README.md
  tests/robustness/coverage/coverage_test.go
  tests/robustness/coverage/kind-with-tracing.yaml
  tests/robustness/coverage/testdata/.gitignore
Labels: area/testing, area/robustness-testing, needs-ok-to-test, size/L, approved

#20295 Document #20221 in robustness track record
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
  CHANGELOG/CHANGELOG-3.6.md
  tests/robustness/README.md
Labels: area/testing, area/robustness-testing, size/XS, approved

#20293 [release-3.5] Fix error in pull-etcd-release-tests when running in Prow
  scripts/test_images.sh
Labels: size/S, approved

#20305 Fix yamllint errors
  tests/robustness/coverage/kind-with-tracing.yaml
Labels: area/testing, area/robustness-testing, ok-to-test, size/S, approved

#20309 Move EnsureTrace to traceutil
  pkg/traceutil/trace.go
  pkg/traceutil/trace_test.go
  server/etcdserver/apply/apply.go
  server/etcdserver/txn/delete.go
  server/etcdserver/txn/put.go
  server/etcdserver/txn/range.go
  server/etcdserver/txn/txn.go
  server/etcdserver/v3_server.go
Labels: ok-to-test, size/M, approved

#20314 [release-3.6] Bump go to 1.23.11
  .go-version
  api/go.mod
  client/pkg/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
  tools/rw-heatmaps/go.mod
  tools/testgrid-analysis/go.mod
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/S, approved

#20315 [release-3.5] Remove Github Action Workflows
  .github/workflows/e2e.yaml
  .github/workflows/functional.yaml
  .github/workflows/govuln.yaml
  .github/workflows/release.yaml
  .github/workflows/tests-template.yaml
  .github/workflows/tests.yaml
Labels: size/L, approved

#20308 [2025-07-07] Manual Dependency Bump
  bill-of-materials.json
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#20325 Add OpenTelemetry Spans to Range and Txn
  pkg/go.mod
  pkg/traceutil/trace.go
  server/embed/config_tracing.go
  server/etcdserver/v3_server.go
  server/go.mod
  tests/integration/tracing_test.go
Labels: area/testing, ok-to-test, size/L, approved

#20324 CHANGELOG(3.4,3.5): Add Go 1.23.11 note
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test, size/XS, approved

#20322 [release-3.4] Bump Go to 1.23.11
  .go-version
  go.mod
  tools/mod/go.mod
Labels: ok-to-test, size/XS, approved

#20339 [release-3.5] Fix the issue that --force-new-cluster can't remove all other members in a corner case
  server/etcdserver/raft.go
  server/etcdserver/server.go
  tests/e2e/force_new_cluster_test.go
  tests/framework/e2e/cluster.go
  tests/framework/e2e/etcd_process.go
Labels: size/L, approved

#20341 Update 3.5 changelog to cover the --force-new-cluster issue
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#20331 Tooling: Added licence header
  scripts/build-binary.sh
  scripts/build-docker.sh
  scripts/build-release.sh
  scripts/build.sh
  scripts/build_lib.sh
  scripts/build_tools.sh
  scripts/codecov_upload.sh
  scripts/fix.sh
  scripts/fuzzing.sh
  scripts/genproto.sh
  scripts/markdown_diff_lint.sh
  scripts/measure-testgrid-flakiness.sh
  scripts/release.sh
  scripts/release_mod.sh
  scripts/sync_go_toolchain_directive.sh
  scripts/test.sh
  scripts/test_images.sh
  scripts/test_lib.sh
  scripts/test_utils.sh
  scripts/update_dep.sh
  scripts/update_proto_annotations.sh
  scripts/updatebom.sh
  scripts/verify_genproto.sh
  scripts/verify_go_versions.sh
  scripts/verify_golangci-lint_version.sh
  scripts/verify_proto_annotations.sh
Labels: ok-to-test, size/L, approved

#20347 cache: enable Watch on arbitrary start_revision
  cache/cache.go
  tests/integration/cache_test.go
Labels: area/testing, ok-to-test, size/L, approved

#20348 [2025-07-14] Manual Dependency Bump
  api/go.mod
  api/go.sum
  cache/go.mod
  cache/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/rw-heatmaps/go.mod
  tools/rw-heatmaps/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#20358 Update 3.5 changelog to cover the v2store check false alarm
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#20367 [release-3.5] Fix flaky TestCtlV2CustomContentWithAuthData
  tests/e2e/v2store_deprecation_test.go
Labels: size/XS, approved

#20368 Fix v2store check returning wrong result even there isn't any auth data
  server/etcdserver/api/membership/storev2.go
  server/etcdserver/api/membership/storev2_test.go
Labels: size/M, approved, backport/v3.6

#20371 Update 3.6 changelog to cover the v2store check returning wrong result
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#20380 [release-3.5] Updated help for --quota-backend-bytes
  etcd.conf.yml.sample
  server/etcdmain/config.go
  server/etcdmain/help.go
Labels: ok-to-test, size/XS, approved

#20385 modify the comment for the now public CancelReason
  client/v3/watch.go
Labels: area/clientv3, ok-to-test, size/XS, approved

#20359 Inject antithesis at verify.Verify
  tests/antithesis/server/Dockerfile
  tests/antithesis/server/inject/verify.patch
Labels: area/testing, size/M, approved

#20381 CHANGELOG(3.4,3.5,3.6): Add update in docs of --quota-backend-bytes
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
  CHANGELOG/CHANGELOG-3.6.md
Labels: ok-to-test, size/XS

#20388 etcdctl: refactor `printer_json` files
  etcdctl/ctlv3/command/printer_json_test.go
Labels: area/etcdctl, ok-to-test, size/L, approved

#20390 cache: rename ErrUnsupportedWatch, add ErrKeyRangeInvalid
  cache/cache.go
  tests/integration/cache_test.go
Labels: area/testing, needs-ok-to-test, size/S, approved

#20391 Check promotion against v2store when updating v2store
  server/etcdserver/api/membership/cluster.go
  tests/e2e/member_no_proxy_test.go
Labels: area/testing, size/M, approved, area/etcdserver, backport/v3.6

#20389 Add OpenTelemetry Spans to Put, DeleteRange, Compact
  server/etcdserver/v3_server.go
Labels: needs-ok-to-test, size/S, approved

#20387 [release-3.6] Check promotion against v2store when updating v2store
  server/etcdserver/api/membership/cluster.go
  tests/e2e/member_no_proxy_test.go
Labels: area/testing, size/M, approved

#20395 Update 3.6 changelog to cover the etcdserver bootstrap failure when replaying learner promotion operation
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#20397 Add missing keys_only attribute to tracing test
  tests/integration/tracing_test.go
Labels: area/testing, ok-to-test, size/XS, approved

#20399 cache: rename validateWatchRange as validateRequestRange
  cache/cache.go
  cache/cache_test.go
Labels: ok-to-test, size/XS, approved

#20398 expose IsSortSet so that cache can validate unsupported get flags
  client/v3/op.go
Labels: area/clientv3, ok-to-test, size/XS, approved

#20401 Update `etcdctl member remove` command to support printing clusterID and memberID in hex
  etcdctl/ctlv3/command/printer_json.go
  etcdctl/ctlv3/command/printer_json_test.go
Labels: area/etcdctl, ok-to-test, size/M, approved

#20404 robustness: update README.md
  tests/robustness/README.md
Labels: area/testing, area/robustness-testing, ok-to-test, size/XS, approved

#20405 Fix Antithesis makefile if statement
  tests/antithesis/server/Dockerfile
Labels: area/testing, size/XS, approved

#20365 netutil: Refactor IPv6 address comparison logic
  CHANGELOG/CHANGELOG-3.7.md
  pkg/netutil/host_normalize.go
  pkg/netutil/host_normalize_test.go
  pkg/netutil/netutil.go
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, ok-to-test, size/L, approved

#20421 Turn ETCD_VERIFY on for antithesis tests
  tests/antithesis/config/docker-compose-1-node.yml
  tests/antithesis/config/docker-compose-3-node.yml
Labels: area/testing, size/XS, approved

#20419 cache: refactor validateWatch to use a switch for unsupported watch ops
  cache/cache.go
Labels: ok-to-test, size/S, approved

#20417 [2025-07-28] Manual Dependency Bump
  api/go.mod
  api/go.sum
  cache/go.mod
  cache/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/rw-heatmaps/go.mod
  tools/rw-heatmaps/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved, lgtm

#20416 Update `etcdctl member promote` command to support printing clusterID and memberID in hex
  etcdctl/ctlv3/command/printer_json.go
  etcdctl/ctlv3/command/printer_json_test.go
Labels: area/etcdctl, ok-to-test, size/M, approved

#20422 [release-3.6] Remove the --experimental-snapshot-catch-up-entries from help
  server/etcdmain/help.go
Labels: size/XS, approved

#20427 tests: add robustness test for issue 15220
  tests/robustness/Makefile
  tests/robustness/README.md
Labels: area/testing, area/robustness-testing, ok-to-test, size/S, approved
