Repository etcd-io/etcd, pull requests merged in 2025-01, with the labels that each got.

#19121 [2024-12-30] Manual Dependency Bump
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
Labels: area/testing, area/etcdutl, size/S, approved

#19136 Fix the inconsistent between listen peerURL and advertise peerURL
  tests/framework/integration/cluster.go
  tests/integration/clientv3/cluster_test.go
Labels: area/testing, size/S, approved

#19145 [3.5] Fix mixVersion test case: ensure a snapshot to be sent out
  server/etcdserver/server.go
  tests/e2e/etcd_mix_versions_test.go
Labels: size/XS, approved

#19137 Use new interface in robustness tests
  tests/robustness/client/client.go
  tests/robustness/failpoint/trigger.go
  tests/robustness/traffic/etcd.go
  tests/robustness/traffic/kubernetes.go
Labels: area/testing, area/clientv3, area/robustness-testing, ok-to-test, size/L, approved

#19139 Avoid deadlock in etcd.Close when stopping during bootstrapping
  server/embed/etcd.go
  server/embed/serve.go
  server/etcdserver/server.go
  tests/integration/embed/embed_test.go
Labels: area/testing, backport/v3.5, ok-to-test, size/M, approved

#19128 Update etcdutl migrate command: load wal records from the latest snapshot
  etcdutl/etcdutl/migrate_command.go
  etcdutl/etcdutl/migrate_command_test.go
  tests/e2e/utl_migrate_test.go
Labels: area/testing, area/etcdutl, size/L, approved

#19113 [3.5] support custom content check offline in v2store
  etcdutl/ctl.go
  etcdutl/etcdutl/check_command.go
  tests/e2e/v2store_deprecation_test.go
Labels: size/L, approved

#19151 CHANGELOG: update CHANGELOG-3.5.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: stage/merge-when-tests-green, size/XS

#19153 Fix release_notes.tpl.txt by adding a space between Docker image name and version
  scripts/release_notes.tpl.txt
Labels: stage/merge-when-tests-green, size/S, approved

#19154 [3.5] bump golang.org/x/crypto from 0.21.0 to 0.32.0
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: size/L, approved

#19161 [3.5] Fix release_notes.tpl.txt by adding a space between Docker image name and version
  scripts/release_notes.tpl.txt
Labels: size/S, approved

#19162 [3.4] Fix release_notes.tpl.txt by adding a space between Docker image name and version
  scripts/release_notes.tpl.txt
Labels: size/S, approved

#19158 [3.5] bump golang.org/x/net from 0.25.0 to 0.34.0
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
Labels: size/M, approved

#19160 robustness: only run MemberDowngrade test for high SnapshotCatchUpEntries
  tests/robustness/failpoint/cluster.go
  tests/robustness/scenarios/scenarios.go
Labels: area/testing, area/robustness-testing, size/XS, approved

#19112 rafthttp: Improve warn message in checkClusterCompatibilityFromHeader
  server/etcdserver/api/rafthttp/http.go
Labels: ok-to-test, size/XS, approved

#19164 [3.5] etcdutl/etcdutl: use datadir package to build wal/snapdir
  etcdutl/etcdutl/check_command.go
Labels: size/XS, approved

#19167 [3.5] Avoid deadlock in etcd.Close when stopping during bootstrapping
  server/embed/etcd.go
  server/embed/serve.go
  server/etcdserver/server.go
  tests/integration/embed/embed_test.go
Labels: ok-to-test, size/M, approved

#19166 [3.4] Avoid deadlock in etcd.Close when stopping during bootstrapping
  embed/etcd.go
  embed/serve.go
  etcdserver/server.go
  integration/embed_test.go
Labels: ok-to-test, size/M, approved

#19173 Move getLatestWALSnap into etcdutl/common.go
  etcdutl/etcdutl/common.go
  etcdutl/etcdutl/migrate_command.go
Labels: area/etcdutl, size/M, approved

#19175 tests: fix wrong number in comment.
  tests/robustness/traffic/kubernetes.go
Labels: area/testing, area/robustness-testing, ok-to-test, size/XS, approved

#19176 tests: use high burst value in limiter.
  tests/robustness/traffic/traffic.go
Labels: area/testing, area/robustness-testing, ok-to-test, size/XS

#19165 [2025-01-10] Bump dependency updates identified by dependabot
  api/go.mod
  api/go.sum
  client/pkg/go.mod
  client/pkg/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/etcdserver/api/v2store/store_ttl_test.go
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19174 Enhance test case TestEtctlutlMigrate to support multiple member cluster
  tests/e2e/utl_migrate_test.go
Labels: area/testing, size/M, approved

#19148 fix for #19066 Print warnings when deprecated options are configured in config file
  server/etcdmain/config.go
  server/etcdmain/config_test.go
Labels: ok-to-test, size/L, approved

#19181 client/pkg/logutil: add test for MergeOutputPaths
  client/pkg/logutil/zap_test.go
Labels: needs-ok-to-test, size/M, approved

#19171 Update 3.4/3.5 CHANGELOG with fix for deadlock in etcd.Close
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: ok-to-test, size/XS, approved

#19156 migrate flag experimental-corrupt-check-time to use corrupt-check-time
  server/embed/config.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
  tests/e2e/corrupt_test.go
  tests/framework/e2e/cluster.go
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/robustness-testing, area/etcdutl, ok-to-test, area/observability, size/L, approved

#19170 client/pkg/logutil: simplify MergeOutputPaths function
  client/pkg/logutil/zap.go
Labels: ok-to-test, size/M, approved

#19125 add MemberDowngradeUpgrade failpoint
  tests/e2e/cluster_downgrade_test.go
  tests/framework/e2e/curl.go
  tests/framework/e2e/downgrade.go
  tests/robustness/failpoint/cluster.go
  tests/robustness/failpoint/failpoint.go
Labels: area/testing, area/robustness-testing, size/L, approved

#19199 Rename migrate_command_test.go to common_test.go
  etcdutl/etcdutl/common_test.go
Labels: area/etcdutl, size/XS, approved

#19120 chore: enable use-any rule from revive
  server/embed/config.go
  server/storage/wal/wal_test.go
  tools/.golangci.yaml
Labels: area/tooling, size/M, approved

#19200 Minor refactor on RaftCluster.Recover()
  server/etcdserver/api/membership/cluster.go
Labels: size/S, approved

#19197 [3.4] Bump golang.org/x/crypto and golang.org/x/net
  go.mod
  go.sum
Labels: ok-to-test, size/M, approved

#19169 Add Robustness test to reproduce issue 18089
  tests/robustness/README.md
  tests/robustness/main_test.go
  tests/robustness/makefile.mk
  tests/robustness/scenarios/scenarios.go
  tests/robustness/traffic/etcd.go
  tests/robustness/traffic/traffic.go
Labels: area/testing, area/robustness-testing, needs-ok-to-test, size/M, approved

#19196 migrate flag experimental-compaction-batch-limit to use compaction-batch-limit
  server/embed/config.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
  tests/e2e/corrupt_test.go
  tests/framework/e2e/cluster.go
  tests/robustness/failpoint/trigger.go
  tests/robustness/options/server_config_options.go
Labels: area/testing, area/robustness-testing, ok-to-test, size/L, approved

#19212 [3.4] Bump go toolchain to 1.22.11
  .go-version
  go.mod
  tools/mod/go.mod
Labels: size/XS

#19211 [3.5] Bump go toolchain to 1.22.11
  .go-version
  api/go.mod
  client/pkg/go.mod
  client/v2/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  raft/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
Labels: size/S, approved

#19093 Prevent leaking file descriptor during snapshotting and provide better logging of errors
  client/v3/snapshot/v3_snapshot.go
Labels: area/clientv3, size/M, approved

#19209 [2025-01-16] Bump dependency updates identified by dependabot
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19224 changelog: update Go entry to reflect 1.22.11 update
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#19226 robustness: do not panic when parsing unknown versions.
  tests/framework/e2e/downgrade.go
Labels: area/testing, size/M, approved

#19214 Update golang toolchain to 1.23.5
  .go-version
  api/go.mod
  client/internal/v2/go.mod
  client/pkg/go.mod
  client/v3/go.mod
  etcdctl/go.mod
  etcdutl/go.mod
  go.mod
  pkg/go.mod
  server/go.mod
  tests/go.mod
  tools/mod/go.mod
  tools/rw-heatmaps/go.mod
  tools/testgrid-analysis/go.mod
Labels: area/performance, area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, ok-to-test, size/S, approved

#19198 server/proxy/tcpproxy: reuse addr in TCPProxy.Run
  server/proxy/tcpproxy/userspace.go
Labels: ok-to-test, size/XS, approved

#19201 flags: optimise memory allocation
  pkg/flags/selective_string.go
  pkg/flags/unique_strings.go
Labels: stage/merge-when-tests-green, ok-to-test, size/XS, approved

#19152 chore: enable early-return and superfluous-else from revive
  contrib/lock/client/client.go
  etcdctl/ctlv3/command/check.go
  etcdctl/ctlv3/ctl.go
  pkg/flags/selective_string.go
  server/etcdserver/api/v2store/store.go
  server/etcdserver/cluster_util.go
  server/proxy/grpcproxy/watcher.go
  server/storage/mvcc/watchable_store.go
  tests/framework/e2e/cluster.go
  tests/integration/clientv3/metrics_test.go
  tests/integration/v3_alarm_test.go
  tests/integration/v3_failover_test.go
  tests/robustness/validate/patch_history.go
  tools/.golangci.yaml
  tools/etcd-dump-logs/raw.go
Labels: area/testing, area/tooling, area/etcdctl, area/contrib, area/robustness-testing, size/L, approved

#19230 wait for the member to get started
  tests/common/auth_test.go
Labels: area/testing, size/XS, approved

#19188 mvcc: restore tombstone index if it's first revision
  server/storage/mvcc/key_index.go
  server/storage/mvcc/key_index_test.go
  server/storage/mvcc/kv_test.go
  server/storage/mvcc/kvstore.go
  tests/e2e/watch_test.go
Labels: area/testing, backport/v3.4, backport/v3.5, size/L, approved

#19218 Fix passing compaction-batch-limit to etcd v3.4 and v3.5
  tests/robustness/failpoint/trigger.go
  tests/robustness/options/server_config_options.go
  tests/robustness/scenarios/scenarios.go
Labels: area/testing, area/robustness-testing, size/S, approved

#19233 Add compaction to kubernetes robustness tests
  tests/robustness/traffic/etcd.go
  tests/robustness/traffic/kubernetes.go
  tests/robustness/traffic/traffic.go
Labels: area/testing, area/robustness-testing, needs-ok-to-test, size/L, approved

#19105 tests: address bridge unexported return issue
  tests/framework/integration/bridge.go
  tests/framework/integration/cluster.go
Labels: area/testing, ok-to-test, size/S, approved

#19246 [2025-01-21] Bump dependency updates identified by dependabot
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19247 Add tests for NewConfig matching AddFlags defaults
  server/embed/config_test.go
Labels: size/S, approved

#19086 etcdserver: add learner check to readyz
  server/etcdserver/api/etcdhttp/health.go
  server/etcdserver/api/etcdhttp/health_test.go
Labels: ok-to-test, size/M, approved

#19249 [3.5] mvcc: restore tombstone index if it's first revision
  server/mvcc/key_index.go
  server/mvcc/key_index_test.go
  server/mvcc/kv_test.go
  server/mvcc/kvstore.go
  tests/e2e/watch_test.go
Labels: size/L, approved

#19251 [3.4] mvcc: restore tombstone index if it's first revision
  mvcc/key_index.go
  mvcc/key_index_test.go
  mvcc/kv_test.go
  mvcc/kvstore.go
  tests/e2e/watch_test.go
Labels: size/L, approved

#19221 Fix race condition (also a regression of the PR 19139)
  server/embed/etcd.go
  server/embed/serve.go
Labels: area/testing, backport/v3.5, size/M, approved

#19245 Add tests for hardcoded flags in TestEtcdServerProcessConfig
  tests/framework/e2e/cluster.go
  tests/framework/e2e/cluster_test.go
Labels: area/testing, size/L, approved

#19259 Update 3.5 changelog to cover the race condition fix
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#19260 CHANGELOG: update backport info for #19179
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#19257 Refactoring the error handlers concurrent control implementation
  server/embed/etcd.go
  server/embed/serve.go
Labels: size/M, approved

#19232 build(deps): bump github.com/golang-jwt/jwt from v4 to v5
  bill-of-materials.json
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  server/auth/jwt.go
  server/auth/jwt_test.go
  server/auth/options.go
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
Labels: area/testing, area/tooling, area/etcdutl, size/M, approved

#19248 migrate flag experimental-watch-progress-notify-interval to use watch-progress-notify-interval
  server/embed/config.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
  tests/e2e/watch_test.go
  tests/framework/e2e/cluster.go
  tests/robustness/scenarios/scenarios.go
Labels: area/testing, area/robustness-testing, ok-to-test, size/L, approved

#19265 Remove explicit random seed in robustness tests
  tests/robustness/main_test.go
Labels: area/testing, area/robustness-testing, needs-ok-to-test, size/XS, approved

#19263 Remove the code of checking ClusterVersionSet in MinimalEtcdVersion
  server/storage/schema/schema_test.go
  server/storage/wal/version.go
  server/storage/wal/version_test.go
  tests/integration/utl_wal_version_test.go
Labels: area/testing, size/M, approved

#19264 migrate to use warning-apply-duration flag
  server/embed/config.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
Labels: ok-to-test, size/M, approved, lgtm

#19266 docs(CHANGELOG): add release date of etcd v3.5.18
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#19267 migrate to use bootstrap-defrag-threshold-megabytes flag
  server/config/config.go
  server/embed/config.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
  server/etcdserver/bootstrap.go
Labels: ok-to-test, size/L, approved

#19272 tests: Add retry if promote member fails.
  tests/e2e/runtime_reconfiguration_test.go
Labels: area/testing, needs-ok-to-test, size/S, approved

#19279 Fix addMemberAsLearnerAndPromote to avoid error 'etcdserver: can only…
  tests/e2e/runtime_reconfiguration_test.go
Labels: area/testing, size/XS, approved

#19255 Add Version field to the robustness model
  tests/robustness/client/client.go
  tests/robustness/model/describe.go
  tests/robustness/model/deterministic.go
  tests/robustness/model/deterministic_test.go
  tests/robustness/model/history.go
  tests/robustness/model/non_deterministic_test.go
  tests/robustness/report/wal.go
  tests/robustness/traffic/kubernetes.go
  tests/robustness/validate/operations_test.go
  tests/robustness/validate/validate_test.go
Labels: area/testing, stage/merge-when-tests-green, area/robustness-testing, ok-to-test, size/L, approved

#19269 tests/robustness: continue should ignore last key
  tests/robustness/traffic/kubernetes.go
Labels: area/testing, area/robustness-testing, size/XS, approved

#19276 [Solution 2] Add `DowngradeVersionTestRequest` for Downgrade or migration test only
  api/etcdserverpb/raft_internal.pb.go
  api/etcdserverpb/raft_internal.proto
  api/etcdserverpb/rpc.pb.go
  api/etcdserverpb/rpc.proto
  scripts/etcd_version_annotations.txt
  server/etcdserver/server.go
  server/storage/schema/schema_test.go
  server/storage/wal/version.go
  server/storage/wal/version_test.go
Labels: size/XXL, approved

#19281 Fix documentation of List method of Kubernetes interface
  client/v3/kubernetes/interface.go
Labels: area/clientv3, needs-ok-to-test, size/S, approved

#19244 Add downgrade cancellation e2e tests
  etcdctl/README.md
  tests/e2e/cluster_downgrade_test.go
  tests/framework/e2e/downgrade.go
  tests/framework/e2e/etcdctl.go
Labels: area/testing, area/etcdctl, stage/merge-when-tests-green, size/M, approved

#19280 add learner check to readyz
  server/etcdserver/api/etcdhttp/health.go
  server/etcdserver/api/etcdhttp/health_test.go
Labels: ok-to-test, size/M, approved, lgtm

#19293 [2025-01-28] Bump dependency updates identified by dependabot
  api/go.mod
  api/go.sum
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/mod/go.mod
  tools/mod/go.sum
  tools/testgrid-analysis/go.mod
  tools/testgrid-analysis/go.sum
Labels: area/testing, area/clientv3, area/tooling, area/etcdctl, area/etcdutl, size/L, approved

#19291 changelog: add mixed rw performance evaluation backport
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#19298 migrate to use max-learners flag
  server/config/config.go
  server/embed/config.go
  server/embed/etcd.go
  server/etcdmain/config.go
  server/etcdmain/config_test.go
  server/etcdmain/help.go
  server/etcdserver/bootstrap.go
  server/etcdserver/bootstrap_test.go
  tests/framework/integration/cluster.go
  tests/integration/clientv3/cluster_test.go
Labels: area/testing, ok-to-test, size/L, approved

#19294 changelog: add entries regarding 3.5.18 dependency updates
  CHANGELOG/CHANGELOG-3.5.md
Labels: size/XS, approved

#19308 [test] Close the http response body
  tests/e2e/metrics_test.go
Labels: area/testing, size/XS, approved

#19300 fix(alerts): set severity of 'ectdMembersDown' from 'critical' to 'wa…
  contrib/mixin/alerts/alerts.libsonnet
  contrib/mixin/test.yaml
Labels: area/contrib, ok-to-test, area/observability, size/M, approved

#19310 Fix goword errors
  tests/integration/embed/embed_proxy_test.go
Labels: area/testing, size/XS, approved

#19297 Mark etcd-local-tester as deprecated so we can remove it in future
  tools/local-tester/README.md
  tools/local-tester/bridge.sh
  tools/local-tester/bridge/bridge.go
  tools/local-tester/bridge/dispatch.go
Labels: area/testing, area/tooling, size/XS, approved

#19195 Switch from grpc-ecosystem/go-grpc-prometheus to grpc-ecosystem/go-grpc-middleware/providers/prometheus
  bill-of-materials.json
  bill-of-materials.override.json
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  server/config/config.go
  server/embed/etcd.go
  server/etcdmain/grpc_proxy.go
  server/etcdserver/api/v3rpc/grpc.go
  server/etcdserver/api/v3rpc/metrics.go
  server/go.mod
  server/go.sum
  tests/framework/integration/cluster.go
  tests/go.mod
  tests/go.sum
  tests/integration/clientv3/examples/example_metrics_test.go
  tests/integration/clientv3/metrics_test.go
Labels: area/testing, area/clientv3, area/etcdctl, area/etcdutl, ok-to-test, size/L, approved

#19311 Update 3.6 changelog to cover the go-grpc-middleware/providers/promet…
  CHANGELOG/CHANGELOG-3.6.md
Labels: size/XS, approved

#19305 scripts/test_images.sh: refactor to import job into the prow infrastructure
  scripts/test_images.sh
Labels: size/L, approved

#19192 Correct compaction period comments
  server/etcdserver/api/v3compactor/periodic.go
Labels: ok-to-test, size/XS, approved

#19313 deflaky: TestSnapshotStatus
  etcdutl/snapshot/v3_snapshot_test.go
Labels: area/etcdutl, size/XS, approved
